### ISSUE TITLE
sensitive to h2o2

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1395]
is there a reason why sensitive to h2o2 is not a child of sensitive to oxidative stress?

Original comment by: Antonialock

**Comment by ValWood** [comment]
@bahler
@manulera 
i think we could add this parentage. I don't really fully understand why it could not be added. Maybe @Antonialock does?

Maybe because  causes problems that are not directly related to oxidative stress?
but based on the GO hierarchy, it should probably be added:
https://www.ebi.ac.uk/QuickGO/term/GO:0070301

**Comment by Antonialock** [comment]
I asked for this connection - I never fully understood the reason but I suspect it might have to do with that certain chemicals could induce a range of different stresses.

For example, addition of CaCl2 could induce salt stress, osmotic stress, calcium stress (I suppose?!).

From memory there are other chemicals in the FYPO 'sensitive to...' branch that induce oxidative stress: t-BOOH, menadione...

**Comment by ValWood** [comment]
being pragmatic, I agree users would exprect to retrieve 'sensitive to hydrogen peroxide' from 'senstive to oxidative stress' so I added the additional parent "sensitive to oxidative stress'

We can deal with any fall out later.

**Comment by ValWood** [comment]
That's better.
