### ISSUE TITLE
abolished division timing control in response to nitrogen availability

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2236]
abolished division timing control in response to nitrogen availability

A population phenotype in which the  effect of nitrogen source on timing of nuclear division is abolished

(I hope you can make this better!)

PMID:689088

**Comment by mah11** [comment]
Would it work to call it "abolished regulation of cell division upon nitrogen source shift"?

If not, could use "abolished cell division rate change upon nitrogen source shift"

possible def: A phenotype in which a cell does not alter the timing or rate of cell division when shifted from one nitrogen source to another. Normally, cell division is delayed upon shifting from a poor to a rich nitrogen source, and accelerated upon shifting from a rich to a poor nitrogen source.

Does it have to be a population phenotype? Obviously they looked at populations in this paper, but could the phenotype also be observed at the cell level in a different experiment?

possible synonyms
synonym: abolished change in cell division rate upon nitrogen source shift
synonym: abolished nutritional modulation of cell division RELATED
synonym: unchanged cell division rate upon nitrogen source shift EXACT

Also note that PECO has a couple of "nitrogen source shift" terms you could use for the annotations.

**Comment by ValWood** [comment]
Yes this works (I think the abolished cell division rate change upon nitrogen source shift is best....or could it even be 
abolished cell division timing change upon nitrogen source shift?)

I'm not sure if it can be cell. Out of my comfort zone with these papers, but they have been 'trending' for a while so I thought I would bight the bullet.  

If I understand correctly, the phenotype could be observed  at the cell level. However I'm not sure if you could conclude anything from a single cell because a population divides at a range of sizes and these  types of experiments report a deviation from a population *average*.  It feels like it needs to be population because of this?

**Comment by mah11** [comment]
OK, have put it in as a population phenotype for now. That means it isn't under anything cell cycle, because the "cell cycle phenotype" ancestor term is under cell phenotype (via cellular process phenotype).

  abolished cell division timing change upon nitrogen source shift FYPO:0004701

I'm slightly worried that "timing" is a bit woolly, but I tried to figure out whether the actual rate of division (aka cycle duration) was changing but got too confused. Hey ho ...

edit file a1f756ac121fb02f150b11ad8be96320fbb10b03
release ddd4e270a2170a940afaaf394d41d2784f48b0af
