### ISSUE TITLE
ribosome biogenesis phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2241]
lower levels of 80S monosomes
A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which cells contain fewer 80S monosomes in the cytosol than normal.
and 
higher levels of half-mer polysomes
A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which cells contain more half-mer polysomes in the cytosol than normal.

PMID:26122634, doing a) because its only a couple of experiments and its a new gene characterization. I needed a quick one because the paper I did yesterday took 6hours....

**Comment by ValWood** [comment]
decreased 60S:40S subunit ratio

**Comment by mah11** [comment]
I have followed the GO convention of leaving the sizes out of primary names, but have made the size-specific synonyms exact because that should be safe for the fission yeasts. And I learned what a half-mer polysome is.

  decreased cytosolic monomeric ribosome level FYPO:0004706
  increased cytosolic half-mer polysome level FYPO:0004707
  decreased cytosolic large:small ribosomal subunit ratio FYPO:0004708

edit file a1f756ac121fb02f150b11ad8be96320fbb10b03
release ddd4e270a2170a940afaaf394d41d2784f48b0af
