### ISSUE TITLE
add synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2250]
FYPO:0004616
Abolished microtubule catastrophe
Abolished microtubule shrinkage

"
Significantly, we found that the MT plus ends had a profound defect in MT catastrophe. In our analysis of speck- led MTs, we noted no instances of MT plus-end shrinkage within the time frames of the movies (2–5 min). These ends did not shrink upon hitting the cell tip, but instead contin- ued to grow and curved around the cell tips (n 􏰍 15). "

PMID:15772152

**Comment by mah11** [comment]
These synonyms were included when the term was added:

id: FYPO:0004616
name: abolished cytoplasmic microtubule depolymerization at plus end at cell tip
[snip def & other synonyms]
synonym: "abolished microtubule catastrophe at cell tip" RELATED [PomBase:vw]
synonym: "abolished microtubule plus end shrinkage at cell tip" RELATED [PomBase:vw]

I made the "catastrophe" synonym related because they didn't see any depolymerization (i.e. it's not just absence of the really fast depolymerization of "catastrophe").  I'm not sure if "shrinkage" corresponds more closely to depolymerization generally or catastrophe specifically, but maybe that one could be exact .

**Comment by ValWood** [comment]
OK , I didn't click what I was looking for when searching....
