### ISSUE TITLE
name long curved cytoplasmic microtubules

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2257]
Should we add a comment that these curve around the cell tip? 
or do they occur in other circumstances?

**Comment by mah11** [comment]
I wouldn't say anything that would restrict the term only to cases where the MTs curve around the cell tip, because some pics show MTs that are curved along their whole length even though they aren't quite long enough to reach all the way around the tip. E.g. gtb1-22 & gtb 1-29 PMID:15280226 fig 5B (other alleles are more severe and do curve all the way round the tip).

But no prob to add a comment saying it can happen.

**Comment by ValWood** [comment]
It might help, I always wonder if I need another term for the ones which curl all around the tip, but it seems its just a stronger version of the same phenotype.

**Comment by mah11** [comment]
comment added

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
