### ISSUE TITLE
ntr: pre meiotic DNA rereplication

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2270]
def
A regulation phenotype observed in the meiosis I in which negative regulation of the initiation of DNA-dependent DNA replication is abnormal during pre meiotic DNA replication, resulting in one or more rounds of rereplication of the entire genome.

PMID:25891897

**Comment by mah11** [comment]
oof. more work than it looked like, because the existing terms were implicitly specific for mitotic DNA replication and had to be renamed.

I think you want FYPO:0004759 for the annotation(s).

  abnormal regulation of DNA replication initiation FYPO:0004756
  abnormal negative regulation of DNA replication initiation FYPO:0004757
  abnormal negative regulation of premeiotic DNA replication initiation FYPO:0004758
  abnormal negative regulation of premeiotic DNA replication initiation resulting in complete rereplication FYPO:0004759

**Comment by ValWood** [comment]
maybe they have only been used for mitotic phenotypes?

**Comment by mah11** [comment]
edit file: 0f9dda8eb776ac06d7de0f4795eb1ae6da751294
release: 863e7570fe1db168c75b987dcd624cf183f18827
