### ISSUE TITLE
Re: decreased meiosis II

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2271]
Obsolete this term (population phenotype).
Rehouse existing annotations, with abolished+penetrance  or request a new population term

**Comment by ValWood** [comment]
I guess the first step is to do the annotation check and see if these can move

SPBC17D1.07c	npg1	II	GTPase regulator Rng2-like (predicted) 
SPBC1778.04	spo6	II	Spo4-Spo6 kinase complex regulatory subunit Spo6 

then it can just be obsoleted

**Comment by mah11** [comment]
also check FYPO:0000476 'decreased meiosis' and FYPO:0003380 decreased meiosis I'

as noted in email, I'll move the existing term if anyone wants to keep population phenotype annotations; there aren't enough to make it worth the bother of creating a new term (also, it's kind of correcting the placement of a term that applied at the population level all along rather than a different concept)

**Comment by mah11** [comment]
Just remembered: the other catch is that it'll cause parentage headaches use population terms for these. (I suspect that's why I've shoved the problem under the rug this long ...) We would either have to move the "abnormal" term  (currently the parent of "decreased" and "increased" out from under cell phenotype -- and it couldn't go under population phenotype either, because it would have an is_a child in each branch -- or we lose the link between "abnormal" and "decreased" for these specific ones. That makes me lean in favor of just obsoleting the "increased" and "decreased" terms and not replacing them. Push the abolished+penetrance alternative instead.

Also, be warned: there are lot of annotations using FYPO:0000584 & FYPO:0000588 (the sporulation terms).

**Comment by Antonialock** [comment]
only problem I see is that if you are only interested in the mutants where a process is completely broken, then you can't pull those out if we don't make the distinction between "abolished" and "abolished in some" (=decreased).

I don't know if this is important to people but seems like it could be.

**Comment by mah11** [comment]
Eventually that would be fixed by having the search able to take penetrance into account (and it's only an issue for a handful of processes). I suppose we could postpone adjusting the ontology until the search capabilities catch up, but it might be a long time.

**Comment by mah11** [comment]
processes for which this is relevant:

conjugation/mating
meiosis
sporulation
apoptosis

anything else?

**Comment by Antonialock** [comment]
would we add the extension "complete penetrance" for any annotations to "abolished" made so far without a penetrance extension?

**Comment by mah11** [comment]
I think yes, but of course it's hard to be sure without actually checking the annotations.

Looks like I shouldn't mess with this bit of the ontology for at least a few days in any case!

**Comment by ValWood** [comment]
decreased sporulation 73
decreased apoptosis (no term) 0
decreased meiosis 13
decreased conjugation frequency (44 but that one's OK, cos it really is a population term)

abolished meiosis 17
abolished sporulation 54 
(as antonia says, add 100% penetrance automatically maybe?)

As it is only 2 terms and their descendants which are affected I don't think its a big issue to lose the distinction between abolished/decreased for a short time....

Or I'm still  open to adding  
"decreased sporulation efficiency" as a population term for the 73....

**Comment by mah11** [comment]
Don't forget increased sporulation.

Increased apoptosis and decreased apoptosis exist but don't have any annotations.

I can recast increased/decreased sporulation/meiosis as "x frequency" if you're happy to have them directly under population phenotype, without a connection to the corresponding "abnormal cell phenotype" term, as is the case for the conjugation frequency terms.

**Comment by ValWood** [comment]
I think we should do that, its the easiest solution.

But should we  ask kim to add a penetrance to the abolished?  Because from now on we should only use this with some penetrance....

And for these terms could they have 'related synonyms' for decreased terms and a comment that  the penetrance should be supplied if possible?

**Comment by Antonialock** [comment]
also decreased spore germination (child of viable spore population then?)

**Comment by mah11** [comment]
I'll double-check when I get back to this ticket to do the work, but probably yes, I'll do spore germination as well.

**Comment by mah11** [comment]
recast some existing 'increased/decreased' as population-level 'increased/decreased frequency' (deleted xps):
  FYPO:0000376, FYPO:0000377 apoptosis
  FYPO:0000476, FYPO:0003380, FYPO:0003789 meiosis
  FYPO:0000581 spore germination
  FYPO:0000584, FYPO:0000588, FYPO:0002052 sporulation

**Comment by mah11** [comment]
edit file: d8336ce9c1bf6f49b17dced4e4f2afd769d6cbb2
release: 8a9c45cd3600794a1651f7865b5290988dd03528
