### ISSUE TITLE
ntr: abolished protein localization to meiotic kinetochore during meiosis I   + .....

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2276]
term: abolished protein localization to meiotic kinetochore during meiosis I 
def:
A cell phenotype in which the localization of a protein to the kinetochore of a chromosome is abolished during the first meiotic nuclear division.

descendent of FYPO:0001375

**Comment by ValWood** [comment]
just spotted
decreased protein localization to kinetochore during meiosis I
so maybe need a grouping term if  "abolished' can't be a descendent of 'decreased'

**Comment by ValWood** [comment]
also
normal protein localization to meiotic spindle pole body during meiosis I

descendent of
FYPO:0003541	normal protein localization to meiotic spindle pole body

**Comment by mah11** [comment]
abnormal protein localization to kinetochore during meiosis FYPO:0004762
  abolished protein localization to kinetochore during meiosis I FYPO:0004763
  normal protein localization to meiotic spindle pole body during meiosis I FYPO:0004764

I won't add any other grouping terms for now, because there may be some relief on the abolished/decreased front in PATO ... at least, they were considering it when I asked a while back. I've prodded again to see if they've made a decision/forgotten about the question/etc.

https://github.com/pato-ontology/pato/issues/46

**Comment by mah11** [comment]
edit file: 71c1d4c3495fa0675989a8523d3bcec4357fa04f
release: 7cda3fe634db6b3967c97dd04819d944aab4629b
