### ISSUE TITLE
ntr abolished protein phosphorylation of condensin PMID:25520186

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2278]
I want to capture a phenotype which abolished phosphorylation of the condensin complex.

abolished protein phosphorylation of condensin complex

(I guess when we have complex IDs we can get rid of these terms and use the complex ID in assayed_using)?

PMID:25520186

**Comment by mah11** [comment]
I would MUCH rather do this as "abolished protein phosphorylation" with annotation extensions up front. I don't want to set a precedent for adding any "[changed] phosphorylation of [x] complex" terms because it could lead to a slew of similar requests. there's also no "protein complex phosphorylation" term in GO , so we would be out on a limb there.

I don't think we'll even lose much information if you use "abolished protein phosphorylation" with the individual genes/proteins in extensions. They know which subunits are phosphorylated in wt and not in the mutant, and we have those subunits annotated as being in the condensin complex, so people interested in this area will be able to connect the dots.

**Comment by ValWood** [comment]
MAkes sense, I used the individual genes
