### ISSUE TITLE
glucose starvation vs. glucose limitation

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#2300]
In #1687, we discussed "glucose limitation" and whether it's the same as "glucose starvation" or not. We eventually added FYPO:0003743, decreased cell population growth during glucose limitation, with a comment explaining glucose limitation as below about 4.4 mM (0.08%), but above zero.

Since then, we've added three other terms using "glucose limitation" in the names, with the same comment (FYPO:0003938, FYPO:0004168, FYPO:0004765). All four terms are used in annotations.

Now the question has (re-)arisen whether we should continue to make a distinction between limitation and starvation for glucose. In #2298 Antonia said:

"I don't think we need to distinguish between glucose starvation and limitation, I think it is the same response."

I (Midori) added the new terms requested in #2298, and am transferring the follow-up discussion of the starvation/limitation question here.

**Comment by mah11** [comment]
From the follow-up exchange:

Midori: The starvation vs limitation split comes from #1687 -- I got the impression that Val wanted to make the distinction (so she probably still does).

M: #1687 includes the question about glucose limitation vs. glucose starvation, and is the one where the first glucose limitation term was added. I asked Val whether "glucose starvation" would do for her request, and if not, how to define the difference between "glucose starvation" and "glucose limitation". I don't think there's a great answer in the ticket comments. I ended up going with starvation = no glucose at all and limitation = below 4.4 mM (0.08%) but not zero, but I've been aware all along that that information really belongs in conditions.

Val: I think it is important to keep the distinction but I don't know how best to do it. Happy for any solution.

V: Basically the limitation was not starvation, but 4.4 mM which would be considered low glucose.
I can't see the original ticket but we had a long discussion among ourselves and it was based on suggestions from the authors, who wanted us to represent that the response is different from the normal level of glucose supplied (which is really excess glucose).

**Comment by mah11** [comment]
More transferred from #2298:

Val: 
This is the session the term was created for
http://curation.pombase.org/pombe/curs/b5db93caaa51792d/ro/
there are other genes annotated to
decreased cell population growth during glucose limitation
which may not be 'low glucose' as defined here, namely for gene products
gpa2
sds23
ssp1
trt1

----

Val:
ssp1 and sds23 are OK, from hanyu et al
so only gpa2 and trt1 will need checking (when we decide the best way to proceed).

I'd like to keep a term to represent this in some way if it is possible, as it does seem to be a specific adaptation to low glucose (probably normal in the wild when glucose is unlikely to be in such excess)

**Comment by mah11** [comment]
More transferred from #2298:

> Val: Is the "adaptation to low glucose" different from the response to "no glucose"?

Antonia: I can't imagine it is (surely, in no glucose, the cells would fire the "low glucose" response? i.e. a starvation response)

**Comment by mah11** [comment]
>>     Val: Is the "adaptation to low glucose" different from the response to "no glucose"?
> 
> Antonia: I can't imagine it is (surely, in no glucose, the cells would fire the "low glucose" response? i.e. a starvation response)

Val: Nope its different. See the old thread. IIRC the argument is that this low level of glucose is what fission yeast more than likely encounter in the wild. What is normally observed in laboratory setting with excess glucose is probably different from the pathways which are activated in the wild in low glucose.

**Comment by mah11** [comment]
Val: http://www.ncbi.nlm.nih.gov/pubmed/24815688?dopt=Abstract

**Comment by mah11** [comment]
Now commenting for myself at last ...

I'm not convinced that "the old thread" (#1687) did satisfactorily answer the question of whether there's a difference between glucose *limitation* (aka low glucose, aka less than about 4.4 mM) and glucose *starvation*. I also don't see how it helps to know that laboratory media usually have lots more glucose than yeasties typically find in the wild.

What is the difference in response to low glucose versus none at all?

**Comment by Antonialock** [comment]
No glucose at all -> cells die after a few days
"low" glucose -> cells reprogramme their gene expression profile compared to when in "high glucose".

I don't like having the def in there about 4.4 mM glucose. This level is chosen because:
"we previously reported that fission yeast can proliferate at essentially normal rates in media containing as little as 0.08% (4.4 mM) glucose, which is equivalent to the blood glucose level in a healthy human before breakfast"

It doesn't really have anything to do with pombe in the wild (I'd guess pombe in the wild would grow on complex mixtures of different stuff, and the levels of each carbon source would fluctuate)

I just want to make the distinction between "low enough glucose where the "low glucose" programme is active" & "high enough glucose so the "high glucose" programme is active" 
Maybe in reality there is even a grey-zone between these two states (some parts of each programme might overlap?)

**Comment by mah11** [comment]
> I don't like having the def in there about 4.4 mM glucose.

I totally agree; that's a condition, not part of the phenotypes.

And what I want to know is whether "low enough glucose where the "low glucose" programme is active" is the same as "glucose starvation". If there's no glucose (and no other carbon), do cells spend their remaining few days doing the same sort of gene expression as cells in low glucose? Or are there actually three situations: lots, a little, and none?

> It doesn't really have anything to do with pombe in the wild (I'd guess pombe in the wild would grow on complex mixtures of different stuff, and the levels of each carbon source would fluctuate)

Agree. "The wild" isn't even remotely homogeneous or constant over time or space.

> Maybe in reality there is even a grey-zone between these two states

I bet there is. This is biology, after all, so it's always safe to assume "it's more complicated than that".

**Comment by Antonialock** [comment]
Umm, I'm only guessing now but I'd guess they would first go through with the normal changes (upregulate high affinity glucose (and other other carbon transporters?)), that would obviously not "work" (because there is no carbon added in the media) so maybe they would upregulate autophagy, and maybe try and mate more than cells kept at 'some' glucose level?

**Comment by mah11** [comment]
phew, I don't think my head is getting any less melty ...

**Comment by ValWood** [comment]
In the abstract
S. pombe arrests cell cycle progression when transferred from media containing 2.0% glucose to media containing 0.1%. After a delay, S. pombe resumes cell division at a surprisingly fast rate, comparable to that observed in 2% glucose. We found that a number of genes, including zinc-finger transcription factor Scr1, CaMKK-like protein kinase Ssp1, and glucose transporter Ght5, enable rapid cell division in low glucose. 

The suspect it is due to a shift from glycolysis to respiration to maintain ATP production despite limiting glucose

I'm happy to capture this anyway, if you think that glucose limitation is inappropriate. I think it is worth capturing though.

**Comment by Antonialock** [comment]
I don't think glucose limitation is inappropriate.
I think that starvation = limitation.
= there is no point in maintaining two separate terms

**Comment by ValWood** [comment]
Ok, it sounds like a merge

**Comment by mah11** [comment]
OK, it sounds like Val & Antonia now agree that "glucose starvation" and "glucose limitation" are the same, at least for our phenotype annotation purposes. So what I'll do is:

- Standardize on "glucose starvation" in term names and "glucose limitation" in exact synonyms;

- Do any necessary merges; 

- Make sure definitions are consistent; 

- Delete comments with guff about glucose concentrations that belongs in conditions.

Shout soon if that would cause problems — next FYPO session is tomorrow ;)

**Comment by mah11** [comment]
didn't need any merges after all -- terms that used "limitation" up until a few minutes ago weren't otherwise identical to any "starvation" terms

**Comment by mah11** [comment]
edit file: 60400ab363d2deef2a6a0f3c814fc2c7142c5d6b
release: ad1a93ec3a6e446c7aa0632a50e74379931a8778
