### ISSUE TITLE
meiotic re-replication terms from Jacky's e-mail

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2307]
So the it would be

"pre meiotic DNA rereplication" term

cells undergo normal pre meiotic DNA replication followed by a further
round of DNA replication in the absence of nuclear division

Would this make sense (it follows the definition pattern for the mitotic
term):

Definition
A regulation phenotype observed in the meiosis I in which negative
regulation of the initiation of DNA-dependent DNA replication is
abnormal during pre meiotic DNA replication, resulting in one or more
complete or partial rounds of re-eplication of the  genome.

If not then I think what you have said is fine.

Jacky

**Comment by mah11** [comment]
Turns out I added two of these last month:

id: FYPO:0004758
name: abnormal negative regulation of premeiotic DNA replication initiation

id: FYPO:0004759
name: abnormal negative regulation of premeiotic DNA replication initiation resulting in complete rereplication

I've now added one more:

id: FYPO:0004855
name: abnormal negative regulation of premeiotic DNA replication initiation resulting in partial rereplication

**Comment by mah11** [comment]
edit file: 60400ab363d2deef2a6a0f3c814fc2c7142c5d6b
release: ad1a93ec3a6e446c7aa0632a50e74379931a8778
