### ISSUE TITLE
abolished cell population growth at high temperature

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2311]
I have always done this with
abolished vegetative cell population growth
and temperature condition (I think?)

It only has 18 annotations....
should we obsolete to ensure consistent (I thought we had, but maybe we did this somewhere else?)

v

**Comment by mah11** [comment]
We've flagged "abolished vegetative cell population growth" as not for direct annotation, because we don't want anyone to use it when they should use "inviable vegetative cell population". That's why we've kept the "abolished vegetative cell population growth at high tempeature" term around (well, that and we think people will look for it).

That said, I've been doing ts mutants as "viable" at standard (or low) temp and inviable at high temp for quite a while. I hope that's OK because it would be a huge pain to find and change them all!

**Comment by mah11** [comment]
I'm going to close this, because I think we don't want to take abolished vegetative cell population growth out of the don't-annotate set.
