### ISSUE TITLE
query misplaced septum in stationary phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2316]
I thought this seemd odd ?
maybe because its a sibling of  equivalent vegetative term, but the cells are still growing vegetatively.

(I came across it because I wasn't sure why there were 2 terms
"misplaced septum" and "misplaced septum during vegetative growth" as I wasn't sure when else it would occur?

**Comment by mah11** [comment]
Everything referring to stationary phase in FYPO is a terrible hack. You're quite right that any individual cell that divides in stationary phase does so in a vegetative way, but  I've never been able to shake the suspicion that users would want to see the stationary phase stuff distinguished somehow, since it's not quite the same as cells growing rapidly in exponential phase. So I've kept all stationary phase FYPO terms split out from the vegetative-phase department, as a sort of least-worst, lesser-evil kind of thing. I don't have a pre-formed objection to changing that, tho I think we probably ought to discuss it a bit in a curator meeting (Antonia has requested and used a lot of the stationary phase terms).

**Comment by ValWood** [comment]
Ok, I see the rationale and I think this works for now...
I only spotted it because I was curious about the parent child term but I doubt this will bother our users!

v

**Comment by mah11** [comment]
OK, I'll sweep it back under the rug ;)
