### ISSUE TITLE
decreased mitochondrial membrane potential PMID:25483891 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2349]
decreased mitochondrial membrane potential PMID:25483891

**Comment by ValWood** [comment]
not to self, in presence of nigericin

**Comment by ValWood** [comment]
also
increased nigericin resistance

**Comment by ValWood** [comment]
increased resistance to valinomycin

**Comment by ValWood** [comment]
normal cardiolipin composition

**Comment by ValWood** [comment]
increased sensitivity to potassium ionophores
increased sensitivity to nigericin

**Comment by mah11** [comment]
New terms:
- abnormal mitochondrion FYPO:0004943
- decreased mitochondrial membrane potential FYPO:0004944
- resistance to nigericin FYPO:0004945
- sensitive to potassium ionophore FYPO:0004946
- normal mitochondrial membrane cardiolipin level FYPO:0004947

Notes:
- for "increased resistance to valinomycin" use FYPO:0000768
- for "increased sensitivity to nigericin" use FYPO:0000757
- Let me know if  FYPO:0004947 isn't what you meant by "normal cardiolipin composition"
- I've requested a CHEBI term for "potassium ionophore"
- I'll add "increased sensitivity" and "increased resistance" synonyms globally if you really, really need them, but not otherwise because it'll be extremely tedious.

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
