### ISSUE TITLE
checkpoint arrest term, help required

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2388]
I  have mutants which arrest in metaphase because the spindle checkpoint is active

as usual, I used
"increased activation of mitotic cell cycle spindle assembly checkpoint"
because the  checkpoint would not be active in these conditions in wt cell (although the activation would be normal for the mutant)

Then to confirm the arrest is checkpoint dependent they do double mutants with various checkpoint components to see if the  metaphase arrest is still present. As expected it isn't.
So, what would the phenotype be.
I want to say "abolished metaphase arrest" but  the WT cell would not be arrested.

This made me think that sometimes when we look at the phenotype of a double mutant we aren't really comparing the change  to the WT we are comparing  the change to  what happens in the single mutant.
So now I don't know how to record this......

**Comment by ValWood** [comment]
I can just go with
"abolished mitotic cell cycle spindle assembly checkpoint"

which is enough to figure it out if you compare the phenotypes of the  alp5 mutant with the alp5 bub1 mutant.

Of course you only see the  strong effects of abolishing the checkpoint in the double mutants with a mutant like alp5 which compromises some aspect of spindle kinetochore attachment .....

OK, I think I answered my own question, but input welcome.....

**Comment by Antonialock** [comment]
Ohh, yeah I've been wondering about the best way of doin this too. I may have just done phenotypic suppression? 'Abolished' seems reasonable though

**Comment by ValWood** [comment]
It would be  nice to be able to say :

alp5-yada mad1delta "decreased metaphase arrest" compared to alp5
but thats for another time.....and I think the above captures the info,  the user just needs to work a little harder to figure it out....

**Comment by mah11** [comment]
I only annotate phenotypes relative to wild type, and I have some notes stashed about being frustrated that I couldn't annotate a double mutant phenotype because the paper only showed single vs. double, not also wt.

In principle, we could adopt OMP's approach of using both "independent" and "dependent" phenotype annotations, where the latter are relative to some other independent annotation (we emailed about it a bit during the grant-prep madness). In practice, it would be an enormous job, requiring changes in Chado, Canto, display, querying, etc. etc.

**Comment by mah11** [comment]
... er, so can we close this?

**Comment by ValWood** [comment]
>  In practice, it would be an enormous job, requiring changes in Chado, Canto, display, querying, etc. etc.

Yeah future grant fodder
