### ISSUE TITLE
relationship between G2 arrest phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2436]
FYPO:0000839 - inviable elongated mononucleate aseptate cell
are the phenotypes used to infer
FYPO:0003373 - abnormal cell cycle arrest in mitotic G2 phase

how can these be related?

FYPO:0003373 - abnormal cell cycle arrest in mitotic G2 phase
has output?
FYPO:0000839 - inviable elongated mononucleate aseptate cell

or is it
FYPO:0000839 - inviable elongated mononucleate aseptate cell
has output?
FYPO:0003373 - abnormal cell cycle arrest in mitotic G2 phase

**Comment by ValWood** [comment]
actually if
FYPO:0004922	inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase

is a descendant of both
I could review  which ones can move down just to see that I didn't miss anything.
Then if
FYPO:0000839 or FYPO:0003373 ALWAYS =  FYPO:0004922
we can block the ancestors for direct annotation ....

**Comment by mah11** [comment]
Still thinking, but so far ...

FYPO:0000839 and FYPO:0003373 are not directly linked now, because 
- I wouldn't assume you can always tell that an inviable elongated mononucleate aseptate cell has arrested specifically in G2 phase, as opposed to S or even G1.
- I also didn't assume that arrest in G2 is always lethal, i.e. that no cell ever fixes the problem, recovers, etc.

**Comment by ValWood** [comment]
Yes, keep this on the back burner. It is an interphase block but people usually use to indicate a G2/M block. I don't know why now. I have a number of questions for Jacky about which phenotypes are really indicative of which stage arrest.

**Comment by mah11** [comment]
closing because it's ancient and hasn't had any updates in literally years
there are probably more recent tickets on similar topics
