### ISSUE TITLE
abnormal protein localization to mitoticspindle pole

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2449]
abnormal protein localization to mitotic spindle pole during anaphase

descendent of
increased duration of protein localization to mitotic spindle pole body

**Comment by ValWood** [comment]
PMID:15930132

**Comment by mah11** [comment]
erm, no, something looks wrong. Is the requested term name correct? If so, no need to specify ancestry; it'll be obvious. But right now it's not clear whether the term is really what you want, since the suggested parent doesn't make sense for it.

**Comment by ValWood** [comment]
oh yeah it only makes sense in the context of the protein I'm annotating...

and it should have been
abnormal protein localization to mitotic spindle pole body during anaphase

but basically its both things
a) abnormal protein localization to mitotic spindle pole during anaphase
and
b) increased duration of protein localization to mitotic spindle pole body

I don't want to make both annotations (I suspect we often make the checkpoint problem annotations to either of these terms)

I suggest instead 
ntr a) abnormal protein localization to mitotic spindle pole during anaphase
ntr b) abnormal checkpoint  protein localization to mitotic spindle pole during anaphase

b) can also be a descendant of
increased duration of checkpoint protein localization to mitotic spindle pole body 

because the checkpoint proteins should not be there at that point

does that work?

**Comment by mah11** [comment]
No. Increased duration is a subclass of abnormal, so it would be a TPV to put an "abnormal" term under an "increased duration" term.

I can add "increased duration of protein localization to mitotic spindle pole body during anaphase", with or without also including the intermediate term "abnormal protein localization to mitotic spindle pole during anaphase" ("increased duration of protein localization to mitotic spindle pole body" exists - FYPO:0001837).

I would greatly prefer not to include any "checkpoint protein localization" terms because I am not keen to try to define "checkpoint protein". I'll reconsider if you can get it defined in an ontology such as PRO.

**Comment by ValWood** [comment]
Hmm.
Mad3 and bub1 are such special cases I wonder if we could put them in the terms to represent the 2 branches of the spindle checkpoint:

increased duration of Mad3 checkpoint protein localization to mitotic spindle pole body
increased duration of Bub1 checkpoint protein localization to mitotic spindle pole body

Then I could check  all the annotation to:
increased location of protein to mitotic SPB (assayed using Mad3)
and
abnormal durationn of localization to spindle pole body (assayed using mad3)
and  a link could also  be made to 
"increased duration of checkpoint activation" for these

and possibly also " increased the Mad3/Bub1 foci"  terms ......

You don't like it do you :).....
I'm worried that the(my)  annotation are inconsistent.....currently the spindle checkpoiont activation stuff can end up in a few places

**Comment by mah11** [comment]
True, I don't even like the gene/gene product-specific terms that are in FYPO now ("transport gene level", "Rad22 foci", etc. etc.), so it would be vastly better to avoid adding more. It seems especially dodgy for protein localization terms where the specific protein can so easily be captured in an extension.

If Mad3 and Bub1 are really that special, you could try getting a GO protein localization term (or terms) added -- they'd probably reject the gene/protein names, but they might go for a "protein localization involved in X checkpoint" sort of thing.

**Comment by mah11** [comment]
I've added this so far, because it's totally uncontroversial:
increased duration of protein localization to mitotic spindle pole body during anaphase FYPO:0005096

If you want any terms specific to the spindle checkpoint, I recommend pursuing the "protein localization involved in mitotic spindle checkpoint" angle with GO.

**Comment by mah11** [comment]
edit file: 0ced6bfa9217652be586f19ff66c40f7058eacc9
release: 494d8d1501aa70b5aa96f73b38d012267f3e8bf5

**Comment by ValWood** [comment]
Its OK, all the examples I can find are annotated to "increased activation of spindle assembly checkpoint"

which is what the assay is used to indicate. Things will probably get annotated to one or the other but I won't worry about it for now.
