### ISSUE TITLE
possible  merge between FYPO:0000839 FYPO:0004923

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2463]
FYPO:0000839 inviable elongated mononucleate aseptate cell
Definition
A cell phenotype in which a cell contains one nucleus, has no septum, is elongated, and is inviable.

has a single child
FYPO:0004923 inviable elongated mononucleate aseptate vegetative cell with mitotic cell cycle arrest
A cell morphology phenotype in which a vegetative cell is inviable contains one nucleus, has no septum, is longer than normal, and progression through the mitotic cell cycle is arrested.

Are these equivalent?
(there are no siblings)

I guess FYPO:0000839 isn't defined vegetatively but I'm sure that is how it is used?

**Comment by mah11** [comment]
Well spotted - FYPO:0000839 is defined logically as vegetative but the text def doesn't reflect that. I'll fix it.

I have no idea if the two terms are interchangeable in practice for pombe, although from an ontology-geeky POV FYPO:0004923 is more specific than FYPO:0000839 because FYPO:0004923 adds the "mitotic cell cycle arrest" criterion.

**Comment by ValWood** [comment]
I don't think there is any difference for fission yeast. ....If the cell is inviable elongated it is cell cycle arrested.

**Comment by Antonialock** [comment]
I guess you could also get inviable elongated mononucleate aseptate lysed cells? 
Cell lysis isn't really arrest...?
But they would probably only be annotated to inviable elongated lysed cells
(I don't think I would think to specify aseptate for these, unless it's the other way around i.e. they are septate)

**Comment by ValWood** [comment]
true. We haven't seen an elongated lysing cell as far as I'm aware?

2 options. One is to merge. The other is to block the parent for direct annotation for pombe.

**Comment by mah11** [comment]
Of the two, I prefer the merge. I don't think it's all that likely that the generic cell phenotype ontology will extend to this level of detail even if it does get built, because it's just not, well, generic. And I think the do-not-annotate scheme is more suitable for terms that are so high-level that they're not informative. It's a bit silly to use do-not-annotate for a term as detailed as FYPO:0000839.

**Comment by Antonialock** [comment]
Ok, I'm not against that

**Comment by ValWood** [comment]
I agree. 

However, note that  for GO we often use "do not annotate" for terms where the annotation would be informative, but it should be possible to be more specific (1118 terms). I think the same should apply to FYPO terms, although not necessarily in this instance.

**Comment by mah11** [comment]
Yes, I know, and I dislike that use of the do-not-annotate flags in the ontology.

**Comment by ValWood** [comment]
Why? it improves the annotation...

**Comment by ValWood** [comment]
Actually I didn't even think of this as a "do not annotate flag" in the ontology. The GO ones aren't  *in GO*. Its just an internal soft check?

**Comment by mah11** [comment]
merge done

**Comment by mah11** [comment]
edit file: 02e53975e4138596f952e50fe8675346a0276112
release: bd7cb989ef38a30349babc1206d0fdb124313237
