### ISSUE TITLE
obsolete decreased production of siRNA involved in chromatin silencing by small RNA?

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2539]
I found this term:
decreased production of siRNA involved in chromatin silencing by small RNA

I don't think it has any annotations? 
It seems like the "type" of term name we use for this phenotype is:
decreased siRNA level 

obsolete the "decreased production of siRNA involved in chromatin silencing by small RNA" I realize it is not exactly the same as decreased siRNA level but it might be confusing to have it hang around seeing it hasn't even been used yet.

**Comment by mah11** [comment]
FYPO:0005052 does have one annotation, from PMID:26443059. It's one of those slightly awkward phenotypes inferred from other phenotypes - because the overall level of RNA transcribed from cen outer repeats is increased (FYPO:0000220), but the level specifically of outer repeat-derived siRNA is decreased (FYPO:0004201), the authors interpret the results as meaning that there's less of the siRNA-generating process taking place. I did just trust them on that ...

**Comment by Antonialock** [comment]
Ah fair enough.

I also only checked www for genes annotated to the term, but I now see it on stage,
