### ISSUE TITLE
Question about "abnormal cell cycle phase" term

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2542]
This ticket
https://github.com/pombase/curation/issues/761

made me look at the term, as I wasn't sure what it meant.

I think from the children it might mean "abnormal cell cycle phase transition"
Could you have a look and let me know if this would make sense?

The descendent phenotypes see to be all describing transition defects observed when you have a cell cycle block?

**Comment by mah11** [comment]
No, FYPO:0002735 is logically defined referring to GO:0022403 'cell cycle phase', and its text def includes "does not proceed normally through a specific cell cycle phase". Transition abnormalities are housed under 'delayed' or 'premature' phase transition, and their xps point to terms in the GO:0044770 branch. I could easily add an 'abnormal cell cycle phase transition' term to group them further.

Some phenotypes, e.g. FYPO:0000333 'mitotic G1/S transition delay', are classified as both phase abnormalities (G1 is longer than normal) and transition abnormalities (the G1/S transition is late).

If you prefer to define all cell cycle phenotypes in terms of the transition processes in GO, that will have to wait until I have a day or two clear for another major overhaul, but it should be doable. If you want to do that, I'll obsolete the terms that use the GO:0022403 branch rather than rename them.

**Comment by ValWood** [comment]
OK I understand this now.
I think the 'abnormal cell cycle phase transition' would be useful.

**Comment by mah11** [comment]
OK, I'll add the grouping term. Do you want to leave everything else as is?

**Comment by ValWood** [comment]
yes

**Comment by mah11** [comment]
grouping terms added:
  abnormal cell cycle phase transition FYPO:0005273
  abnormal meiotic cell cycle phase transition FYPO:0005274
  abnormal mitotic cell cycle phase transition FYPO:0005275

**Comment by mah11** [comment]
edit file: 6ed67908e769470d4cd5e32b2e31751cba8581c2
release: 177067ba0b96083275fece46904f9eb490e908ca
