### ISSUE TITLE
negative regulation of transcription by glucose

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2546]
We have the two terms
normal negative regulation of transcription by glucose
abnormal negative regulation of transcription by glucose

all the annotations to these terms are from assays where they measure the transcription (via a reporter like lacZ but sometimes only the RNA level) of a gene normally expressed during glucose starvation when cells are grown in glucose-rich medium. 

I don't think this term name "rings" right, can we make something else the primary name
e.g. normal/increased transcription/expression of glucose starvation gene during vegetative growth
?

**Comment by ValWood** [comment]
so
abnormal negative regulation of transcription by glucose
is 
glucose insensitive transcription?

perhaps
abnormal expression of glucose repressed gene?

**Comment by Antonialock** [comment]
Yes; abnormal negative regulation of transcription by glucose
is
glucose insensitive transcription

**Comment by ValWood** [comment]
maybe that could be primary name?

**Comment by Antonialock** [comment]
but it sounds horrible..

**Comment by mah11** [comment]
Negative regulation of transcription by glucose is a bona fide GO term (GO:0045014 and descendants). I would be willing to use the GO synonym "glucose repression" in the names of FYPO terms that describe effects on this transcriptional regulatory system. I do not want to change an existing effect-on-process term into a level-of-stuff term.

I'm also happy to add terms in the RNA level branch of FYPO for "normal/increased/decreased  level of glucose-repressed gene mRNA", and add annotations using them. I do think inferring an effect on the GO:0045014 process is safer than in most cases where RNA levels or reporter gene product activities are measured, because the phenomenon has been so thoroughly characterized for so long (over 50 years). Granted, just adding RNA level annotations won't capture all of the steps that support inferring an effect on transcription - since quite a bit of it is the body of knowledge accumulated based on lots of experiments in several species - but it could help.

**Comment by Antonialock** [comment]
Ok, lets stick with the negative regulation of transcription by glucose then.

**Comment by mah11** [comment]
OK. I'll also add the RNA level terms - it won't be bad to have annotations to both.

note to self: add some synonyms to existing terms, including "glucose-insensitive transcription"

**Comment by mah11** [comment]
decreased level of glucose-repressed gene mRNA during vegetative growth FYPO:0005278
  increased level of glucose-repressed gene mRNA during vegetative growth FYPO:0005279
  normal level of glucose-repressed gene mRNA during vegetative growth FYPO:0005280

**Comment by mah11** [comment]
edit file: 6ed67908e769470d4cd5e32b2e31751cba8581c2
release: 177067ba0b96083275fece46904f9eb490e908ca
