### ISSUE TITLE
normal mitotic cohesion

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2571]
normal establishment of mitotic  cohesion
normal maintenance of mitotic cphesion
PMID:12242294

**Comment by mah11** [comment]
normal establishment of mitotic sister chromatid cohesion FYPO:0005312
  normal maintenance of mitotic sister chromatid cohesion FYPO:0005313

**Comment by mah11** [comment]
edit file: deaef0426ccef63b4fdb8e7b0497838810101852
release: b0b60d0941f0bc92c4971f6a2dad85df58ea1031

**Comment by ValWood** [comment]
used these terms but did not see them as 

normal mitotic sister chromatid cohesion

**Comment by mah11** [comment]
They're siblings because if one but not the other is normal, then you don't have normal cohesion overall (e.g. if cohesion is set up normally but then falls apart - abnormal maintenance - it's not all well).

The relations that we haven't included for Canto-suggestion reasons are normal cohesion has_part normal establishment and normal cohesion has_part normal maintenance.

**Comment by ValWood** [comment]
OK
