### ISSUE TITLE
diff between FYPO:0000392 and FYPO:0000620

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2580]
FYPO:0000392 - abnormal cell cycle arrest at mitotic metaphase/anaphase transition

and

FYPO:0000620 - abnormal cell cycle arrest in mitotic metaphase

appear to be used for the same phenotype (arrest at the transition with condensed unseparated chromosomes and  abnormally elongated spindle)

I wonder if we should merge them?

I think you can only arrest just before the transition? but  
FYPO:0000620 - abnormal cell cycle arrest in mitotic metaphase might be a better primary term name

**Comment by mah11** [comment]
They are not defined identically. FYPO:0000620 describes arrest in any part of metaphase, and points to GO:0000089, whereas FYPO:0000392 is specific for the metaphase/anaphase transition and points to GO:0007091.

If you are *absolutely certain* that fission yeast cells never arrest in metaphase other than at the metaphase/anaphase transition, then there's probably a case for making FYPO:0000620 obsolete. Even if we do, though, I don't think it's a good idea to rename FYPO:0000392 because its current name is consistent with the xp'd GO term and with its defined specificity.

**Comment by ValWood** [comment]
I'm not certain. I'm not sure how you would make the distinction though between 

any part of metaphase, and the  metaphase/anaphase transition.

I also thought that 'arrest' had to happen at a transition point ?

**Comment by ValWood** [comment]
I.e isn't all arrest dependent on some checkpoint?

**Comment by mah11** [comment]
Hmm, perhaps it's FYPO:0000392 that should go obsolete - if you arrest in metaphase you *don't* undergo the transition. Is it even possible to start the transition but not finish it? (If so, there's your distinction, tho.)

As for the bigger-picture questions about arrest, I'm not sure. Maybe all abnormal arrest is due to not meeting checkpoint criteria, but defining the arrest phenotypes that way feels circular - people use arrest phenotypes to characterize checkpoints. And normal arrests are a whole other thing ...

**Comment by ValWood** [comment]
No, the transition is an all or nothing event. Its activation of the APC in this case.  Its essentially a 'switch' occuring, and enforces directionality.

I just have a feeling that arrest  (normal or abnormal) can only occur when some criteria are not satisfied, and this can only happen at a transition point.

**Comment by ValWood** [comment]
>Hmm, perhaps it's FYPO:0000392 that should go obsolete - if you arrest in metaphase you don't undergo the transition. Is it even possible to start the transition but not finish it?

I think that would work.
Definitely you don't undergo the transition.  If you arrest at the transition, you arrest in metaphase. the transition is just a point in between metaphase and anaphase.

**Comment by mah11** [comment]
> No, the transition is an all or nothing event.

That rather suggests you can't arrest in the middle of it, so it's FYPO:0000392 that makes no sense.

> I just have a feeling that arrest (normal or abnormal) can only occur when some criteria are not satisfied, and this can only happen at a transition point.

What about S phase arrest and the intra-S DNA damage checkpoint? (And I haven't looked into the vertebrate oocyte prophase I arrest, but I've never heard of a "prophase/metaphase transition".)

**Comment by ValWood** [comment]
Oh I just found this. 
I think this is also equivalent?
 FYPO:0000324 - mitotic metaphase/anaphase transition delay

**Comment by mah11** [comment]
I think arrest a la FYPO:0000620 could go on to do the transition late as in FYPO:0000324, or not reach the transition at all.

**Comment by ValWood** [comment]
Yep I immediately deleted that comment!

**Comment by ValWood** [comment]
agreed.
That rather suggests you can't arrest in the middle of it, so it's FYPO:0000392 that makes no sense.

When I asked for this I was thinking prior to, not in the middle of but  everything should move to:
FYPO:0000620 - abnormal cell cycle arrest in mitotic metaphase

**Comment by mah11** [comment]
OK! watch this space ...

**Comment by ValWood** [comment]
I yes I forgot about intra-S! so there are exceptions, but I think we have resolved the metaphase anaphase one

**Comment by mah11** [comment]
FYPO:0000392 is now obsolete

**Comment by mah11** [comment]
edit file: 138d806d362c771009d917f669073b54cb4452af
release: 0c9f107ee56df966ee46641cac1897aa7fa31157

**Comment by ValWood** [comment]
Just for the record. My comment about only blocking before the transition was rubbish. However the solution to only have the  block describe "metaphase arrest" is good. To be more specific, we would need terms like the one Antonia added (metaphase arrest with abnormal spindle), but we should be more specific about what is abnormal for the phase (i.e metaphase arrest with elongated spindle)
