### ISSUE TITLE
antisense RNA

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2604]
4 genes are annotated to FYPO:0002913 increased antisense RNA transcription from two papers
(atf1 is annotated to the child increased antisense RNA transcription at stress response genes)

I had a quick look at the papers and it looks like it they should be annotated to
"increased antisense RNA level" 

so FYPO:0002913 can be merged into FYPO:0003557?
and the term used for atf1 be renamed?

PMID:25122751 and PMID:24100010

**Comment by mah11** [comment]
No, we keep transcription and RNA level terms separate because they don't actually mean the same thing: a difference in RNA level may be due to changes in transcription or degradation. It's also possible to do assays that look specifically at transcription, although they're not done nearly as often as simply measuring RNA levels.

I can recast FYPO:0003908 as an RNA level term, because it has never had a logical definition and has only been used for that one atf1 annotation. But I won't merge the more general terms.

**Comment by mah11** [comment]
FYPO:0003908 now rejigged.

**Comment by Antonialock** [comment]
Yes I know they don't mean the same thing, I thought that in these papers the authors were measuring RNA level, not transcription. I guess I meant 'renaming' rather than 'merging'. Whatever works :-)

**Comment by mah11** [comment]
edit file: 36a0132ad81c1ca6c58d5359cde67b290188929d
release: 26871d42eabe9730906d4a2e850f973d24f88ad8
