### ISSUE TITLE
query descendants of "elongated vegetative cell"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2609]
This is all I see? Is that correct?

![elongated_vege_cell](https://cloud.githubusercontent.com/assets/7359272/14215116/dd99875c-f838-11e5-8fd6-1f1ddd9ae332.jpg)

**Comment by ValWood** [comment]
(I don't see the viable or inviable options)

**Comment by mah11** [comment]
looks like Canto failing to use the has_part links (so not an ontology issue)

**Comment by ValWood** [comment]
Hmm, I keep forgetting. Did we remove has_part from canto because it didn't always make sense? (i forget).

also, remind me why
"elongated viable vegetative cell" isn't 
is_a  elongated vegetative cell

**Comment by mah11** [comment]
Canto should follow has_part links, and it has been working fairly recent past (as evidenced by the time without this sort of ticket ;) ). Makes me wonder if the current problem is connected with all the rest ...

We removed has_part from the ontology in the "normal phenotype" branch as a hack to ensure that the "normal" term suggestions made sense.

I'm using has_part instead of is_a because that's a better fit for defining FYPO terms as phenotypes (as opposed to defining "cells with these phenotypes", despite having "cell" in a lot of the names), and the whole thing behaves better upon reasoning this way.

**Comment by ValWood** [comment]
OK, will open Canto ticket....
