### ISSUE TITLE
cut parentage

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2615]
shouldn't cut de a descendent of
inviable vegetative cell with cell death during mitosis?

**Comment by mah11** [comment]
When we crafted cut and its parent and sibling, we didn't say anything about when the cells die relative to when the nucleus divides. I still don't know enough to make that call.

**Comment by ValWood** [comment]
Definitely stuck in mitosis (hasn't completed anaphase correctly), despite cytokinesis also occurring (checkpoint is over-ridden)

**Comment by mah11** [comment]
Just cut itself? Or does the FYPO:0003166 phenotype also count as "stuck in mitosis" even though two nuclei form?

**Comment by ValWood** [comment]
I was thinking about this recently. If a cell is a mutant and has characteristics of different phases how do we establish which phase it is in. I would say, that if it hasn't managed to separate its chromosomes it is stuck in metaphase, even if cytokinesis has subsequently occurred.
But...I will check that! 

I want to @-jacky but she isn't in this list?
https://github.com/orgs/pombase/people

**Comment by mah11** [comment]
> If a cell is a mutant and has characteristics of different phases how do we establish which phase it is in.

This is a lot of the reason I haven't tried to build a phase-of-death link in for cut and various other terms.

**Comment by Antonialock** [comment]
I guess the phases are not necessarily mutually exclusive. They are in wild-type, because things "should" happen in a sequenced and orderly fashion, but mutants are mutants, so sometimes they might try and do Y even though X hasn't completed etc. 

Add to that that it isn't always clear from the experiment exactly what phase a cell is in (at least not to me). I guess it's like the saying "all models are wrong, some are useful" & similarly the break down of the cell cycle into discrete steps is a bit arbitrary but it can be a useful descriptor.

**Comment by ValWood** [comment]
This phenotype is called "cytokinesis in the absence of nuclear division". My gut feeling would be that these cells are 'stuck in mitosis' even though cytokinesis has taken place.

**Comment by mah11** [comment]
I"m kinda leery of defining any ontology terms based on anyone's gut feelings .. even yours ;)
