### ISSUE TITLE
PMID:11102508 normal spindle pole body duplication

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2637]
PMID:11102508

A physical cellular phenotype yada yada

child of
normal mitotic spindle pole body?

**Comment by mah11** [comment]
> child of
> normal mitotic spindle pole body?

Not by is_a, because normal SPB is a structure phenotype, and the new term will be a process phenotype. Maybe has_output, but I'd be more comfortable doing that with a "normal spindle pole body organization" term, because all aspects of organization -- not just duplication-- have to be normal to get normals SPBs.

**Comment by ValWood** [comment]
OK, my suggestion didn't seem right.

**Comment by mah11** [comment]
normal spindle pole body organization FYPO:0005378
  normal spindle pole body FYPO:0005379
  normal mitotic spindle pole body duplication FYPO:0005380

**Comment by mah11** [comment]
edit file: 5f36967d7cb5b61e4a6211eb22979c7f1be12d30
release: b8e8e14d27cdadda3688d067256838564a118a90
