### ISSUE TITLE
is penetrance valid for FYPO:0000303?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2651]
currently not available, but seems appropriate ( I have a genotype with 0.44% mating frequency)
FYPO:0000303	decreased conjugation frequency

**Comment by mah11** [comment]
No, penetrance is not valid for any population phenotype. Penetrance says how many of the individuals in a population have the phenotype, so for us it's relevant to cell phenotypes. It wouldn't make sense to say 10% of a population has the phenotype "decreased proportion of the population conjugates".

I'll improve the def wording.

**Comment by ValWood** [comment]
I guess I could  do sterile with a percentage.....?

**Comment by mah11** [comment]
yeah, that should work

**Comment by ValWood** [comment]
I can't add penetrance for sterile...only expressivity...

**Comment by mah11** [comment]
Ah, I see the problem - it's because we moved abnormal conjugation out from under cell phenotype when we decided to treat increased & decreased conjugation frequency as population phenotypes. I'll add sterile itself to the config so you can add penetrance after Canto reloads the configs (tomorrow, if I understand correctly).

**Comment by ValWood** [comment]
I think that  will work.

**Comment by mah11** [comment]
will close, because config edit is done.
