### ISSUE TITLE
are these terms related? should they be ?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2653]
FYPO:0001974	increased number of cells with 1C DNA content	
FYPO:0001430	abnormal mitotic cell cycle arrest with unreplicated DNA

I think I could use either...

**Comment by mah11** [comment]
I'll add the link FYPO:0001430 has_output FYPO:0001974

Rationale: If cells arrest in G1, the proportion of the population with 1C DNA content will go up. But you'd also get more cells with 1C DNA if progress through G1 slows rather than stops, so all-out arrest isn't the only way to get more 1C (and the terms thus aren't identical).

**Comment by mah11** [comment]
done in 
edit file: 6661305a803ccbc7889ba3e7d176839bc56a0dd0
release: ec9073a2c1a23a15d859cbed4d611d4e06281726
