### ISSUE TITLE
ntr: normal protein level during G1 phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2658]
I forgot this one...
PMID:9398669

note to self....I'm putting the session through with this as a comment

**Comment by ValWood** [comment]
actually it is't just during G1, its in G1 arrest (nitrogen starved)

**Comment by mah11** [comment]
normal protein level during cell cycle arrest in mitotic G1 phase in response to nitrogen starvation FYPO:0005409

Note: Right now the new term is only under 'normal protein level during nitrogen starvation' FYPO:0004084, i.e. it's not under '... during vegetative growth' like the other 'during mitotic cell cycle phase' protein level terms. This is because nitrogen starvation stuff generally isn't under vegetative growth.

**Comment by mah11** [comment]
edit file: c8a3c80b1ab0ad92eff599604216ff22314cb836
release: bc216a53995af2ca206b7dc3a28293bf8f3b978b
