### ISSUE TITLE
ntr: elongated

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2670]
inviable elongated cell arrested in mitotic interphase in response to UV
descendent of 
FYPO:0004197

and
inviable elongated cell with fragmented nucleus arrested in mitotic interphase in response to UV
descendent of 
FYPO:0005303
FYPO:0004197

PMID:11861765

note to self, most of these are likely interphase arrested:
FYPO:0005303	elongated vegetative cell during cellular response to UV

**Comment by mah11** [comment]
inviable elongated vegetative cell with mitotic cell cycle arrest in interphase during cellular response to UV FYPO:0005421
  inviable elongated vegetative cell with fragmented nucleus and mitotic cell cycle arrest in interphase during cellular response to UV FYPO:0005422

note: FYPO:0005421 is not under FYPO:0004197 because FYPO:0005421 does not specify a fragmented nucleus

**Comment by mah11** [comment]
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a
