### ISSUE TITLE
cytokinesis phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2707]
Follow on from

I'm fairly convinced now that
inviable elongated multinucleate aseptate vegetative cell
is an output of "abolished cytokinesis"

but hinges
https://github.com/pombase/curation/issues/959

How can these terms be related in FYPO?

abolished cytokinesis  sometimes has output FYPO:0002024
Should this also be a type of  cell cycle arrest?

The paper I am reading PMID:8978670
"arrested at cytokinesisas binucleate or tetranucleate cells with improperly deposited septum material in the medial region of the cell (Balasubramanian et al., 1994). "
fits all of the other mutants

**Comment by ValWood** [comment]
I think I have also used this for the same phenotype
inviable elongated multinucleate vegetative cell with abnormal septum morphology


This has been used for rng2 and cdc3.

I wonder if the terms should merge and a comment added to 
inviable elongated multinucleate aseptate vegetative cell
saying 
"improperly deposited septum material is sometimes visible as a broad band in the middle of the cell"
?

Would that work?

I wonder if this is correct. The septum doesn't really form at all (because there is no actomyosin ring?).
The septum material is deposited in a broad band in the middle of the cell.

**Comment by mah11** [comment]
> abolished cytokinesis sometimes has output FYPO:0002024

If it's "sometimes" we can't put FYPO:0000417 (abolished cytokinesis) has_output FYPO:0002024. But if there's no other way to get the FYPO:0002024 phenotype, we can say FYPO:0002024 output_of FYPO:000417.

> Should this also be a type of cell cycle arrest?

If it gets connected to cell cycle arrest at all, it'll have to be by something other than is_a (so no, not a type of). I'm also not sure the cell cycle necessarily arrests -- if cytokinesis stops, but the nuclear cycle gets decoupled and carries on, is that really "arrest", or a different sort of abnormal?

> I wonder if the terms should merge ...

I will not merge FYPO:0002024 and FYPO:0002025 because the former means there's no septum (under circumstances where you would be able to detect a septum if there was on), whereas the latter means there is a septum but something's wrong with it. The rng2-346 mutant has a septum that looks nearly complete, much more cohesive than I would call "a broad band in the middle of the cell"; it's just got a wonky shape (the cdc3-313 cell looks like more of a grey area, and I wouldn't object to saying that's not a septum).

http://jcs.biologists.org/content/joces/109/1/131.full.pdf fig 5 a & f
the septum in f is nowhere near as broad as the one in cdc3-124 from PMID:8978670

**Comment by ValWood** [comment]
>But if there's no other way to get the FYPO:0002024 phenotype, we can say FYPO:0002024 output_of FYPO:000417.

There isn't, I'm sure so I think that sounds OK.
Ignore the rest...

**Comment by mah11** [comment]
ok, link added

edit file: 87bbd5a48383ecf64dfdfde1fc48c7f8b8c05389
release: a1a90675d29890871922540ab49849611cfd8bc0
