### ISSUE TITLE
penetrance for increased septation index and thickness?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2708]
Would this make sense?

**Comment by ValWood** [comment]
also for 
increased septum thickness

**Comment by ValWood** [comment]
ignore for thickness, its there...

**Comment by mah11** [comment]
The septation index terms are population terms, so they cannot have penetrance extensions (penetrance only makes sense for cell phenotypes, because penetrance is what proportion of organisms in a population have the organism-level phenotype).

We can use expressivity extensions on population phenotypes, and I have used that to capture more vs. less of a population showing a phenotype that can only be observed at the population level.

**Comment by ValWood** [comment]
OK, I thought there was something.....
