### ISSUE TITLE
abnormal monopolar protein localization to one cell end PMID:26749213

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2726]
Abnormal  localization of a protein which normally localizes to both cell ends to a single cell end.
(I'm sure you will do a better job but thats what I mean!)

PMID:26749213

Henar has made an annotation to  "abnormal cell polarity" and I think thats a suitable parent with the abnormal protein localization parentage.

**Comment by mah11** [comment]
I have named it

abnormally monopolar protein localization to cell tip FYPO:0005503

I'm a little bit worried about linking it to cell polarity -- we've defined the normal/abnormal cell polarity terms (by xp and text) as the processes that establish and/or maintain polarity being normal or abnormal. Localization of a protein to end(s) could be a symptom rather than a cause of wonky polarity processes, and if it is just a symptom, the link is a bit dodgy. For now I've included an is_a link as requested, in case I'm overthinking this. It could change to output_of if the protein localization is an effect rather than a cause (of course, in real life it could be either, depending on which protein .. argh).

**Comment by ValWood** [comment]
I agree about the link to cell polarity. It didn't seem that it would always be true.
I don't even see the "abnormal cell polarity now" its
FYPO:0001584	abnormal protein localization to cell tip
but I wonder if I changed it afterwards?

**Comment by mah11** [comment]
I'm happy to leave that link out

**Comment by ValWood** [comment]
yep, do...

**Comment by mah11** [comment]
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738
