### ISSUE TITLE
regulation of replication intitiation

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2733]
ID  FYPO:0001248
Ontology    fission_yeast_phenotype
Term name   abnormal regulation of mitotic DNA replication initiation 

does not show when looking at
ID  FYPO:0001344
Ontology    fission_yeast_phenotype
Term name   abnormal mitotic DNA replication initiation 

(shouldn't it?)

**Comment by mah11** [comment]
It makes ontological sense that these aren't connected, because the reasoner only follows is_a links in external ontologies including GO to infer FYPO structure. In GO, of course, connections between 'process' and 'regulation of process' use regulates, not is_a, so the reasoner doesn't do anything with them.

In general I haven't manually asserted any is_a links between phenotype-affecting-process and phenotype-affecting-regulation-of-process terms. To do so seems like it would kind of imply that regulation is intrinsic to a process (in reality, sometimes it is, sometimes it isn't). It would be internally consistent to handle everything the same way, and less work to keep them unconnected as they are now ;)

**Comment by mah11** [comment]
going to leave things unchanged for now
