### ISSUE TITLE
NTR: precocious sister chromatid segregation at meiosis I  PMID:26483559

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2735]
synonym:equational segregation.

Def: Sister chromatid segregation at meiosis I

![precocious s-c sep](https://cloud.githubusercontent.com/assets/7359272/16739260/205adcce-4791-11e6-83cc-8451a89b071c.jpg)

**Comment by ValWood** [comment]
found it
FYPO:0003604	sister chromatid separation during meiosis I

I could not see it under here? 
abnormal meiotic chromosome segregation
None of the immediate descendants seem to be appropriate ancestors?

**Comment by ValWood** [comment]
I think there should be a relationship between FYPO:0003604 and 
FYPO:0000209	abnormal attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation

(this is the term the CC used here...)

I guess its:

FYPO:0000209 has_output  FYPO:0003604, but maybe to make the link we need to specify how the attachment is abnormal?
(i.e bipolar attachment in meiosis I)

**Comment by ValWood** [comment]
Hmm, not always, may occur...

In contrast, if bipolar spindle attachment of sister chromatids is established, precocious sister chromatid segregation (i.e., equational segregation) may occur.

(difficult to imagine how it would not occur uncorrected though?)

**Comment by ValWood** [comment]
yeah I think its OK to do....

"Nevertheless, the frequency of equational segregation in mei- osis I increased to 7% in the nup132Δmad2Δ double mutant. This result suggests that erroneous microtubule-kinetochore attachments occurred in the nup132Δ mutant but that the er- roneous attachments can be corrected in the presence of SAC."

.....so if the errors persist,  the outcome would be equational segregation  at meiosis I

**Comment by ValWood** [comment]
There are also other ways to get this phenotype...

In addition to SAC, sister centromere coherence prevents equational segregation of the sister chromatids in meiosis I. We therefore examined the segregation pattern of sister cen2-GFP in the sgo1Δ background, in which sister centromere cohesion is compromised (Kitajima et al., 2004).


So the abnormal attachment process could be an has_output of both  phenotypes? (still not got this in my head totally for Canto inheritance and display...)

**Comment by mah11** [comment]
Now that we have 'abnormal meiotic sister chromatid segregation' (FYPO:0005509) from #2730, I've added the link FYPO:0003604 is_a FYPO:000509.

I'm a bit confused about what else to do. We have had the link FYPO:0003604 output_of FYPO:0002093 (decreased meiotic sister chromatid cohesion), but that implies that decreased cohesion is the only way to get sister chromatid separation in meiosis I. Now it seems like that's not the case - the early separation could be due to decreased cohesion OR biorientation in meiosis I? If that's true, then output_of won't work. I'll remove that link for now.

If these are "if x happens, y may happen" (not "y definitely will happen"), then has_output won't hold. We may have to use comments, and hope people (a) read them and (b) select the right set of terms for their actual results.

**Comment by mah11** [comment]
changes so far in
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738

**Comment by ValWood** [comment]
OK I re read this  quickly. Maybe its all OK? If I can't find the appropriate terms next time I'm looking I'll suggest comments?
close?

**Comment by mah11** [comment]
OK, I've added some comments now.
