### ISSUE TITLE
change primary term names for 2 terms with during?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2754]
FYPO:0002087	exocytic vesicles present in increased numbers at cell tip during cell growth
to
exocytic vesicles present in increased numbers at cell tip during mitotic interphase

and
FYPO:0002088	exocytic vesicles present in increased numbers at barrier septum during septation
to
exocytic vesicles present in increased numbers at cell tip during mitotic telophase

(they have one annotation each, and this seems fine for this paper
PMID: 22891673)

I  used them for curs/4f2995b7c74f1360 but it now seems better to use phases with 'during' if possible, for consistency? Otherwise we could end up describing  things as during process and during phase when we mean the same thing?

**Comment by mah11** [comment]
I'm not sure this is a great idea, especially for the second term. Although in pombe cell growth normally only takes place in interphase, and septation normally coincides with telophase, they are not really the same.

Mitosis only directly involves the nucleus, and it's only part of the bigger cell division process. There's nothing inherent in cytokinesis that has to take place during, rather than after completion of, telophase (and in many eukaryotes there are circumstances where cytokinesis doesn't happen).

It's much more important for terms to be consistent with the observations they're meant to represent than with the wordings of other terms.

I would prefer to add synonyms than change the names, because the current names reflect the observations more closely (again, especially for the septation/telophase one). For the phenotypes here, they don't even necessarily look at the nuclei or do anything else to directly assay the state of the nucleus, i.e. they don't directly show the cell cycle phase or stage of mitosis.

**Comment by ValWood** [comment]
the paper I was working on referred to 
exocytic vesicles present in increased numbers at cell tip during mitotic interphase
so presumably these are used interchangeably. Are you happy with this one.

In general, I always try to make my during  refer to phases, unless they are par of the process,  but I'm happy to use the septation term for the second one (as it is almost certainly 'involved in').

**Comment by mah11** [comment]
> the paper I was working on referred to
> exocytic vesicles present in increased numbers at cell tip during mitotic interphase
> so presumably these are used interchangeably. Are you happy with this one.

Well, "happy" is probably too strong a word, but I'm willing to make this change because it won't make the term name diverge from the actual experimental observation as much as in the other case.

**Comment by mah11** [comment]
done in
edit file: f60ef64b041e47900fcd4c23fc8df2509c03bb7a
release: 256754d4c284572089d920f8ed9bdab8139dce99
