### ISSUE TITLE
sister chromatid separation during meiosis I PMID:21920317

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2789]
sister chromatid separation during meiosis I, with  lagging chromosomes, followed by normal chromosome segregation

descendent of
FYPO:0005633	sister chromatid separation during meiosis I followed by normal chromosome separation

(needed because they have different penetrance)

**Comment by ValWood** [comment]
is there a relationship between

FYPO:0002219
"A cellular process phenotype in which homologous chromosome segregation, or disjunction, is normal (i.e. indistinguishable from wild type)." 

and
FYPO:0005633 sister chromatid separation during meiosis I followed by normal chromosome separation

**Comment by mah11** [comment]
No, because to meet the FYPO:0002219 criteria everything about meiosis I segregation has to be normal, and that's not the case if sister chromatids separate (even if the chromosomes do manage to end up in the right place afterwards).

If I were to add a term for "normal chromosome separation during meiosis I", in principle both FYPO:0002219 and FYPO:0005633 could have has_part FYPO:new, but using has_part in the "normal" branch leads to undesirable Canto suggestions.

**Comment by ValWood** [comment]
OK

**Comment by mah11** [comment]
sister chromatid separation during meiosis I, with lagging chromosomes, followed by normal chromosome separation FYPO:0005641

**Comment by mah11** [comment]
edit file: 502037384246b921861b98a5686db1aa00aaf950
release: c136177d2f6ece14a68bf41de8de6b74323072c6
