### ISSUE TITLE
new terms for telomerase associated paper

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2795]
increased duration of protein localization to telomere
decreased  protein:RNA binding  used 	decreased protein binding for now

(I'd quite like to get ter1 consistently  the extensions (or telomerase_RNA).  For the other phenotype acting on telomerase RNA I had to use telomerase_RNA)

**Comment by mah11** [comment]
> I'd quite like to get ter1 consistently the extensions (or telomerase_RNA). 

Is there a word missing here? It doesn't quite make sense as written, so I can't figure out what you're trying to do.

**Comment by mah11** [comment]
> decreased protein:RNA binding

This is, unfortunately, less straightforward than it looks. (I had a community session recently where I thought about adding an RNA-protein binding term, but I decided it wasn't worth the faff for one or two annotations from one paper). The terms themselves look innocuous, but the implications for ancestry and extension configuration are hairy.

- We have to decide whether the existing RNA binding terms are actually RNA-protein interaction terms, or if they also encompass RNA-RNA interactions. (This is probably the most awkward thing.) The way they're defined now ("occurrence of RNA binding by a gene product is normal|abnormal|etc. ...") isn't very explicit, but implicitly allows both RNA-RNA and protein-RNA, since a gene product can be RNA or protein.

- For RNA-protein interaction/binding terms, the extension configuration will have to demand one protein ID (gene ID as proxy) and one RNA ID, and the RNA will have to allow a specific RNA ID (i.e. gene ID as proxy), or a transcript type SO ID. So it'll need the radio buttons and SO autocomplete box. We probably also ought to check with Kim about how to do the cardinality - two lines, each with cardinality 1 might work, but I'd like to confirm that.

- Extension configuration considerations also mean that life will be very difficult if we try to make RNA-protein binding terms is_a protein binding or is_a RNA binding (let alone both). Shout if you want me to walk you through why ...

- A smaller thing, but I wonder if it would be easier to interpret the term if we use "interaction" rather than "binding" in the name, i.e. 'decreased protein-RNA interaction". I would then also be tempted to rename the "protein binding" terms to use "protein-protein interaction", for consistency.

Is it worth the above effort?

**Comment by ValWood** [comment]
> I'd quite like to get ter1 consistently the extensions (or telomerase_RNA).
>> Is there a word missing here? It doesn't quite make sense as written, so I can't figure out what you're trying to do.

There might be a couple of words missing.

For one extension I had to use telomerase_RNA the SO term, for the other I had to use ter1 (the gene product)

**Comment by ValWood** [comment]
Yeah I was inclined to leave it as "decreased protein binding" if you look at the IDs its clear enough what is reduced.

I quite like the idea of calling it reduced interaction instead though.....

**Comment by mah11** [comment]
> For one extension I had to use telomerase_RNA the SO term, for the other I had to use ter1 (the gene product)

If you have notes about which terms offered which options, we can investigate whether the extension configuration could 'n should be adjusted.

**Comment by mah11** [comment]
> I quite like the idea of calling it reduced interaction instead though

I could do that for existing terms, as a non-urgent thing for after the looming update.

**Comment by ValWood** [comment]
FYPO:0002134	decreased RNA binding	Chromatin immunoprecipitation experiment			Fig 7 B	assayed_using telomerase_RNA

would like to put ter1 becuse thats what I put in the other one (Although now, it is obvious why, this is the protein binding term, which allows any gene label)
decreased protein binding	Co-immunoprecipitation experiment		
this is decreased protein:RNA binding
fig 7 c	assayed_using ter1 , assayed_using ssb1


Anyway if this is in any way tricky, ignore as it isn't important......

**Comment by ValWood** [comment]
> I could do that for existing terms, as a non-urgent thing for after the looming update.

yep non urgent....

**Comment by mah11** [comment]
added the straightforward term:
increased duration of protein localization to telomere FYPO:0005649

You could make the extensions consistent by using ter1 with both - FYPO RNA binding terms allow either SO or gene IDs.

I've opened #2799 for the "protein-protein interaction" name change.

new term in
edit file: f14c0eac4a5a646b2d3a74ed10281625439e35db
release: 2e411809995df8079922d7b3d846b7b3324bc081
