### ISSUE TITLE
question about FYPO:0000658

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#280]
FYPO:0000658 is defined as A molecular function phenotype in which occurrence of DNA binding by a mutated gene product is decreased.

I have a case where a point mutation in geneX leads to decreased binding to DNA by geneY
I am guessing that this falls out of the scope of the term in question? 

E.g. it is intended to only be used when a mutation in geneX leads to decreased binding of geneX to DNA 

Ergo; if you would use assayed\_using\(geneY\) with this term, it would mean that you get decreased binding of geneX to the DNA sequence/promoter region/whatever of geneY NOT that you get decreased binding of geneY to DNA

Original comment by: Antonialock

**Comment by mah11** [comment]
I'm gonna close this, because I think the problem it describes can be solved by using the new "assayed_enzyme" and "assayed_substrate" extension relations. A DNA-binding protein isn't exactly an "enzyme" but we can have a think about whether that relation needs a new, broader name and carry on using it in the meantime.
