### ISSUE TITLE
heterothallic mating PMID:11260263

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2808]
is this the correct term to use?

FYPO:0002520	decreased frequency of conjugation with h+ cells

@Antonialock

**Comment by mah11** [comment]
If the heterothallic strain they tested is h-, then yes, you can use FYPO:0002520; if it was h+, FYPO:0002521. Or you could just use the parent, FYPO:0000303, and include h- (or h+) in the genotype background. The backgound would be a good idea anyway, because the mating phenotype is different in the homothallic (h90) strain - you could also annotate a normal mating phenotype for the h90 strain.

**Comment by Antonialock** [comment]
I wouldn't use that term here.

So what they see is that h90 cells mate efficiently among eachother, however if they grow h+ cells together with h- cells they hardly mate at all (and h+ or h- cells have reduced mating with h90).

In the discussion they say
"we suspect that the differences in mating efficiency between homothallic and heterothallic myo1D cells may reflect their inefficiency to extend conjugation tubes over a distance"
(= h90 cells efficienttly mate because cells of different mating types will be spatially close to each other, whereas it is less likely that h+ specific and h- specific cells find themselves right on top of each other).

It is a bit of a weird one, I would probably just annotate this to descreased mating efficiency (I don't think it would be wrong to make the annotation "decreased mating efficiency with h+ or h-cell, and specify backgrounds etc but I think that knowledge might not be worth it since the explanation is so simple...it would be more valuable if they show a micrograph of short conjugation tubes or whatever)

**Comment by ValWood** [comment]
ok agreed....
