### ISSUE TITLE
How to represent expression of an exogenous  viral protein

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2812]
When Vpr was expressed in the cdc2-3w strain, the cdc phenotype was clearly observed and cell proliferation was inhibited (Fig. 2A and B). 

How can I capture the endogenous  viral protein expression. Can this be done as a condition?

**Comment by mah11** [comment]
what's the paper?

**Comment by ValWood** [comment]
PMID:10684278
(I usually ignore exogenous protein expression EXP's but its pretty important here and its a really strong phenotype that is different for the 2 alleles)

"Genetic Studies with the Fission Yeast Schizosaccharomyces
pombe Suggest Involvement of Wee1, Ppa2, and Rad24
in Induction of Cell Cycle Arrest by Human
Immunodeficiency Virus Type 1 Vpr"

**Comment by mah11** [comment]
I'm not stupendously keen on shoehorning this into conditions - it doesn't fit my rule of "if it doesn't matter which cells you use, it's a condition". Cells that do express Vpr do something different under a given set of conditions than cells that don't.

Obviously the hyper-correct way to do this would be to use genotypes that include cdc-whatever and Vpr wt overexpression alleles, but for one viral protein in one paper it makes no sense to adapt pombe Canto to allow it.

The next most genetically correct thing would be to put Vpr in the background, but that wouldn't show on the gene pages.

How important is it to curate these phenotypes for pombe? The big-picture aim of the paper seems to be to elucidate how Vpr works in its host cells, rather than to learn about the cell cycle itself in fission yeast or even species-neutrally.

If it is worth curating, I guess you could (mis)use a condition, and I'll look the other way and pretend I don't see it ;)

**Comment by ValWood** [comment]
Yes that makes sense. I thought there might be something interesting about ppa2, and I was getting carried away curating it but really it isn't telling us anything about pombe.

**Comment by mah11** [comment]
oh, yeah, it is interesting biology and nifty how they've used pombe :)
