### ISSUE TITLE
NTR: decreased rate of microtubule polymerization PMID:16394105

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2834]
NTR: decreased rate of microtubule polymerization

descendant of
FYPO:0005681	decreased microtubule polymerization

standard def
ref: PMID:16394105

**Comment by mah11** [comment]
decreased rate of microtubule polymerization FYPO:0005703

For any process, "decreased" and "decreased rate" are siblings under "abnormal", because "decreased" is defined as "decreased extent", and rate or extent don't necessarily both change (i.e. you can have decreased rate without decreased extent - reaches the same extent but takes longer to get there).

edit file: 11877ed76fce9ae9583da5947f28b4c5e4ee6c6c
release: db5d4e543f7f6dbe443a927feaedadd5e3158917
