### ISSUE TITLE
Possible term merge abnormal septum and 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2841]
FYPO:0004292
abnormal septum

and
FYPO:0002455
abnormal septum during vegetative growth

is there a difference?

**Comment by mah11** [comment]
Well, FYPO:0004292 lacks the "vegetative growth" restriction, so it's available for any septum that is abnormal at other times.

If vegetative growth is the only life cycle phase in which pombe has septa, then we don't need to make the distinction and we can obsolete FYPO:0004292 (it doesn't have any annotations).

**Comment by ValWood** [comment]
I'm not aware of a septum during meiosis, but I don't know how it happens. All I know is, anything described so far is vegetative.

This is  the only paper I have seen about cytokinesis during meiosis is this one, not yet curated
https://www.ncbi.nlm.nih.gov/pubmed/22526418
the actin ring appears to guide the prospore membrane in meiosis in the same way that it guides the septum in mitosis.

I think we can remove it.

**Comment by mah11** [comment]
I've just found why we have both: abnormal includes mislocalized, and we've kept the "stationary phase" terms separate from the "vegetative growth" terms, so we have "mislocalized septum in stationary phase" (FYPO:0004294) is_a FYPO:0004292.

Stationary phase is a funny one, because it's applicable at the level of a population (cell deaths = cell divisions, so total number of living cells stays the same). Any cell that does divide in stationary phase is likely doing so in a vegetative-growth kind of way, so separating stationary from vegetative in FYPO is more me being cautious than a hard-and-fast biological reality. I probably won't go and change most of the stationary phase terms, but if you think it's better to fudge in the FYPO:0004294 (i.e. put "mislocalized septum in stationary phase" under "abnormal septum during vegetative growth") case so we can get rid of FYPO:0004292, I won't make a big fuss.

**Comment by ValWood** [comment]
Nah whichever you think is best.

**Comment by mah11** [comment]
Leaving it as is means less work for me ;)

**Comment by ValWood** [comment]
Its not offending me, it was a curiosity which I will ignore now I know :)
