### ISSUE TITLE
phenotype sounds the same.....

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2857]
mitochondrial aggregation at cell tip
monopolar intracellular mitochondrion distribution

(both used for nda3-KM311)

**Comment by mah11** [comment]
id: FYPO:0000896
name: mitochondrial aggregation at cell tip

id: FYPO:0003811
name: monopolar intracellular mitochondrion distribution

The way they're defined, they're not quite identical. FYPO:0000896 says that mitochondria are clustered more than normal (as in the parent def), and that the cluster(s) are at one or both cell tips - it's not restricted to one tip by the def.

FYPO:0003811 says that mitochondria are only found at one, not both, cell tips; it doesn't say they're clustered together more than usual at the tip.

The terms can be merged, with def adjustments, _if_ both of these are true:

1. Aggregated mitochondria never go to both cell tips at once.

2. Any time mitochondria are found at only one cell tip, they're aggregated.

Is that the case?

**Comment by ValWood** [comment]
OK there are 2 annotations to 
FYPO:0000896 - mitochondrial aggregation at cell tip
nda3 and pka1.

Nda3 paper has

![mmb1](https://cloud.githubusercontent.com/assets/7359272/20941777/f27d93f4-bbef-11e6-8d87-7884ef96e249.jpg)
![mmb1-txt](https://cloud.githubusercontent.com/assets/7359272/20941782/ffb1d4b8-bbef-11e6-87a9-16a5e091770f.jpg)

but oddly mmb1 is not annotated with this phenotype from this paper....

**Comment by ValWood** [comment]
nda3 to
FYPO_ID(FYPO:0003811 - monopolar intracellular mitochondrion distribution)
is as above (I think, a bit diffucult to follow because the figure numbering doesn't seem to quite correspond in this paper)

So in summary there does seem to be aggregation at one, or both ends, but the phenotypes are related and seem to co-occur at least sometimes...

Does that help?

**Comment by mah11** [comment]
In the pics for nda3 and mmb1, mitochondria may be symmetrically or asymmetrically distributed, but they don't look particularly localized to the cell tip(s); they're all over one or both halves of the cell.

In the pka1 mutant the localization looks more restricted towards cell tips, but is that just because the whole micrograph is dimmer? And it still doesn't look as tightly end-localized as, say the Tea proteins. That makes me think we could lose the 'cell tip' business, or relegate it to synoyms'

If these micrographs cover all of the phenotypes you need to describe, how about:

    FYPO:0000894 ! abnormal intracellular mitochondrion distribution
    [i] FYPO:0000895 ! mitochondrial aggregation
    - [i] FYPO:new1? ! asymmetric mitochondrial aggregation	RELATED synonym 'monopolar mitochondrial aggregation'
    - [i] FYPO:new2? ! symmetric mitochondrial aggregation

optional: include RELATED synonyms using 'aggregation at cell tip'

I could either make FYPO:0000896 and FYPO:00003811 obsolete, or change them so that FYPO:00008956 becomes FYPO:new2 (symmetric mitochondrial aggregation) and FYPO:00003811 becomes FYPO:new1 (asymmetric). That depends on whether existing annotations will be OK if I reuse the existing IDs.

This all assumes that if mitochondria are only on one side of the cell, they're also aggregated. I don't see any exceptions in the pics above.

**Comment by ValWood** [comment]
Yes I think you are right, we should lost the cell tip part altogether. 
I wonder if the phenotype is really about distribution at all, because this  partitioning is what happens prior to mitosis anyway. It's maybe more about the aggregation.....

so its either
aggregated
-- aggregated and asymettrically localized

which I think is  what you  are saying.

I think you can tweak the defs and I'll double check the annotations (the above are all of them so it will be quick)

**Comment by mah11** [comment]
merged FYPO:000896 int FYPO:000895
  adjusted FYPO:0003811, FYPO:0003897 names, text & logical defs, synonyms
  added new term
  -  symmetric mitochondrial aggregation FYPO:0005838

edit file: c7a15cafaa8050e2b54a4c11583417bbfe467ba2
release: 74369eefb832ad18294fb77705d090d23e345ed8
