### ISSUE TITLE
ntr: abolished mitotic spindle assembly checkpoint  silencing

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2865]
See
https://github.com/geneontology/go-ontology/issues/12741

**Comment by ValWood** [comment]
ref PMID: 19592249

also today
PMID:21664573

also need 
delayed mitotic spindle assembly checkpoint silencing
(the checkpoint eventually switches off by at a much slower rate)

**Comment by ValWood** [comment]
and "normal mitotic spindle assembly checkpoint silencing"

**Comment by mah11** [comment]
in light of the discussion on the GO ticket, do you still want 'silencing' in synonyms?

**Comment by ValWood** [comment]
Definitely silencing as synonyms because thats what its usually reported as so I think users will search on that....

**Comment by mah11** [comment]
abolished deactivation of mitotic spindle assembly checkpoint FYPO:0005726
  decreased rate of deactivation of mitotic spindle assembly checkpoint FYPO:0005727
  normal deactivation of mitotic spindle assembly checkpoint FYPO:0005728

> (the checkpoint eventually switches off b[ut] at a much slower rate)

I used 'decreased rate' for FYPO:0005727 because of this comment. Let me know if you also need 'delayed' (defined as starting later than normal).

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
