### ISSUE TITLE
ntr: prospore membrane formation PMID:27630265

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2868]
abnormal initiation of prospore membrane formation (Aka activation)
abnormal prospore membrane expansion

**Comment by ValWood** [comment]
PMID:27630265

**Comment by ValWood** [comment]
delayed initiation of prospore membrane formation (Aka activation)

**Comment by mah11** [comment]
Can we define the processes of initiation/activation of prospore membrane formation and prospore membrane expansion (and request GO terms)?

**Comment by ValWood** [comment]
I'm not sure about this.

Here the authors infer that the small spores they are seeing are caused by a defect in membrane expansion, which makes sense, but maybe I should just curate small spores.?
or "abnormal regulation of prospore membrane biosynthesis"?

They also interpret another phenotype  that  prospore membrane  biosynthesis is never started.
So maybe "abnormal regulation of  activation of prospore membrane biosynthesis"?

Then I assume that we would not need new GO terms?

**Comment by mah11** [comment]
OK, I'm certainly no expert in this area, but I've had a look at the paper. It does look like prospore membrane formation goes wrong right from the start in some of their mutants.

For the cases they interpret as "prospore membrane biosynthesis is never started", I suggest "abolished prospore membrane formation" (FYPO:0001915). The "regulation" bit is an inference based on the observed phenotype plus prior knowledge about the Ypts, so I wouldn't use a regulation phenotype term. (But I don't object to simplifying evidence to IMP for a GO annotation to a regulation term.)

For their "delayed initiation of prospore membrane formation", I'll add "delayed prospore membrane formation" - FYPO "delayed" terms are all "delayed onset", defined as "starts later than normal", so that fits the observation. See above for why not to use "activation" (it's a type of positive regulation in GO, and regulation is the inference, not the observation, here).

The membrane expansion thing looks hardest to represent. They do indeed see smaller-than-normal spores, so annotating to "small spore" wouldn't be wrong. I wonder if "decreased prospore membrane formation" (FYPO:new) would be sufficiently prospore membrane-specific to make everyone happy?

**Comment by ValWood** [comment]
yep....
and agree about the regulation for phenotype

I also requested a GO term
for this
0a18d3058ad0058a/feature/gene/view/1

prospore membrane biogenesis (might be useable for logical def?)

**Comment by mah11** [comment]
Well, I didn't comb through the paper exhaustively, but from the parts I did read I'd stick with 'prospore membrane assembly' - I didn't see anything about synthesis of phospholipids etc. being directly affected (or assayed).

**Comment by ValWood** [comment]
Ah I thought biogenesis covered synthesis and assembly? Isn't it broader?

**Comment by mah11** [comment]
yes; what I'm saying is that I didn't read anything in this paper that addresses synthesis (if it's there, it's in the parts I didn't read)

**Comment by ValWood** [comment]
Oh I see, I mention synthesis earlier... yep that's incorrect.... formation is correct

**Comment by mah11** [comment]
decreased prospore membrane formation FYPO:0005736
  delayed onset of prospore membrane formation FYPO:0005737

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
