### ISSUE TITLE
T shaped cell during G0 to G2 transition, and various phenotypes for tip1 in PMID:11007487

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2891]
requested in 
curs/8fb498d6aad39666#

T shaped cell during G0 to G2 transition
As cells re-enter G2 from G0 growth is initiated from a new growth axis causing a T shaped cell morphology

PMID:11007487

**Comment by ValWood** [comment]
and
bent cell during G0 to G1 transition
As cells re-enter G1 from G0 cell growth is initiated from a new growth axis causing a bent cell morphology

**Comment by mah11** [comment]
GO doesn't have anything about a G0 to G2 transition. Does it refer to this from our little in-house quiescence ontology?

[Term]
id: PBQ:0000004
name: cell quiescence following G2 arrest due to glucose limitation
def: "Cell quiescence, i.e. a specialized resting state in which the cells do not grow or divide, and the gene expression pattern changes globally, that a cell enters following cell cycle arrest in G2 due to glucose limitation." [PomBase:mah]
comment: Note that this type of cell quiescence has been characterized in fission yeast.
synonym: "cellular quiescence following G2 arrest due to glucose limitation" EXACT [PomBase:mah]
synonym: "quiescence following G2 arrest due to glucose limitation" BROAD [PomBase:mah]
is_a: PBQ:0000001

**Comment by ValWood** [comment]
Ah, I thought GO had something..... I copied Jacky's request verbatum as it seemed correct and I thought you would tweak the defs.

**Comment by ValWood** [comment]
hmm I was reading that as G0 to G1 transition...

**Comment by ValWood** [comment]
yes its following PBQ:0000004

**Comment by ValWood** [comment]
also
short disorganised cytoplasmic microtubules
Interphase microtubule bundles do not reach the cell tips and are not aligned parallel to the long axis of the cell
child of FYPO:0002760	short cytoplasmic microtubules
Fig 3F

**Comment by mah11** [comment]
OK, if you don't know otherwise, I'll assume the G0-toG2 term does refer to PBQ:4, and carry on.

**Comment by mah11** [comment]
> short disorganised cytoplasmic microtubules
> Interphase microtubule bundles

For this one, should I do it as microtubules or microtubule bundles? It'll affect which GO CC term the xpk refers to, and I'll make the name and def match.

**Comment by ValWood** [comment]
@jvhayles are these bundles?

**Comment by ValWood** [comment]
thinking about it of course they are
and Google agrees
"fission yeast cells display three to five long MT bundles that extend along the long axis of the cell"

**Comment by mah11** [comment]
OK. Should I change existing FYPO cytoplasmic microtubule terms to refer to bundles?

**Comment by JackyVH** [comment]
Yes they are bundles and yes I think that the term microtubule is nearly always referring to microtubule bundles. However for example  tea2/tip1 are localised at the tip of the growing microtubule bundle but are also being transported along a microtubule within the bundle  so what is seen is a bigger blob (technical term) at the tip of the bundle and then much fainter blobs that move along the microtubule at a faster rate than the growing microtubule bundle to reach the tip of the bundle.  I hope this makes sense

Jacky

**Comment by ValWood** [comment]
decreased protein localization to cell cortex of cell tip
child of
FYPO:0001586	decreased protein localization to cell tip

**Comment by ValWood** [comment]
requested in
curs/8fb498d6aad39666#
increased microtubule catastrophe rate at cell cortex
A cellular process when growing interphase microtubules switch to shrinkage at a high frequency when they reach any cortical region of the cell and is no longer restricted to the cell tips

since
FYPO:0004616
abolished cytoplasmic microtubule depolymerization at plus end at cell tip

has synonym 
abolished microtubule catastrophe at cell tip

I used
FYPO:0003194	increased rate of microtubule depolymerization
so 
- [ ] could we have a cell tip specific term?
and
- [ ] add synonyms for catastrophe?

**Comment by ValWood** [comment]
final one:
decreased dwell time at cell tip
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which microtubule plus ends remain in contact with the cell cortex at cell tips for a shorter time than normal.

**Comment by ValWood** [comment]
More from Jacky for
T shaped cell during G0 to G2 transition
in /curs/b19dfb2b27f82b53 PMID:11018050

(@jvhayles , I think this is the same?)
T-shaped cell after re-entry into the cell cycle from stationary phase
Cells show a T shaped cell morphology when entering the cell cycle from stationary phase

And this comment:
Fig 4 I know this term is a synonym but it implies that cells can re-enter the cell cycle from different stages of the cell cycle not just GO to G1, so I think it is not a synonym. In the situation described in this paper the cells are grown in YES so will exit and re-enter the cell cycle from G2, though this was not shown. I think it needs a more general term as well as having the G0 to G1 term
(which I think is what we figured?)

**Comment by mah11** [comment]
I've added these new terms:
  T-shaped cell during G0 to G2 transition FYPO:0005792
  bent cell FYPO:0005793
  bent cell during G0 to G1 transition FYPO:0005794
  abnormal microtubule bundle structure FYPO:0005795
  short disorganized microtubule bundle FYPO:0005796
  short microtubule bundle FYPO:0005797
  decreased protein localization to cell cortex of cell tip FYPO:0005798
  decreased microtubule dwell time at cell tip FYPO:0005799

and added 'microtubule catastrophe' related synonyms for 'microtubule depolymerization' terms that didn't already have them.

I've moved the rest of the rejig to 'microtubule bundle' to #2893 because it'll take a bit more time and thought, so I'll tackle it separately. Similarly, the bit about a generic T-shaped/quiescence term is now in #2895 because it didn't come in until I'd done the rest). Closing this, since I think everything is done or re-housed (open a new ticket for anything I've missed)

edit file: e11093212f09d87e8061de7ef35a29411f9fe4b8
release: a9a214f7dcfe1d1a32dcb82bd952317396a78d54
