### ISSUE TITLE
ntr: microtubule movement etc for PMID:15177031

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2897]
https://curation.pombase.org/pombe/curs/ce1fc9c90e999884/ro/

Abolished protein localisation the microtubule plus end
Situation in which the localisation of a protein normally localised at the microtubule plus end is abolished

descendent of
FYPO:0000931	abnormal protein localization to microtubule cytoskeleton during vegetative growth

and
protein localisation to nuclear region during mitotic interphase
localisation of protein to cytoplasmic region in vicinity of the nucleus during mitotic interphase. The protein may be mislocalized or fail to be normally removed
descendant of
FYPO:0001370	abnormal protein localization

**Comment by ValWood** [comment]
abolished transport along cytoplasmic microtubules
A situation where a protein can bind to microtubules but its movement along microtubules is abolished

(actually this could be "abolished transport along cytoplasmic microtubules to cell tip")

**Comment by ValWood** [comment]
normal movement along cytoplasmic microtubules to cell tip
situation where movement of a protein along microtubules is the same as wild type

**Comment by mah11** [comment]
Is that last one (normal movement along cytoplasmic microtubules to cell tip) the same as in #2896? If not, what's the difference?

Also, would "abolished transport along cytoplasmic microtubules to cell tip" refer to the same process? I'm a little hazy on whether to use "transport" or "movement", and whether there's a reason not to use "movement" for both the normal and abolished FYPO terms.

**Comment by ValWood** [comment]
yes, anywhere I have used transport or movement, I mean the same thing.

**Comment by mah11** [comment]
added:
  abolished protein localization to microtubule plus-end FYPO:0005814
  abnormal protein localization to perinuclear region of cytoplasm during mitotic interphase FYPO:0005815

I'm going to close this because I've added the terms not related to #2896. I'll leave the other ticket open and add a note to include 'abolished' as well as 'normal' once we're all confident about what the process is.

edit file: 85705a33c6973058513adaeb1cbffc0f932f4fba
release: f701ceddcb5be7069b0b51dd8744b5bc4d16e188
