### ISSUE TITLE
NTR:  accumulation of F- actin  PMID:12764130

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2924]
Figure 4 B
accumulations of F actin in the cytoplasm during vegetative growth

descendant of FYPO:0000350	abnormal actin cytoskeleton morphology during vegetative growth

**Comment by ValWood** [comment]
+ increased actin cable formation

**Comment by ValWood** [comment]
NTR: inviable after spore germination, multiseptate without cell division
standard def

descendant of
FYPO:0001991	inviable after spore germination, without cell division
FYPO:0000118	multiseptate vegetative cell

**Comment by mah11** [comment]
I've done the first one as "aggregated" because we've mainly used "accumulation" as a related synonym for "level of $stuff", which doesn't capture the abnormal morphology angle for the cytoskeleton. It's got plenty of synonyms.

  aggregated filamentous actin in cytoplasm FYPO:0005853
  abolished actin cable assembly FYPO:0005854
  inviable after spore germination, single cell division, multiseptate cell FYPO:0005855

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4

**Comment by ValWood** [comment]
> increased actin cable formation ?

**Comment by ValWood** [comment]
s'Okay, I did this as "thick actin cables' it works

**Comment by mah11** [comment]
sorry, copy/paste glitch - FYPO:0005854 is increased, not abolished
