### ISSUE TITLE
FYPO:0001214  sensitive to potassium chloride 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2940]
FYPO:0001214  sensitive to potassium chloride is not currently a child of sensitive to salt stress

**Comment by Antonialock** [comment]
also, it seems sensible to also have "sensitive to NaCl", and then I can move a lot of the existing sensitive to salt stress + condition annotations to the more specific terms?

**Comment by Antonialock** [comment]
Hmm...

another 'popular' salt is CaCl2. For this I think I  pick "sensitive to calcium" or "sensitive to salt stress + CaCl2 condition" depending on the context....which doesn't really feel like a satisfactory way to do it.

How do you think we could handle these annotations best overall? (in reality it is impossible to know if the cells are sensitive to e.g. the calcium ion or the osmotic stress, unless they do several tests, which they often don't do.

**Comment by ValWood** [comment]
Maybe we need to discuss this one.
I think I favour specific phenotypes, because as you say there is often know way to know what the sensitivity is to (calcium or osmotic stress), but not specific GO terms   for the chemical,  but for the response type

during response to heavy metal
during response to osmotic stress 
where different pathways deal with the insult

**Comment by mah11** [comment]
I don't usually think of calcium chloride as a salt stress - chemically it's a salt, but I would annotate to "sensitive to calcium" because calcium ions have specific effects. (I also tend to think of salt stress sensitivity as being tested using NaCL or KCl, and osmotic with sorbitol.)

As for classifying sensitivity to NaCl or KCl, you know I try to avoid doing too much of that manually because it can be hard to maintain. But _if_ NaCl/KCl _always_ imposes salt stress, I can move those terms down. Do you know of any exceptions?

This issue has nothing to do with whether you would or wouldn't do a GO annotation so let's not drag that in any further.

**Comment by Antonialock** [comment]
Genetically there are differences between NaCl stress and KCl stress - sty pathway mutants are sensitive to both, whereas git mutants are sensitive to KCl (and CaCl). 

I don't think it makes sense to specifically lump NaCl and KCl. This is a random image I grabbed when googling KCl NaCL cell import, it looks like they can go via quite different routes so it makes sense their effects are not same same but different

![screen shot 2017-01-10 at 10 33 36](https://cloud.githubusercontent.com/assets/12727506/21812302/7a51f0f4-d720-11e6-8fab-9d00cd185909.png)

**Comment by mah11** [comment]
That's all interesting, and useful for annotations, but what I need to know for the ontology is kind of the other way round. I didn't think there was ever any suggestion that we would "lump KCl and NaCl" in the sense of merging the FYPO terms with each other or any less specific term.

Instead, I need to know whether there's ever any case of "sensitive to KCl" that would NOT count as "sensitive to salt stress", and same question for NaCl. That will tell me whether it's OK to move one or both terms to be is_a "sensitive to salt stress".

**Comment by Antonialock** [comment]
Well, I don't think "sensitive to potassium" or "sensitive to sodium" should be is_a "sensitive to salt stress" but KCl and NaCL _are_ salts by definition..?

**Comment by mah11** [comment]
added
sensitive to sodium chloride FYPO:0005889

I haven't put it or 'sensitive to KCl' under salt stress yet.

**Comment by mah11** [comment]
closing because old; reopen if there is any specific thing to do
