### ISSUE TITLE
can FYPO terms be restructured  for better alphabetical term sorting 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2958]
Q: SGO is there any reason why phenotype term names cannot be restructured to
abolished x     ->    x, abolished
normal x    ->    x, normal
increased x -> x, increased
decreased x -> x, decreased
would result in better alphabetical grouping on the gene pages
http://www.pombase.org/spombe/result/SPBC11B10.09#fission_yeast_phenotype-single_allele-population_phenotype

JB, JM agreed.
I could not think if there was a reason....

**Comment by mah11** [comment]
Hmmm. Although I understand the motivation behind it, I don't love this idea. Changing the term names would not be pure gain -- it's a trade-off in which slightly improved grouping on gene pages would be offset by some negatives:

- The names are more consistent the way they are now with most other phenotype ontologies (albeit not all), and with normal English syntax;

- Because they follow normal English syntax, each term name is more readable by itself than it would be if we swapped words around;

- Putting the modifier first helps a bit with drilling down as in Canto;

- People have become familiar with the current names (although this point is minor and I could dismiss it in the absence of the other considerations).

Bear in mind also that renaming terms would only make a small dent in the problem of enormous lists on pages like cdc2 and mcm2. In any order those lists are incomprehensibly long and full of fussy details. We need a more sophisticated solution to the laundry-list problem, and if we come up with a good one we may not need to make term name changes do the job.

So in light of the fact that there's a trade-off in which the benefit is a partial solution at best anyway, I am inclined to keep the current names rather than do the work -- which can't be fully automated -- of changing all that would be affected. At an off-the-cuff guess it's probably around 4000 terms.

**Comment by ValWood** [comment]
I was sure that you would not like it :)

Lets sit on this because as you say, it isn't an ideal solution for everything...

Its useful to have it hear as a suggestion. ...and we need to think more about the  long phenotype lists.....

**Comment by Antonialock** [comment]
I kind of like this suggestion for any of the "flat" phenotype categories (sensitivity to chemical: increased/decreased/normal, growth: increased/decreased/normal. It would help with readability for me (I don't browse ontologies like I read a book anyway so I don't think we need to stick to normal english syntax for that reason).

I don't like it for phenotypes where you can drill down deep in the ontology (say the chromosome segregation part of the ontology for instance). 

I think Midori is right in that it would create a lot of extra work for some slight benefit?

Maybe we can do something nicer. The slim "summary" for BP annotations looks good, maybe we can do something similar for phenotypes. We might need to split this section because the different phenotype "categories" are quite different. Perhaps we could summarise the data on a few rows e.g.

abnormal biological processes
chromosome segregation, recombination

drug responses:
sensitive to: benomyl, mbc, hydroxyurea
resistant to: UV

growth
...

**Comment by ValWood** [comment]
I would prefer to have a summary section  and filters
Term suggestions fro FYPO summary at top of page are in this ticket:

https://github.com/pombase/website/issues/80

I don't think we can go the route of arranging the data  within the section by category...too may things in multiple sections.....
