### ISSUE TITLE
T-shaped cell output_of link

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2964]
regardless of my possible misunderstandings here:
https://github.com/pombase/fypo/issues/2963

should 
T-shaped cell	FYPO:0005566	output_of	abnormal cell polarity	FYPO:0005568

be output of abnormal vegetative cell polarity (we should define this microtubule T-shaped as a vegetative cell mutant)

**Comment by mah11** [comment]
No, because "T-shaped cell during recovery from quiescence" FYPO:0005810 and its two is_a children are not under "vegetative cell" (we haven't put any "recovery from quiescence" terms under "vegetative growth" ancestry).

Since it isn't being inferred, I can manually add FYPO:0000013 ! T-shaped vegetative cell output_of FYPO:0000026 ! abnormal vegetative cell polarity.

**Comment by ValWood** [comment]
Hmm, OK, is the quiescent cell T-shaped...I thought it was once the cell is vegetative again...tricky...

Anyway, I was using T-shaped cell, I should have been using "T-shaped vegetative cell"
but yes if the link could be added if it isn't there...

**Comment by mah11** [comment]
link added

edit file: 0d9722396812a51fc5f72387734c81fe4137fa4a
release: 6f259a41134e8ac25aef2208b93300fefa663bad
