### ISSUE TITLE
localization phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2983]
I noticed that 
"decreased punctate nuclear protein localization"

is not  present when the "localization phenotype " filter is set. I think it might be missing a parent?

**Comment by mah11** [comment]
This is because the parent, mislocalized protein during vegetative growth, has the link  output_of FYPO:0000443 ! abnormal protein localization during vegetative growth (not is_a or part_of). To get the behavior you want, Kim will have to have the filters use the output_of relation for FYPO, and probably also has_output.
