### ISSUE TITLE
ntr: abolished microtubule cortical anchoring

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2994]
PMID:25736293

fig 3B and supp 3B

descendent of:
	FYPO:0005464	abnormal maintenance of protein location at cell tip

x product with ? 
https://github.com/geneontology/go-ontology/issues/13348

**Comment by mah11** [comment]
This reads as though it would refer to a GO BP rather than MF term, perhaps GO:0097248 'maintenance of protein location in cell cortex of cell tip', plus another xp part to make it specific for microtubules. That would certainly be a better fit for the suggested ancestor, which is in the BP phenotype department of FYPO. (Also, the MF term suggested in the linked GO ticket isn't tip-specific so it wouldn't capture all the necessary conditions anyway.)

**Comment by mah11** [comment]
Scratch that - better idea for new GO term for xp based on existing 'microtubule anchoring' terms: "microtubule anchoring at cell cortex of cell tip"

**Comment by mah11** [comment]
abnormal protein localization to cell tip FYPO:0005987
  abolished microtubule anchoring at cell cortex of cell tip during meiotic cell cycle FYPO:0005988

renamed FYPO:0001584 and some descendants to make 'vegetative' explicit

FYPO:0005988 is not under FYPO:0005464 because the existing terms are all specific for vegetative growth. For now, I've just put FYPO:0005988 directly under FYPO:0005987; we can fill in non-veg-specific intermediate terms as the need arises.

edit file: 01ba4a11eebc4116f235ea963c18d01e231dc4ef
release: acbc41b365922deb2a26ca46510834c779d780c0
