### ISSUE TITLE
	abolished cell division timing change upon nitrogen source shift

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3009]
parentage.

should this be a cell cycle phenotype?

**Comment by mah11** [comment]
At the simple superficial level, FYPO:0004701 is not connected with cell cycle phenotype terms because it's classified and defined as a population phenotype, whereas all the cell cycle terms are under cell phenotype.

As for why FYPO:0004701 was done that way, there's background in #2236 and #2508. Re-reading them now, it seems that it did our heads in a bit at the time.

**Comment by ValWood** [comment]
OK just wondered, I guess mitotic index and septation index would be the same.
No filters apply to it so I was curious, but it isn't really a problem...
