### ISSUE TITLE
ntr: karmellae formation PMID:28242692

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3013]
Overgrowth of nuclear membranes  resulting in karmellae: a proliferation of stacks of endoplasmic reticulum membrane develop around the nucleus.

descendant of FYPO:0000769

**Comment by mah11** [comment]
Do you want a structure phenotype or a process phenotype? An is_a path to FYPO:0000769 implies a structure phenotype, and that's what I'm inclined to use here. But then its name would be "karmellae present" or something to that effect.

**Comment by Antonialock** [comment]
Term name 	excess endoplasmic reticulum membrane present
Definition 	A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which cells contain more endoplasmic reticulum (ER) membrane than normal. Excess ER membranes may form abnormal structures.

?

**Comment by mah11** [comment]
I think there's a case for a term for the (inherently abnormal, at least for pombe) presence of karmellae, since they have a distinctive structure.

Given that the ER membrane and outer nuclear membrane are continuous, it is tough to decide whether to put "it's got karmellae" under abnormal ER membrane or abnormal nuclear envelope. I don't know if it's both at once ...?

**Comment by ValWood** [comment]
excess endoplasmic reticulum membrane adjacent to nuclear envelope ?
(The Karmella appear to be specifically associated with the nucleus)


I also need a term  for suppression of this phenotype,

"Thin- section electron microscopy of single- and double-mutant cells demonstrated that karmellae formation in vps4Δ cells was com- pletely suppressed by loss of cmp7 or lem2 (Fig. 5). "

Karmella present or absent can be synonyms?
I agree its a structure term...

**Comment by ValWood** [comment]
hmm, I guess it's both. It seems to manifest ore at the nuclear envelope...

**Comment by ValWood** [comment]
although maybe here is better to point to...
GO:0097038 perinuclear endoplasmic reticulum
(I can ask Adam when I am done....I agree it's continuous so its a problem to call....)

**Comment by ValWood** [comment]
See figure 4 for the best pics....

**Comment by ValWood** [comment]
> I also need a term for suppression of this phenotype,

I guess that would be "normal nuclear envelope morphology" ;)

**Comment by mah11** [comment]
I can use "karmellae" in the name, because they're adjacent to the nucleus by definition (among other features). My question was whether you're happy with 'abnormal endoplasmic reticulum morphology' as the ancestor - the papers (well, abstracts mostly, tbh) I'm looking at suggest that's the best thing to use.

Another question: is it always abnormal to see karmellae in pombe? A few minutes ago I thought so, but I've now learned that it's normal for budding yeast to form karmellae under conditions that increase expression of HMG-CoA reductase. Does anything similar happen in pombe?

**Comment by mah11** [comment]
>> I also need a term for suppression of this phenotype,
>
> I guess that would be "normal nuclear envelope morphology" ;)

yup.

**Comment by ValWood** [comment]
Later, says 
Similarly, overexpressing Lem2p in S. pombe, or compromising nuclear import of Heh2p, an ortholog of Lem2p in S. cerevisiae, induces the formation of similar abnor- malities (31, 32).

Previously I annotated as  "excess nuclear envelope present"
http://pombase2.aska.gen.nz/genotype/654d33ea7fb3acba-genotype-5

So could we place under "nuclear" and make this a parent?

**Comment by ValWood** [comment]
nice cartoon in supp

![both](https://cloud.githubusercontent.com/assets/7359272/25667564/c4a21e46-301b-11e7-8471-b54048d3976b.jpg)

**Comment by ValWood** [comment]
Can it be both abnormal ER and abnormal NE? I think that would work best?

In pombe I don't think that Karmella are ever normal (at least in these quantities).
I wonder if they are normal in S.c, if this is overexpression of HMG-CoA reductase, isn't this also an abnormal  phenotype where excess membrane is produced?

**Comment by mah11** [comment]
> Can it be both abnormal ER and abnormal NE?

I'm kind of leery, but can try it, since the membranes are continuous.

As for S.c., I don't know how high the HMG-CoA reductase levels in question are, but as long as I'm only doing the ontology for fission yeast phenotypes, I don't have to worry about whether karmellae are ever normal in other species ;)

**Comment by ValWood** [comment]
Well until today I had never heard the word Karmella, so I'm guessing they aren't common in pombe, and the "excess nuclear envelope" is abnormal anyway

**Comment by ValWood** [comment]
Adam:
My only other comment is to emphasize that, as far as anyone knows, karmellae are always pathological in Sc or Sp.

**Comment by mah11** [comment]
karmellae present FYPO:0006019

edit file: 5db139c03ed753121711c62c481a369bf4b04bb7
release: 9431b22e28d71d174a057ee0fac5591aac32b6ad
