### ISSUE TITLE
odd viability phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3020]
This might need to go on website tracker, not sure.

When I filter "ark1" on "viability phenotypes" I see

normal growth on camptothecin?
(but this filter  excludes  chemical sensitivities, so I did not expect to see this)

**Comment by mah11** [comment]
It's because all of the "normal growth on x" terms are is_a FYPO:0001357 ! normal vegetative cell population growth. It's a little odd because it implies that the parent means "normal growth under some set of conditions" rather than "normal growth under any and all conditions". But if we didn't do it that way, I'm not sure how we could give the "normal on x" terms logical definitions.

Oh, and FYPO:0001357 is_a FYPO:0002060 ! viable vegetative cell population, because if a population is growing at all it's got to be viable.

I haven't put sensitivity terms under viable or inviable, because the degree of sensitivity can vary such that a population may be viable or inviable on a given x, but I can think about whether it would work to move to viable. Not sure without a think.

**Comment by ValWood** [comment]
Its probably not a problem, I just thought it seemed strange at frist glance  but it makes sense...

**Comment by mah11** [comment]
OK. In the meantime I thought up another possible approach. I'll close this until/unless we get user confusion or complaints, but will record my crazy idea in case we need it:

I could kludge xps for most of the normal on x terms as intersection_of "normal growth on chemical substance" (FYPO:new), and then only the new grouping term and the IR and UV terms would wind up directly under FYPO:0000139 ! cell population growth phenotype or FYPO:0001358 ! vegetative cell population growth phenotype.

If that sounds like gibberish, don't worry; I'll know what it means and can explain later if we wind up doing it ;)
