### ISSUE TITLE
various PMID:27146110 spindle stuff

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3025]
ntr: incomplete mitotic metaphase chromosome recapture
meredith's def:
abnormal mitotic metaphase chromosome recapture' that includes aberrant pausing of the kinetochore near the SPB during recapture, instead of the usual complete capture all the way to the SPB.

ntr: abnormal kinetochore microtubule polymerization during mitotic metaphase chromosome recapture
meredith's def:
An 'abnormal kinetochore microtubule polymerization during mitotic metaphase chromosome recapture' is an 'abnormal mitotic metaphase chromosome recapture' that includes aberrant lengthening of the microtubules that move the kinetochore away from the spindle-pole body, instead of the usual mirotubule shortening.

should probably be "involved in"?

ntr: decreased time to mitotic metaphase chromosome recapture
meredith's def:
A 'decreased time to mitotic metaphase chromosome recapture' is an 'abnormal mitotic metaphase chromosome recapture' in which chromosomes are recaptured more quickly than for wild-type cells

ntr:  increased time to mitotic metaphase chromosome recapture
meredith's def:
A 'increased time to mitotic metaphase chromosome recapture' is an 'abnormal mitotic metaphase chromosome recapture' in which chromosomes are recaptured more slowly than for wild-type cells

**Comment by ValWood** [comment]
ntr:
increased rate of kinetochore sliding during chromosome recapture
Opposite of the existing term 'decreased rate of kinetochore sliding...'

**Comment by ValWood** [comment]
ntr: delayed mitotic sister chromatid biorientation
meredith's def:
A 'delayed mitotic sister chromatid biorientation' is an 'abnormal mitotic sister chromatid biorientation' in which biorientation is delayed.

**Comment by ValWood** [comment]
ntr	long mitotic spindle microtubules protruding beyond  the nuclear envelope from the kinetochore attached end of the microtubule.

def based on FYPO:0003787
A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which cells form mitotic spindle microtubules that are longer than normal, and  the kinetochore attached end of the microtubule extends beyond the nuclear envelope causing a protrusion. The protruding spindle microtubules are surrounded by an extension of the nuclear envelope.


(I hope you can word this better than me)

Its 
![protrusion](https://cloud.githubusercontent.com/assets/7359272/26410451/3b5f3502-409b-11e7-9e95-219a4cb38a5c.jpg)

**Comment by ValWood** [comment]
ntr: 	abnormal mitotic chromosome congression with chromosome centering
abnormal chromosome congression in which chromosomes fail to center on the spindle

**Comment by ValWood** [comment]
ntr: decreased interkinetochore distance before mitotic anaphase
The opposite of increased interkinetochore distance

**Comment by ValWood** [comment]
ntr
unstable mitotic spindle length
meredith's def: An abnormal bipolar mitotic spindle that undergoes large length fluctuations, rather than remaining constant in length. This is related to mitotic spindle collapse, but is not exactly the same.

**Comment by ValWood** [comment]
ntr: normal rate of chromosome segregation
meredith's def:  Normal speed of chromosome movement toward the mitotic spindle pole during anaphase chromosome segregation.

ntr: Delayed mitotic sister chromatid segregation

**Comment by ValWood** [comment]
ntr delayed mitotic sister chromatid biorientation
meredith's def: A 'delayed mitotic sister chromatid biorientation' is an 'abnormal mitotic sister chromatid biorientation' in which biorientation is delayed.

**Comment by mah11** [comment]
phew, so many questions ... here we go ...

1

> incomplete mitotic metaphase chromosome recapture

OK if I reword the def to "... in which mitotic metaphase chromosome recapture does not proceed until the kinetochore has moved all the way to the spindle pole body (SPB), but kinetochores instead pause abnormally near the SPB"?


2
> abnormal kinetochore microtubule polymerization during mitotic metaphase chromosome recapture
> 
> should probably be "involved in"?

I wouldn't use "involved in" here, because MT polymerization is not a normal part of chromosome recapture.

If no objections, I'll use def "... in which microtubules attached to the kinetochore lengthen instead of shortening".

3a
> decreased time to mitotic metaphase chromosome recapture

Is this advanced/premature onset or decreased duration?

3b
> increased time to mitotic metaphase chromosome recapture

Is this delayed onset or increased duration?

4
> delayed mitotic sister chromatid biorientation

just to confirm - this is delayed onset, not increased duration?

5
> long mitotic spindle microtubules protruding beyond the nuclear envelope from the kinetochore attached end of the microtubule

If the MTs are indeed "surrounded by an extension of the nuclear envelope", I wouldn't call this "protruding beyond the nuclear envelope". Following FYPO:0003787, it could be named "long mitotic kinetochore microtubules protruding beyond spindle pole body" (kinetochore microtubule is_a spindle microtubule in GO CC).

6
> abnormal mitotic chromosome congression with chromosome centering

Missing words "loss of" in suggested name?

Anyway, how about "uncentered mitotic chromosome congression", with def "...in which chromosomes do not align at the midpoint of the long axis of the mitotic spindle" (and a bunch of synonyms)?

7
> unstable mitotic spindle length

Could we use "fluctuating mitotic spindle length" as the name? "Unstable" sounds like it could include fluctuation or collapse. I could even use "unstable mitotic spindle length" with a more general def that would group the "collapse" terms and the new term for "fluctuating". Would that be useful?

I think they would all go under FYPO:0000131 abnormal mitotic spindle elongation (note to self: move existing terms from assembly to elongation).

unstable: spindle does not remain at a constant length or gradually elongate
fluctuating: spindle undergoes large changes in length, instead of remaining at a constant length or gradually elongating

**Comment by mah11** [comment]
a bunch of new terms (I checked the paper for rate vs. onset):

  incomplete mitotic metaphase chromosome recapture FYPO:0006039
  abnormal kinetochore microtubule polymerization during mitotic metaphase chromosome recapture FYPO:0006040
  decreased rate of mitotic metaphase chromosome recapture FYPO:0006041
  increased rate of mitotic metaphase chromosome recapture FYPO:0006042
  increased rate of kinetochore sliding during chromosome recapture FYPO:0006043
  long mitotic kinetochore microtubules with kinetochore at tip of nuclear envelope protrusion FYPO:0006044
  delayed onset of mitotic sister chromatid biorientation FYPO:0006045
  uncentered mitotic chromosome congression FYPO:0006046
  decreased interkinetochore distance before mitotic anaphase FYPO:0006047
  unstable mitotic spindle FYPO:0006048
  fluctuating mitotic spindle length FYPO:0006049
  normal rate of mitotic sister chromatid separation FYPO:0006050

and one last comment:

> ntr: normal rate of chromosome segregation
> meredith's def: Normal speed of chromosome movement toward the mitotic spindle pole during anaphase chromosome segregation
> 
> ntr: Delayed mitotic sister chromatid segregation

Because these are about anaphase movement, the existing "separation" term will do for "delayed", and I've added FYPO:0006050 as separation (in list above).

delayed onset of mitotic sister chromatid separation FYPO:0004705

Do reopen this or a new ticket if anything looks odd, missing, wrong, etc.!

edit file: 8327a5131881826ee4e520dff86baf58bd95679c
release: 85dea041789aa6f6b30f9397f131bc7615d8d37b
