### ISSUE TITLE
cytoplasmic microtubules

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3045]
we have a number of terms referring to cytoplasmic microtubules.
When people refer to "cytoplasmic microtubules"   without any further specification they are always referring to interphase microtubules (even though there are non-interphase cytoplasmic microtubules from the SPB).

I wonder if we could rename the terms to interphase microtubules?  (which would differentiate from  astral cytoplasmic microtubules).

This would allow some terms (which mean the same thing) to be merged.
Anything annotated to
"long cytoplasmic microtubules"  would be
"long cytoplasmic microtubules during mitotic interphase"

but the term name would be  "long interphase microtubules"

The associated curved terms would become "long curved interphase microtubules".

Otherwise quite a lot of annotation revisions will be required. We will need to move everything down to the "during mitotic interphase" term. Annotation would also be simpler as we would  have slightly fewer terms. Its a little confusing at the moment.

**Comment by mah11** [comment]
We can rename some of the "cytoplasmic microtubule" terms, but not all (one of your examples is one that actually can't change or merge). These will have to remain as "cytoplasmic microtubule" because they have descendants that refer to astral microtubules:

FYPO:0004088	abnormal cytoplasmic microtubules
FYPO:0005693	abolished cytoplasmic microtubule nucleation
FYPO:0004702	cytoplasmic microtubules absent from cell
FYPO:0000233	long cytoplasmic microtubules
FYPO:0001976	normal cytoplasmic microtubules
FYPO:0002760	short cytoplasmic microtubules

Even the ones that get "interphase microtubule" names will still have text definitions and exact synonyms using the "cytoplasmic microtubules during mitotic interphase" pattern, because that's how they will still have to be defined logically.

Also bear in mind that if we ever do create a species-neutral cell phenotype ontology, it won't allow this equivalence. Likewise, if someone else does the generic ontology, these changes will make this part of FYPO map less neatly to it.

**Comment by mah11** [comment]
further note to self:
add "interphase" versions of short and absent-from-cell terms
interphase terms exist for the others (long, normal, abnormal, nucleation)

**Comment by ValWood** [comment]
I think all of the long,  or curved cytoplasmic microtubule observations refer to interphase microtubules, except  a single annotation to "long astral microtubules during mitotic anaphase A"

Perhaps  do the ones possible, and we should put a soft check on  any non-specific cytoplasmic terms that are required for grouping to make sure we  always specify interphase or 
astral.
This will let us know which ones need to be moved down.
Will that work?

**Comment by mah11** [comment]
Outstanding question: should I rename these?
FYPO:0004727	cytoplasmic microtubule formation from nuclear microtubules
FYPO:0004728	cytoplasmic microtubule formation from nuclear microtubules following nuclear envelope breakthrough
FYPO:0004729	cytoplasmic microtubule formation from nuclear microtubules following spindle microtubule fragmentation

Other than that, I've renamed all of the "cytoplasmic microtubule" terms except the ones that group interphase and astral (listed in my earlier comment above).

New terms:
  abnormal interphase microtubules FYPO:0006101
  interphase microtubules absent from cell FYPO:0006102
  short interphase microtubules FYPO:0006103

Merges:
  FYPO:0005812 into FYPO:0004731
  FYPO:0005856 into FYPO:0005842

edit file: ffdd83fa748d74175fd9956e24f3c5d7fca0df50
release: 76e6d3958f70dff85f97ae7f370dbb0c1f63d300

**Comment by ValWood** [comment]
Hmm, good question. I think these should probably stay s they are because I'm not sure  exactly the timing of these phenotypes.

**Comment by mah11** [comment]
Thanks. That makes sense, and I like that it means I think this one's done :)
