### ISSUE TITLE
single elongated  microtubule bundle curved around end of cell PMID:14742702

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3100]
single elongated  microtubule bundle curved around end of cell

child of
long curved interphase microtubules

FYPO:0002400 | single microtubule bundle
(I'm assuming this must be a bundle although Takashi calls it a microtubule?- I can check if necessary)

![single long curved](https://user-images.githubusercontent.com/7359272/29356339-dfebe608-826b-11e7-912f-ecde84ab4889.jpg)

PMID:14742702

**Comment by mah11** [comment]
single elongated microtubule bundle curved around cell end FYPO:0006195

link to FYPO:0004511 is indirect, via has_part FYPO:0005880, because the new term xp's the GO MT 
bundle term, whereas "long MT" terms xp the GO microtubule term

edit file: 223f7a9792685bcd94375b201375310a0ce2dc24
release: 6e4551640b279c78826137094d3bb3b9247e3cb5
