### ISSUE TITLE
complex assembly  terms in GO where complex assembly is "spontaneous"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3112]
I'm worried that we are putting complex assembly terms in GO when the complex forms spontaneously, but we observe an assembly phenotype in complex member mutants
http://amigo.geneontology.org/amigo/term/GO:0072685
I.e no external "mechanism" for assembly exists.

Could we logically define these with
"GO abnormal complex assembly" and "GO complex terms" without instantiating a process term and  remove them from GO?  They should not have any annotations -but they could be misleading.

I think the same applies to some other processes, but we can address those later.

**Comment by mah11** [comment]
Complex assembly term gatekeeping really must be done at the level of GO BP. It'll get badly out of hand if I (and other ontology developers) have to maintain complex assembly-related terms using multiple systems. Whether any existing GO complex assembly terms shouldn't really be there is a question for the GO editors.

If there is no complex assembly process that would fit into GO, then there's no normal process going awry in a mutant, and I would build a FYPO term as an abnormal GO CC instead of abnormal GO BP (e.g. abnormal level or composition of the complex).

These are the complex assembly terms currently used for FYPO phenotype logical definitions:

Dsc complex assembly	GO:1990155
MCM complex assembly	GO:0072689
Mre11 complex assembly	GO:0072685
RITS complex assembly	GO:1904802
SAGA complex assembly	GO:0036285
anaphase-promoting complex assembly	GO:1904824
eukaryotic translation initiation factor 2B complex assembly	GO:1905173
gamma-tubulin complex assembly	GO:1902481
mitotic checkpoint complex assembly	GO:1905660
origin recognition complex assembly	GO:1902561
pre-replicative complex assembly	GO:0006267
protein complex assembly	GO:0043623
ribonucleoprotein complex assembly	GO:0022618
spliceosomal complex assembly	GO:0000245
telomerase holoenzyme complex assembly	GO:1905323
telomere-telomerase complex assembly	GO:1905324

If any look dodgy (I can vouch for ORC, pre-RC and pre-IC), open a GO ticket to ask whether they should go obsolete. I'll see the GO tickets and do any edits required to keep FYPO in sync with changes. (I would change the FYPO term name and text definition as well as the logical definition.)

> Could we logically define these with
> "[FYPO?] abnormal complex assembly" and "GO complex terms"

I'm not sure I fully understand what you're suggesting, but this sounds like it would still logically imply that there's a normal complex assembly process that can be broken in a mutant.

(Note to self: check whether FYPO:0003629 needs renaming; it doesn't have an xp)

**Comment by ValWood** [comment]
Ah OK in that case I think some should just be abnormal complex, not "abnormal complex assembly"

So to check:

Dsc complex assembly	GO:1990155
Mre11 complex assembly	GO:0072685
RITS complex assembly	GO:1904802
SAGA complex assembly	GO:0036285
anaphase-promoting complex assembly	GO:1904824
eukaryotic translation initiation factor 2B complex assembly	GO:1905173
gamma-tubulin complex assembly	GO:1902481
mitotic checkpoint complex assembly	GO:1905660
telomerase holoenzyme complex assembly	GO:1905323
telomere-telomerase complex assembly	GO:1905324


I will look through these.
