### ISSUE TITLE
synonym of 	abnormal mitotic sister chromatid segregation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3129]
I notice missegregation is an exact synonym of 
abnormal mitotic sister chromatid segregation

but I think it should be
unequal mitotic sister chromatid segregation?

isn't missegregation == unequal distribution of chromosomes

**Comment by mah11** [comment]
Well, in #2860 you asked for terms for "all chromosome segregation defects" to have "missegregation" synonyms, and I took that to mean "abnormal segregation" and its descendants (adjusted for mitotic and meiotic as needed).

Now, it might make sense to keep the synonyms on more terms rather than fewer, but make the scope EXACT for unequal segregation and RELATED for parents and siblings. Would that work for you?

**Comment by ValWood** [comment]
Yep!

**Comment by mah11** [comment]
done

edit file: 884374b24346e939e1e868297533dc49cc5fc21f
release: f08be34c1aaa2f3a32bc54e8fdcd703d89407fe4
