### ISSUE TITLE
mitotic DNA replication initiation from late origin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3151]
PMID:26804021
increased occurence of mitotic DNA replication initiation from late origin

**Comment by mah11** [comment]
It looks like they've measured timing of when certain origins fire, rather than how many late origins fire. So I've added:

premature mitotic DNA replication initiation from late origin FYPO:0006272

with the link FYPO:0006 output_of FYPO:0005758

edit file: d7d8f7a01f37575f82a9cf2a84742841d0172598
release: 02e684c4935884929353728e299d890329b04901
