### ISSUE TITLE
mitotic catastrophe types

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3165]
note from midori: moved original request that was here to new ticket, because mitotic catastrophe overtook the follow-up discussion

**Comment by ValWood** [comment]
and

Delayed onset of mitotic catastrophe with cut cell

Situation there is a delay in the onset of the inviable mitotic catastrophe phenotype. Cells eventually enter mitosis and septate to give rise to a cut phenotype. In a cut phenotype, a cell undergoes septation despite abnormal chromosome segregation, such that the septum physically divides the nucleus into two parts, and produces inviable daughter cell

Is that possible to model. I guess is where the checkpoint is activated, but because the problem can't resolve it "gives up" but there is a delay in the inevitable...

**Comment by mah11** [comment]
> delayed onset of mitotic catastrophe with cut cell

This one's odd, because the existing "delayed onset" terms are all for normal processes, i.e. they would occur in wild type cells, and in mutants they occur but get going later than normal. Cut and mitotic catastrophe are inherently abnormal, so what I think this must be is a sub-type of "mitotic catastrophe with cut" that features a longer pause at some point than another sub-type.

So I wouldn't do this as "delayed onset". If you and Jacky can clarify where the difference is, I can create two new terms, one for each duration of what I called the "pause".

The parent def is:
"...  a cell undergoes mitotic catastrophe (i.e. enters mitosis prematurely and with defective chromosome segregation), and then septates to give rise to a cut phenotype."

So is the difference that one "undergoes mitotic catastrophe ... and immediately septates to give rise to a cut phenotype" and the other "undergoes mitotic catastrophe ... and septates after a [long?] delay to give rise to a cut phenotype"? Or ...?

**Comment by ValWood** [comment]
I think the delay is in the mitotic catastrophe occurring.

@jvhayles can you elaborate 

 (is that the correct  git hub ID,  it doesn't  pop up when I type @....is there any way we can make it do so?)

**Comment by mah11** [comment]
I've added Jacky (@JackyVH) to the collaborators list for this tracker.

**Comment by mah11** [comment]
also added the straightforward term

  increased protein tyrosine phosphorylation during cellular response to hydroxyurea FYPO:0006287

edit file: 2d923e38871c32d7b817d0f5982ca825f8bd21fa
release: 40965462a454594dfe2df7e92f240b36ee5c320b

**Comment by JackyVH** [comment]
Hi Midori
the phenotype that was measured was the timing of the appearance of cut cells in a mik1 delete wee1-50 at 36 compared to a mik1D wee1-50 cig2 delete strain , where it was delayed. They don’t mention that there is any difference between the mik1D wee1-50 ‘cuts’ and the mik1D wee1-50 cig2D ‘cuts’.  With other cdc2 tyrosine phosphorylation data the argument is that active cig2 plays a role in the appearance of cut cells in the mik1delete wee1-50 at 36°C and if deleted the appearance of cut cells is delayed. The pause is before cells enter into mitosis rather than after entry into mitosis with a delay in septation .  I guess this could also be seen as cig2D is a partial suppressor of mik1D wee1-50 though they don’t say this. I haven’t got the paper with me at the moment but I’ll have a talk with Val and get back to you.
Jacky

**Comment by ValWood** [comment]
can we call this  something like
delayed mitotic entry resulting in mitotic catastrophe?

**Comment by JackyVH** [comment]
Yes something like that would do but it does sound  to me as if the delayed entry causes the mitotic catastrophe.  What about simply

“delayed onset of mitotic catastrophe”

as part of the definition of a mitotic catastrophe is that cells enter mitosis prematurely does mitotic entry need to be included in the term

or

delayed mitotic entry followed by mitotic catastrophe

Jacky

**Comment by JackyVH** [comment]
I meant to say that the model they suggest is that cdc2-cig2+ is somehow involved in kinetics of cdc2Y15 dephosphorylation. The dephosphorylation of cdc2(cdc2-cd13??) in the mik1Dwee1-50 causes premature activation of cdc2 and entry into a catastrophic mitosis.  In the a  mik1D wee1-50 cig2 delete cdc2 tyrosine dephosphorylation is delayed (? does cdc2-cig2 (directly or indirectly) phosphorylate and activate cdc25?)  and this slower cdc2 dephosphorylation (probably) delays the entry into mitosis and mitotic catastrophe but cannot completely prevent it

**Comment by mah11** [comment]
Thanks, Jacky.

So can we say there are two phenotypes

- one where mitosis starts at a normal time (or early? compared to wild type, anyway), but goes horribly wrong yielding mitotic catastrophe + cut; 

and

- one where mitosis starts later than normal, and then goes horribly wrong yielding mitotic catastrophe + cut?

If those descriptions are accurate, I suggest these names:

normal onset of mitosis followed by mitotic catastrophe with cut
delayed onset of mitosis followed by mitotic catastrophe with cut
(both subtypes of FYPO:0001048)

**Comment by ValWood** [comment]
If what I got in https://github.com/pombase/fypo/issues/3173
is correct, these would be 
mitotic catastrophe with cut elongated cell
?

**Comment by ValWood** [comment]
@JackyVH  do you agree?

**Comment by mah11** [comment]
> these would be
> mitotic catastrophe with cut elongated cell

What does "these" refer to? I put in suggestions for two terms. It sounds like the "these" in question are mutants that would use the second term (with 'delayed onset of mitosis' in the suggestion) - but I want to confirm that.

**Comment by ValWood** [comment]
Yes, I think the  phenotype Jacky was trying to describe
“delayed onset of mitotic catastrophe”

Is when the cells are both elongated (that is the delated part), AND go to mitotic catastrophe .

Would like Jacky to confirm though...

**Comment by mah11** [comment]
Curator meeting discussion has arrived at the conclusion that "delayed onset of mitosis followed by mitotic catastrophe with cut" is the same as FYPO:0001054, so add the new phrase as a synonym.

Similarly, add "normal onset of mitosis" and "advanced onset of mitosis" synonyms to FYPO:0001053 and FYPO:0001052 respectively.

**Comment by ValWood** [comment]
is this done?
Mitotic catastrophe annotations have gone from ~10 to ~92 after the  recent rearrangement which is good. We can probably close this and open new tickets if required?

**Comment by mah11** [comment]
I hadn't added the synonyms from the last pre-today comment, but it's done now. Happy to use new tickets for any follow-up.

edit file: f61dc6f71d82bb75c80fbb35b46236faeba4c9f7
release: 07ec1de988ca92662aea3748298d50f83930ad92
