### ISSUE TITLE
decreased mating after entry into the stationary phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3197]
PMID:28160081
PMID:25204792

**Comment by ValWood** [comment]
normal mating efficiency after entry in stationary phase PMID:25204792

**Comment by mah11** [comment]
decreased mating efficiency during stationary phase FYPO:0006331
normal mating efficiency during stationary phase FYPO:0006332

reasons for these names:
- both terms use "mating efficiency" because that's what they measured (consistent with our existing defs and comments)
- we have not used "after entry into x" wordings for any other "during x" terms

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947
