### ISSUE TITLE
decreased RNA level during cellular response to zinc ion  starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3199]
| decreased RNA level during cellular response to zinc ion  starvation

synonym decreased RNA level during cellular response to zinc ion  limitation

descendant of
FYPO:0001546 | decreased RNA level during cellular response to zinc ion | Microscopy |   | starvation

PMID:25204792

**Comment by mah11** [comment]
decreased RNA level during cellular response to zinc ion starvation FYPO:0006334

note: "during response to x starvation" terms are not generally is_a ""during response to x" terms, for consistency with GO (and because in starvation there's no x there to respond to)

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947

**Comment by ValWood** [comment]
should

FYPO:0006334 | decreased RNA level during cellular response to zinc ion starvation

be a descendant of


FYPO:0001546 | decreased RNA level during cellular response to zinc ion


it isn't...

**Comment by mah11** [comment]
No; the explanation is in my previous comment.
