### ISSUE TITLE
subtelomeric vs telomeric heterochromatin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3229]
we seems to refer to the telomeri/subtelomeric heterochromatin interchangably as telomeric/subtelomeric. I think we should always call it "subtelomeric" because it is really subtelomeric (it isn't the telomere proper)...and add telomeric as synonyms.

**Comment by mah11** [comment]
I have had a note-to-self kicking around since the time of ticket #1774 reminding me to make FYPO consistent with any changes that GO makes to its CC and BP (*chromatin organization) terms, because at present our "telomeric heterochromatin" and "subtelomeric heterochromatin" FYPO terms point to different existing GO terms.

If you are sure that GO's "telomeric heterochromatin" are not relevant to fission yeast I can stop waiting for GO to sort their terms out, and use only their "subtelomeric heterochromatin" terms.

**Comment by ValWood** [comment]
I think we should use "subtelomeric heterochromatin" for everything. Pombe people  use "telomeric heterochromatin and sub telomeric interchangeably, but they are always referring to the same thing. I'm not convinced that there is heterochromatin at the telomere proper (I don't think it has H3-K9 methylation which is heterochromatin hallmark).

**Comment by mah11** [comment]
OK, thanks. Should I also change plain "subtelomere" to "subtelomeric heterochromatin" generally?

**Comment by ValWood** [comment]
I think that would work... except that in stress  situations it is expressed to I guess then it's not heterochromatin.... tricky...

**Comment by mah11** [comment]
What I could do is keep a "yada at subtelomeric heterochromatin" is_a "yada at subtelomere" arrangement for any "yada" where we already have both, because that wouldn't be wrong. I can also make sure we have both for high-level things like "protein localization to" and "protein modification at".

Want that structure?

**Comment by ValWood** [comment]
That sounds OK!

**Comment by mah11** [comment]
as it turned out, I didn't find any cases where we needed both "subtelomere" and "subtelomeric heterochromatin", tho the option remains available if we do need it later

done in 
edit file: 2e218b650eea4f04511a384f09c2647f50e37359
release: f82be3da1840cab25009367319804f14ec826fe2
