### ISSUE TITLE
add synonym to nuclear envelope protrusion terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3251]
nuclear envelope deformation
(various flavours)

**Comment by mah11** [comment]
what does "various flavours" mean?

**Comment by ValWood** [comment]
Include "ER" terms for searching. I usually type "ER" and "endopl. ret." terms don't always seem to show

**Comment by mah11** [comment]
I'm confused now. Usually we only use ER as an abbreviation when we're referring to the parts of the endoplasmic reticulum that aren't nuclear envelope.

The part of the original ticket that made sense was the request for "nuclear envelope protrusion" to have "nuclear envelope deformation" as a synonym - which will be related, because "deformation" could cover more of the stuff under "abnormal morphology" than just protrusions. There wasn't anything about the rest of the ER.

**Comment by ValWood** [comment]
I think I added the comment to the wrong ticket!

**Comment by ValWood** [comment]
Oh no,  this just means to all the "nuclear  envelope protrusion terms"

**Comment by mah11** [comment]
oh, then it's redundant with "term**s**" in the summary

**Comment by mah11** [comment]
done

edit file: 092e56b5c3ab9a32e4450de0a8287e92d03658bd
release: 61932ede42e2740ae48af70a5ac53ccba20848b2
