### ISSUE TITLE
MP decreased cytoplasmic translational initiation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3262]
I don't see as a descendant of
decreased translation?

**Comment by mah11** [comment]
I'll have to assert that manually, because reasoning doesn't infer is_a in FYPO from part_of in GO. I didn't do it before because I'm not entirely sure it's biologically and ontologically optimal, but I can look at it as a reasonable compromise for improved searching.

edit file: dcfbacedfa48ea3e1ca957f71e1766e36d3b2838
release: 1f6d41e3adba95f410a59a4e7ae56538f3e7a40b
