### ISSUE TITLE
	PMID:11854409 exocyst

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3301]
tetranucleate with three septa

this might seem a bit specific, but this is the 'precidse' phenotype for a cell separation after cyokinesis/ septum disassembly  defect

(the cell undergoes precisely 2 rounds of cell division, with normally spaced septa)

child of

FYPO:0001253 | elongated multinucleate multiseptate vegetative cell, single septa between nuclei

(one day will move many exisitng down to this precise term)

**Comment by ValWood** [comment]
also





FYPO:0000117 | abnormal septation
-NEW abolished cell separation during septation
-- NEW abolished septum disassembly 

(possibly these are the same thing? septum disassembly id how cells separate?)

**Comment by mah11** [comment]
> -NEW abolished cell separation during septation
> -- NEW abolished septum disassembly

It seems to me that one is the consequence of the other - the septum doesn't get disassembled, and as a result daughter cells stay stuck together. I could add both terms, with has_output to link them, if you want.

**Comment by ValWood** [comment]
Yeh if you put both it should be clear.

**Comment by mah11** [comment]
new terms
  elongated tetranucleate triseptate vegetative cell, single septa between nuclei FYPO:0006556
  abolished cell separation after cytokinesis FYPO:0006557
  abolished septum disassembly FYPO:0006558

edit file: 0d9e0cf1388de76dd0c1197d2d475644171376f4
release: 2a1e2b5b008beb8d4f2a80b2801b314cba9770f3

**Comment by ValWood** [comment]
can FYPO:0001253 | elongated multinucleate multiseptate vegetative cell, single septa between nuclei
be defined as an inviable phenotype?


can FYPO:0006558 be a descendant of abnormal septation?

**Comment by mah11** [comment]
> can FYPO:0001253 | elongated multinucleate multiseptate vegetative cell, single septa between nuclei
be defined as an inviable phenotype?

Maybe - as usual, yes if and only if no cell ever survives once it shows this phenotype.

I haven't put it under inviable before now because I have used the term in cases where I couldn't tell whether the affected cells were viable or not, but that could just be my lack of pombe background. (In some cases, the population is viable, but that could be due to incomplete penetrance of the FYPO:0001253 phenotype.)


> can FYPO:0006558 be a descendant of abnormal septation?

No, at least not as the terms are currently defined (text and logical defs), because the "septation" FYPO terms point to GO:0000917 ! division septum assembly. Septum disassembly follows septum assembly; both are parts of cell division in GO, but only septum assembly is part of cytokinesis.

**Comment by ValWood** [comment]
Sorry wrong term

elongated tetranucleate triseptate vegetative cell, single septa between nuclei FYPO:0006556

is a terminal phenotype, I can't be sure about the others

**Comment by ValWood** [comment]
can we rename
"abnormal septation" to "abnormal division septum assembly" then? This would be clearer...

**Comment by mah11** [comment]
> FYPO:0006556 is a terminal phenotype, I can't be sure about the others

OK, done as inviable

> can we rename "abnormal septation" to "abnormal division septum assembly" then?

I've gone with "septum assembly" in names, because pombe doesn't have any other kind of septum. The terms already had exact synonyms using "division septum assembly", and I've made the "septation" wordings broad synonyms, consistent with GO.

edit file: 7a3d4650295c9575e9839b38a8229b6f99ddfdde
release: 28405c8014039cb0b94a78744dc18c6d3a97107c
