### ISSUE TITLE
pcb1 terms  PMID: 19942852

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3320]
1.
monopolar mitotic spindle, nucleated from old SPB
descendent of
FYPO:0000276 | monopolar mitotic spindle

2.
decreased microtubule nucleation from mitotic SPB
descendent of
FYPO:0006336 decreased mitotic microtubule nucleation

3.
normal gamma tubulin complex localization to mitotic spindle pole body

4.
abnormal nuclear membrane invagination
FYPO:0001013 | abnormal membrane organization
descendant of 

5. Abnormal mitotic SPB insertion into nuclear membrane

I think that's it.

How would you normally annotate 
"loss of viability upon mitotic entry"

I'm brain dead today.....

**Comment by ValWood** [comment]
no ignore. I was trying to capture that the cells die over a couple of generations but it isn't important.

Its one of those where there is a small subset of cells that's OK in the first round. Here it's clearly to do with the residual proteins at the existing spb.

**Comment by mah11** [comment]
another question, for this one

> abnormal nuclear membrane invagination

Is there a normal process for this to refer to? There's no GO BP term by the name "nuclear membrane invagination". Does there even need to be a separate phenotype term in addition to the abnormal SPB insertion term?

**Comment by ValWood** [comment]
No, I don't think it needs to be a separate process. I nearly didn't request it...

**Comment by mah11** [comment]
OK, but if there's no separate process, how should the phenotype term be defined? Or should I omit that one?

**Comment by ValWood** [comment]
yep, I think the insertion phenotype is enough. 

the term has a nuclear membrane organization defective parent anyway IIRC....

**Comment by mah11** [comment]
monopolar mitotic spindle nucleated from old spindle pole body FYPO:0006592
  decreased mitotic spindle microtubule nucleation from spindle pole body FYPO:0006593
  normal gamma-tubulin complex localization to mitotic spindle pole body FYPO:0006594
  abnormal mitotic spindle pole body insertion into nuclear envelope FYPO:0006595

I used "spindle microtubule" in FYPO:0006593 because that's what the text accompanying figures 1 & 2 says, and the added specificity was necessary for the new term's parentage not to clash with FYPO:0006337.

I'll add a logical def for FYPO:0006595 when the GO ticket settles down.

edit file: e9eb211633d007d552a03ede3069c10c0e7f3ca0
release: 775c5d9aa382ebbf049ef15dd0952f3da4b372bf
