### ISSUE TITLE
abolished protein localization to nucleus of opposite mating type cell PMID:30089908

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3359]
I forgot this for
PMID:30089908

**Comment by ValWood** [comment]
also

abolished gene expression  in M cells

**Comment by ValWood** [comment]
should
FYPO:0000678 | unequal homologous chromosome segregation

have related synonym aneuploidy?

**Comment by mah11** [comment]
> abolished protein localization to nucleus of opposite mating type cell

To avoid suggesting that the localization normally happens between separate cells, would this slight rejig work?

name: abolished protein localization to mating partner nucleus in zygote
def: A cellular process phenotype observed during mating in which the localization of a protein produced by one cell to the nucleus of its mating partner (i.e. of the opposite mating type) does not occur. Such protein localization normally occurs after cell fusion but prior to karyogamy.

> abolished gene expression in M cells

If it's at all possible, I would much prefer to do this by putting the M cell (h-) info in the genotype instead of the phenotype term. Right now it'll have to go in the background (in https://github.com/pombase/canto/issues/1014 we agreed that would do for a while), so maybe we should revisit the question of allowing h+/h-/h90 as "foreground" alleles.

> should FYPO:0000678 [snip] have related synonym aneuploidy?

It might as well; it's already a related synonym for a couple of the mitotic terms but another won't hurt. They are all ways aneuploidy could arise.

**Comment by ValWood** [comment]
>name: abolished protein localization to mating partner nucleus in zygote

yep

> If it's at all possible, I would much prefer to do this by putting the M cell (h-) info in the genotype instead of the phenotype term. Right now it'll have to go in the background 

ok i can do that

**Comment by mah11** [comment]
done; new term is
  abolished protein localization to mating partner nucleus in zygote FYPO:0006685

edit file: 186769f12d6c0b85492b700abe9d5bae4843ae5c
release: 8c59a4d07cde37fd310986b6f87ce1097b1507c9
