### ISSUE TITLE
ntr: PMID:29689193 cell wall thickness homeostasis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3376]
fig 5 A-F

PMID:29689193
Title | Mechanosensation Dynamically Coordinates Polar Growth and Cell Wall Assembly to Promote Cell Survival.

**Comment by ValWood** [comment]
A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which the fungal-type cell wall thickness homeostasis is abolished resulting in cells with cell walls thicker or thinner than normal.

**Comment by ValWood** [comment]
i.e mixed population. Maybe this is a population phenotype?

**Comment by ValWood** [comment]
what means "thickness or thiness"  cell wall width? (sounds odd though)

**Comment by ValWood** [comment]
add synonym to
old end
 | decreased cell wall thickness at growing end during vegetative growth
-

**Comment by ValWood** [comment]
ntr: 

decreased cell wall thickness at cell tip during vegetative growth

child of

FYPO:0002163 | decreased cell wall thickness during vegetative growth

**Comment by mah11** [comment]
Because they make dynamic observations of the same cells over time, there's no problem using a process phenotype term (though you could optionally also annotate to terms in the abnormal wall morphology branch). There's still some work to do, though, if you want something other than abnormal cell wall biogenesis.

If you want the phenotype to refer to "cell wall thickness homeostasis", it has to be defined as a biological process. At present there is no GO term for it. To get one, you would have to specify a definition, especially how it is distinct from any other type of cell wall organization or biogenesis.

Even with a cell wall homeostasis process term, I'm not comfortable calling it "abolished" - wall organization is clearly abnormal in the mutants, but I really don't know how one could specifically observe "no homeostatic process taking place" as distinct from "homeostatic process going, but badly".

**Comment by mah11** [comment]
> add synonym
> for "old end"
> to
> decreased cell wall thickness at growing end during vegetative growth

I don't understand this one - there is no term named "decreased cell wall thickness at growing end during vegetative growth".

**Comment by ValWood** [comment]
sorry
add 
synonym 
decreased cell wall thickness at growing end during vegetative growth
to
FYPO:0003889 | decreased cell wall thickness at old end during vegetative growth

**Comment by ValWood** [comment]
I'll just do
abnormal cell wall thickness during vegetative growth
for these...

**Comment by ValWood** [comment]
but I need a term for that....

**Comment by mah11** [comment]
OK. The synonym makes more sense now, but can't be exact because the new end will eventually also become a growing end.

**Comment by ValWood** [comment]
yeah. It just seemed overkill to have another term for old end...

**Comment by mah11** [comment]
OK, I think I got the actual things-to-do; new terms are:
  abnormal cell wall thickness during vegetative growth FYPO:0006745
  decreased cell wall thickness at cell tip during vegetative growth FYPO:0006746

edit file: 024ce4890acf3f5f26e9ccd7525e95f8aacb0d26
release: c38c34e27020529fbfe08feb17b8451ebf4cfbda

**Comment by ValWood** [comment]
yep


FYPO:0003889 | decreased cell wall thickness at old end during vegetative growth
can be a child of
FYPO:0006746

**Comment by mah11** [comment]
link added
edit file: 2dace453f9873877f85d41b8d6655197dbf97d81
release: 7999444235838e46ccf3b36375ce3311604803ab
