### ISSUE TITLE
NTR: abnormal localization to both SPB during mitotic anaphase B

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3416]
descendant of 

FYPO:0006640 | abnormal protein localization to mitotic spindle pole body during anaphase B

Not sure how to word this but in the WT  dma1 localizes asymmetrically to on;y one SPB. In the mutant it localizes to both.
worth capturing.... (B vs E)

![both](https://user-images.githubusercontent.com/7359272/52166737-1579bf00-2709-11e9-82e8-d7d5dfc18e9f.jpg)

**Comment by mah11** [comment]
This sounds like FYPO:0001876 ! decreased asymmetric protein localization to old or new mitotic spindle pole body during anaphase, with protein symmetrically localized to both spindle pole bodies.

- Will this do, or should I add a new term specific for anaphase *B*?
- Would it help to swap round so the 'abnormally symmetric protein localization' is the term name instead of a synonym?

**Comment by ValWood** [comment]
No that's the one. I wonder why I couldn't find it.........
