### ISSUE TITLE
NTR: decreased protein localization to cell cortex during meiotic prophase I

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3439]
child of 
FYPO:0000928 | abnormal protein localization to cell cortex

decreased protein localization to cell cortex during meiotic prophase I
synonym decreased protein localization to cell cortex during in zygote

ref
PMID:28292899

**Comment by mah11** [comment]
abnormal protein localization to cell cortex FYPO:0006867 (FYPO:0000928 is 'vegetative', now explicit in its name)
  decreased protein localization to cell cortex during meiotic prophase I FYPO:0006868

synonym is related because 'zygote' is broader than 'prophase I'

edit file: 01395f5f57543ab4fa25ab90630158a963daf505
release: 6a27a43c29768356dcf4af581cabcd42c7b17158

**Comment by ValWood** [comment]
I dont see this under 
abnormal protein localization to cell cortex FYPO:0006867?

**Comment by mah11** [comment]
I do (which makes sense, as the link is asserted).
