### ISSUE TITLE
NTR inviable after spore germination, multiple cell divisions, cell lysis during cytokinesis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3443]
inviable after spore germination, multiple cell divisions, cell lysis during cytokinesis

parents
XXXXXXXXXXXX inviable after spore germination, multiple cell divisions
and
FYPO:0003440 | cell lysis during cytokinesis

make a common parent for new term &
inviable after spore germination, multiple cell divisions, with abnormal cytokinetic cell separation and increased septum thickness  

(I suspect they are the same or related so good to have a grouping)

**Comment by mah11** [comment]
inviable after spore germination, multiple cell divisions, cell lysis during cytokinesis FYPO:0006877
inviable after spore germination, multiple cell divisions, with abnormal septation FYPO:0006878

FYPO:0003971 was created for the gpi1 disruption in PMID:9046095. I admit that similarity between it and the new term doesn't jump out at me, but maybe that's due to limitations of older microscopy.

I also had to guess at what you wanted for the common parent; reopen if you had something different in mind.

edit file: 2a736df11cb4a1235a331761aa20a2d40cdd3f79
release: c6bb70640c22d92a2fafb32d18a7329d277aaf44
