### ISSUE TITLE
PMID:30044717 normal membrane closure during cytokinesis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3444]
normal cleavage furrow ingression

**Comment by mah11** [comment]
normal cleavage furrow ingression FYPO:0006879

It's not clear whether the ticket title is a request for a separate term or a synonym, but I've just added the one new term because it has a corresponding GO BP.

edit file: 2a736df11cb4a1235a331761aa20a2d40cdd3f79
release: c6bb70640c22d92a2fafb32d18a7329d277aaf44
