### ISSUE TITLE
PMID: 9755190

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#3446]
increased chromatin silencing at centromere central core
decreased chromatin silencing at centromere central core

**Comment by mah11** [comment]
FYPO:0003217 and FYPO:0005315 used to have these names (and text & logical defs), but they were changed after Val argued that chromatin silencing does not occur at the centromere central core - GO:0072692 was  made obsolete. See #2904 and the GO ticket linked there.

I have now improved the asserted parents for these terms - they should have been moved but weren't.

edit file: 2a736df11cb4a1235a331761aa20a2d40cdd3f79
release: c6bb70640c22d92a2fafb32d18a7329d277aaf44

**Comment by ValWood** [comment]
"silencing at the central core" doesn't really make sense as a GO term, because there are no genes to silence here. The phenotype  observation is from the insertion  of a marker gene is OK to have "silencing at the central core" but it would need to be logically defined as "GO:silencing occurs_at "central core". t's an artificial situation...

**Comment by Antonialock** [comment]
Thanks. Can we add the requested terms as synonyms if theses are the ones we should use in this case. 

I agree it is an artificial situation, because there isn't normally a gene there, but there is obviously something wrong in these mutants.

**Comment by ValWood** [comment]
Yes we should be able to have the phenotype even if the GO term doesn't exist.

**Comment by mah11** [comment]
> Can we add the requested terms as synonyms

The synonyms have been there since the terms were renamed for #2904.

**Comment by ValWood** [comment]
if I search on
increased chromatin silencing at centromere central core
I only find
normal chromatin silencing at centromere central core?

**Comment by mah11** [comment]
I'll fix that term name, but search behavior is not an ontology issue.

**Comment by ValWood** [comment]
I see, it is called
increased transcriptional repression at centromere central core?

**Comment by ValWood** [comment]
chromatin silencing is a better term name

**Comment by mah11** [comment]
The *entire point* of #2904 was to stop using "chromatin silencing at centromere central core" in term names.

**Comment by ValWood** [comment]
The point was to not instantiate "chromatin silencing at centromere central core" in GO.

but chromatin silencing can be increased or decreased at the core as a phenotype.

To say 

"transcriotion is repressed ar the core" in GO  is wrong, because transcription doesn't normally occur here.

the phenotype term can exist,  but would need to be logically defined using  "chromatin silencing" and "GO:0000939    "condensed chromosome inner kinetochore" 

that's why I said "I think the original term is OK."
