### ISSUE TITLE
tRNA modification levels

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3494]
trm7 delta

 2′-O-methylcytidine level in tRNA ~reduced~ abolished/ Cm
 2′-O-methylguanosine level in tRNA ~reduced~ abolished / Gm 
 1-methylguanosine level increased /m1G increased
normal  pseudouridine    level in tRNA
 7-methylguanosine in tRNA reduced/ m7G  reduced
 N2- methylguanosine in tRNA reduced / m2G  reduced

....that was a learning curve...

**Comment by ValWood** [comment]
trm732

2′-O-methylguanosine level in tRNA normal/ Gm
7-methylguanosine in tRNA normal / m7G 
N2- methylguanosine in tRNA rnormal / m2G

note to self (as above)
 2′-O-methylcytidine level in tRNA reduced/ Cm reduced
1-methylguanosine level increased /m1G increased
normal pseudouridine level in tRNA

**Comment by ValWood** [comment]
trm734
2′-O-methylcytidine level in tRNA norma/ Cm

note to self (as above)
2′-O-methylguanosine level in tRNA reduced abolished / Gm
1-methylguanosine level increased /m1G increased
normal pseudouridine level in tRNA
7-methylguanosine in tRNA reduced/ m7G reduced
N2- methylguanosine in tRNA reduced / m2G reduced

**Comment by ValWood** [comment]
PMID:25404562

**Comment by ValWood** [comment]
one more 
decreased wybutosine formation (yW)

**Comment by mah11** [comment]
We have done almost all phenotypes for modified residues in tRNA as normal/increased/decreased etc. modification process phenotypes (the exception is queuosine, which a bit of an oddball but maybe should be changed to match the rest).

So I'll do these as process phenotypes too, for consistency (also, "abolished level" makes no sense). They can have "x level in tRNA" phrases as related synonyms.

Can you check this list to make sure it's complete? It can be a bit challenging to make sure I've cribbed everything from all the comments; a single comprehensive list is easier to use.

abolished tRNA cytosine 2'-O-methylation (additional synonym: abolished tRNA 2'-O-methylcytidine formation, and similar for the rest)
abolished tRNA guanosine 2'-O-methylation
increased tRNA guanosine 1-methylation (add'l syn: N1-methylation)	GO:0002939
normal tRNA pseudouridylation	GO:0031119
decreased tRNA guanosine 7-methylation	GO:0106004
decreased tRNA guanosine N2-methylation	GO:0002940
normal tRNA guanosine 2'-O-methylation
normal tRNA guanosine 7-methylation
normal tRNA guanosine N2-methylation
decreased wybutosine biosynthesis	GO:0031591

**Comment by ValWood** [comment]
I think that's all of them but I don't see them in canto yet?

**Comment by mah11** [comment]
normal tRNA pseudouridylation FYPO:0007017
  normal tRNA guanosine 2'-O-methylation FYPO:0007018
  normal tRNA guanosine 7-methylation FYPO:0007019
  normal tRNA guanosine N2-methylation FYPO:0007020
  abolished tRNA cytosine 2'-O-methylation FYPO:0007021
  abolished tRNA guanosine 2'-O-methylation FYPO:0007022
  increased tRNA guanosine 1-methylation FYPO:0007023
  decreased tRNA guanosine 7-methylation FYPO:0007024
  decreased tRNA guanosine N2-methylation FYPO:0007025
  decreased tRNA wybutosine biosynthesis FYPO:0007026

edit file: 4f3372764e0e885ec97cf4417808e8d47a70623e
release: b433bc3c036054f6a8b57b3e72e865df4d60549b

> but I don't see them in canto yet?

I always include the above information (term names & IDs, and the github links) when new terms go in. If you don't see new FYPO IDs in a ticket, you won't see the terms in Canto because they haven't actually been added yet. This has been true for as long as FYPO has existed.
