### ISSUE TITLE
NTR: normal growth on MPA

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3519]
normal growth on MPA (we have sensitivity term)  PMID:22508988

and a question. Is there a grouping term for chemical sensitivities ? When I could not find this I was looking for 
normal growth on drug/chemical etc to hang the term request on...

**Comment by mah11** [comment]
> Is there a grouping term for chemical sensitivities ?

FYPO:0000126 ! increased resistance to chemical during vegetative growth
FYPO:0000127 ! increased sensitivity to chemical during vegetative growth

but the "normal growth" terms don't have a "normal growth in presence of some chemical" parent because I don't know how I would define it logically to make a clear distinction from FYPO:0001357 ! normal vegetative cell population growth (which is the parent of the "normal growth on X" terms).

**Comment by mah11** [comment]
normal growth on mycophenolic acid FYPO:0007074

edit file: 51d2fa0213b2f4cacab19ad8df262b67c74ef2fa
release: 53940dd86555e65ec07901c5ed8e36a0a1cc9ee1
