### ISSUE TITLE
PMID:31615768 /microtubule bundling

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3549]
I missed

normal microtubule spindle bundling in mitotic prophase

**Comment by mah11** [comment]
"spindle bundling" isn't a process. Does this mean "normal microtubule bundling during spindle assembly"?

**Comment by ValWood** [comment]
yes!

**Comment by mah11** [comment]
I used this as the term name:
  abnormal microtubule bundle formation during mitotic spindle assembly FYPO:0007126

and put "prophase" in a related synonym because the paper text refers to "pre-anaphase", which is a bit broader (although I guess not much bundling happens in metaphase). Reopen this if it needs any adjustments.

edit file: f623968cf338deb197a749ed344b11922bde331f
release: 22a37036cb982537b07873689c6932f2397082a6
