### ISSUE TITLE
2 terms need to be connected

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3582]
This phenotype

  | 5 | abnormal chromosome segregation during meiosis I with split kinetochore and normal chromosome separation (FYPO:0005633) [single allele genotypes]

indicates

3 | decreased meiotic sister chromatid cohesion at centromere during meiosis I (FYPO:0006423) [single allele genotypes] | ...

basically 
" In moa1Δ cells, although a small population of cells underwent equa- tional segregation at meiosis I (because of defects in mono-orientation), the majority underwent reduc- tional segregation due to the presence of chiasmata and tension exerted across homologues (Fig. 1B). Strik- ingly, 22% of these ‘reductional’ moa1Δ cells showed the separation of imr1-GFP in prometaphase II (Fig. 1C). This separation value is significantly higher than in wild-type cells (<5%), although lower than in sgo1Δ cells (50%), in which cohesion protection is completely abolished (Fig. 1C). "

i.e the chromosomes do normal equational division because of chiasmata, but then "fall apart" 
because of a lack of centromeric cohesion

How can we connect (or even merge) them?

**Comment by ValWood** [comment]
add synonym exact
decreased centromeric cohesion protection
to FYPO:0006423

**Comment by ValWood** [comment]
Actually this definition /term is a bit strange


abnormal chromosome segregation during meiosis I with split kinetochore and normal chromosome separation
A cellular process phenotype in which kinetochores become separated during the first meiotic nuclear division, and in which homologous chromosomes are separated normally.

The homologous chromosome *segregate* normally

So that would be
 split kinetochore in meiosis I with  equational  *homologous chromosome segregation*

**Comment by ValWood** [comment]
Ignore this one for now, I will update later today based on Yoshis comments.

**Comment by ValWood** [comment]
The phenotype is described by Yoshi as:

Abnormal chromosome segregation during meiosis II because of centromeric protection defects during meiosis I

Does that help

**Comment by mah11** [comment]
> FYPO:0005633 indicates FYPO:0006423 ...
> How can we connect (or even merge) them?

If -- but *only* if -- the decreased cohesion represented by FYPO:0006423 is the only problem that can give rise to the segregation phenotype of FYPO:0005633, then we can add an "output" link (FYPO:0005633 output_of FYPO:0006423).

But before I do, please have a look at [this comment](https://github.com/pombase/fypo/issues/2735#issuecomment-232363966) from #2735 -- at that time, it looked like there might be more than one way to get sister chromatid separation in meiosis I. Is that still a concern?

> The homologous chromosome *segregate* normally

No, they separate normally. Remember that GO BP defines segregation as the entire process, including chromosome condensation, cohesion, metaphase plate congression, etc. as well as separation. We discussed this at length in #2782 and #2783 (especially [this comment](https://github.com/pombase/fypo/issues/2782#issuecomment-242401727), [this one](https://github.com/pombase/fypo/issues/2789#issuecomment-242391280), and [this one](https://github.com/pombase/fypo/issues/2782#issuecomment-242418031)).

> So that would be
> split kinetochore in meiosis I with equational homologous chromosome segregation

No, as above; in addition, equational segregation is *not* normal in meiosis I (it's normal in mitosis and meiosis II). Reductional segregation is normal for meiosis I. Also see FYPO:0005634, including the comment.

> The phenotype is described by Yoshi as:
> 
> Abnormal chromosome segregation during meiosis II because of centromeric protection defects during meiosis I
> 
> Does that help

Sorry, no; if anything, it's more confusing now because everything prior to this comment mentions only meiosis I, and now this one brings up meiosis *II* as well.



note to self: change FYPO:0005633 name to avoid "split kinetochore" confusion; the comment even implies that's already been done!

**Comment by ValWood** [comment]
centromeres are protected by cohesion in meiosis I  so that they segregate normally in meiosis II.

Here the protection in meiosis I is abnormal (kinetochores separate in meiosis I). 
segregation at I (migration to the poles) was normal

however the lack of protection in meiosis I 
 results in unequal segregation of sister chromatids in meiosis II -

**Comment by mah11** [comment]
> Here the protection in meiosis I is abnormal (kinetochores separate in meiosis I).

Then not all of segregation was normal.

> segregation at I (migration to the poles) was normal

*Separation* in meiosis I was normal.

> however the lack of protection in meiosis I

To clarify: "protection" is a (slightly woollier) way of saying "sister chromatid cohesion"?

> results in unequal segregation of sister chromatids in meiosis II -

OK, that's clearer in and of itself now. But I'm still a little hazy as to what it has to do with the initial summary for this ticket, since the two terms there only say anything about meiosis I.

**Comment by ValWood** [comment]
Let's forget about the connection part for now.

I thought that separation referred to the release from the connection between chromosomes/chromatids (i.e cleavage cohesion) , and segregation was  subsequent movement toward  the poles?


I guess   "protection" is the :maintenance of centromeric  sister chromatid cohesion"?
(the centromeric cohesion is actively maintained although the arms are cleaved)

**Comment by ValWood** [comment]
correction
I thought that separation referred to the release from the connection between chromosomes/chromatids (i.e cleavage cohesion) , and segregation was separation plus subsequent movement toward the poles?

**Comment by mah11** [comment]
> and segregation was separation plus subsequent movement toward the poles?

see [above](https://github.com/pombase/fypo/issues/3582#issuecomment-563211889) ... or just look at GO

**Comment by ValWood** [comment]
separation:

chromosome separation
Biological Process

Definition (GO:0051304 GONUTS page)
The cell cycle process in which paired chromosomes are detached from each other. Chromosome separation begins with the release of cohesin complexes from chromosomes; in budding yeast, this includes the cleavage of cohesin complexes along the chromosome arms, followed by the separation of the centromeric regions. Chromosome separation also includes formation of chromatid axes mediated by condensins, and ends with the disentangling of inter-sister catenation catalyzed by topoisomerase II (topo II). PMID:20352243

**Comment by ValWood** [comment]
separation in meiosis I is abnormal because cohesin is cleaved at the centromeres and it  shouldn't be.

Segregation is also abnormal I guess *because* separation is part_of segregation. But separation is more accurate.

Segregation at meiosis II is abnormal (unequal)

**Comment by mah11** [comment]
> Segregation is also abnormal I guess because separation is part_of segregation.

Correct. That's why I can't put "normal segregation" in the names of terms like FYPO:0005633. But if "normal separation" includes the correct timing of cohesin cleavage, I should change "normal separation" to something else. "Reductional chromosome apportionment" would be accurate but unwieldy. I could use "normal outcome of chromosome separation", unless you think of something better.

**Comment by ValWood** [comment]
Can't we say
FYPO:0005633
"split kinetochore during meiosis I leading to unequal chromosome segregation at meiosis II?

**Comment by mah11** [comment]
I don't like it much.

1. In FYPO, terms with "split kinetochore" in the names now represent cases where a single kinetochore gets broken into parts (tho I only got round to mopping up FYPO:0005633 yesterday). For " premature sister kinetochore separation" terms, "split kinetochore" goes in related synonyms.

2. I'm really leery of building "leading to" into term definitions. It seems like there's a high risk of doing it wrongly, so as to create dodgy inferences. I could run the idea by @matentzn when he's back ... phenotype A leads to phenotype B is a challenge even when A and B are separate ontology classes.

**Comment by mah11** [comment]
oh, and 3. FYPO:0005633 has never had the faintest hint of meiosis II about it until now, so even if the "leading to" problem can be solved, is it really safe to rejig the existing term?

**Comment by mah11** [comment]
tangential note to self: open ticket to change terms added for #3290 - they're premature separation

**Comment by ValWood** [comment]
In FYPO, terms with "split kinetochore" in the names now represent cases where a single kinetochore gets broken into parts (tho I only got round to mopping up FYPO:0005633 yesterday). For " premature sister kinetochore separation" terms, "split kinetochore" goes in related synonyms.

Great, I was just about to suggest we change this.  I had already checked that all the annotations referred to the phenotype I tried to describe here.
The authors call it split kinetochore so could this be a related synonym.

so
>is it really safe to rejig the existing term?

yes. The other annotations are a single paper from Yoshi.

Could we do:

"premature kinetochore separation during meiosis with unequal chromosome segregation at meiosis II?

(so its two observations which occur in the same cell.  We  can lose the dependency)

**Comment by mah11** [comment]
OK, I used

premature sister kinetochore separation and normal chromosome division in meiosis I, and unequal sister chromatid segregation in meiosis II

and put your text in as an exact synonym


edit file: 48bb20dca3bc5c96c788dee0894d8586ea0770c6
release: 3d6d8217e41d38e07e812c7f918f3ea4487460dd
