### ISSUE TITLE
heterochromatin island stuff PMID:31269446

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3601]
1. decreased chromatin silencing at heterochromatin island GO:1990342
2. decreased histone H3-K9 dimethylation at heterochromatin island during vegetative growth (cf 6373)
~3. increased level of metabolism gene mRNA during vegetative growth~ decided against - see bolew
~4. increased level of stress response gene mRNA during vegetative growth~ add synonym to FYPO:0002664 instead
5. abolished protein localization to chromatin at heterochromatin island
6. abolished protein localization to chromatin at lncRNA gene SO:0002127

**Comment by ValWood** [comment]
How would "metabolism" be defined here?
75% of pombe  processes map to GO metabolism...

**Comment by mah11** [comment]
Regrettably, the paper does not say anything more specific, so it's 'metabolism' as in GO or leave it out (I'm not wedded to including fypo:new3; it just felt a little odd to have new4 but not new3; anyway, fig 3D).

(also, fixed PMID in ticket title ...)

**Comment by ValWood** [comment]
Yeah I would leave out that one.
The meiosis/stress response/ metabolism sets are largely overlapping. These seem  mainly to be stress response genes. 

In fact of the 2  examples  they provide, one is
SPAC2E12.03c
Gene standard name
Characterisation status
biological role inferred
Product
plasma membrane basic amino acid transmembrane transporter (predicted)
(so not metabolism, per se)

and the other is a sub telomeric 
https://www.pombase.org/gene/SPAC11D3.09
(a known stress induced gene)

So this isn't really "core metabolism", although I could not see how they defined their "metabolism" set

I think it's fine only to have the stress response one because it's more meaningful and more precise.

In fact, if I interpreted correct;y this is just mean expression increase of 3 pre-selected catagories . Looking at the plots  the  metabolism mirrors the stress plot, but  the stress plot is much more significant ? It is likely that this   represents  the fact that  a large proportion of the stress genes are also annotated to metabolism.

Based on this, I don't have a problem representing only  the stress and meiosis related increases.

**Comment by mah11** [comment]
new terms
  decreased chromatin silencing at heterochromatin island FYPO:0007212
  decreased histone H3-K9 dimethylation at heterochromatin island during vegetative growth FYPO:0007213
  abolished protein localization to chromatin at heterochromatin island FYPO:0007214
  abolished protein localization to chromatin at lncRNA gene FYPO:0007215
synonym FYPO:0002664

edit file: d2a77819c896c297edbd738a80dd6e27237267a3
release: 7ee10b209e4d7f44ac0bfe2995d335965070c50d
