### ISSUE TITLE
PMID:32023460 Zhang

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3631]
decreased number of eisosome filaments of increased length
decreased number of eisosomes

**Comment by ValWood** [comment]
decreased colocalization of tubular cortical ER with eisosomes
increased colocalization of tubular cortical ER with eisosomes

**Comment by ValWood** [comment]
decreased cortical ER remodelling
Dan put 
the cortical tubular ER pattern changes slower than wild type

This is about dynamic changes to the cortical ER over time.
Do we have any examples?

**Comment by mah11** [comment]
heh, those aren't gonna have logical defs!

**Comment by ValWood** [comment]
I thought not!

**Comment by mah11** [comment]
> This is about dynamic changes to the cortical ER over time.
> Do we have any examples?

Examples of what?

**Comment by ValWood** [comment]
"dynamic changes over time"

**Comment by mah11** [comment]
abnormal eisosome FYPO:0007262
  eisosomes present in decreased numbers FYPO:0007263
  long eisosome filament FYPO:0007264
  long eisosome filaments present in decreased numbers FYPO:0007265
  decreased colocalization of cortical endoplasmic reticulum with eisosomes FYPO:0007266
  increased colocalization of cortical endoplasmic reticulum with eisosomes FYPO:0007267
  decreased cortical endoplasmic reticulum remodeling FYPO:0007268

I put FYPO:0007266-7268 under abnormal endoplasmic reticulum organization (FYPO:0000805); let me know if a different parent would be better. Also, I put "tubular" in synonyms, because GO defines cortical ER as tubular.

Reopen if anything needs to be added or changed.

edit file: ecf7b035ec920c8a0e9ab5ae451caccb744f50ed
release: 252448fdc2c6a1b38d6dfc10b68077832b0b9a1c
