### ISSUE TITLE
chromatin silencing at central core PMID:12526748

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3650]
increased transcriptional repression at centromere central core
-> silencing to match others

also
decreased chromatin silencing at central core

**Comment by mah11** [comment]
The central core terms are different on purpose, per #2904. Could you look at that ticket again and check whether the reasoning there still holds? It does seem that if chromatin silencing reflects heterochromatin assembly, and the central core doesn't have heterochromatin, that it would still make sense for the central core terms not to be the same as the rest. But I don't have any preference as long as you've reviewed the older ticket and think this request explicitly supersedes it.

For 'decreased' see FYPO:0003217 - it's done the same way as the others, with "chromatin silencing" in a related synonym.

**Comment by ValWood** [comment]
There  is chromatin in the central core, but it is specialized chromatin (Cenp-A) not heterochromatin.

So chromatin is still 'silenced'
But it would not make sense to have a 'transcriptional silencing' GO term for this, *even when*  we had silencing terms. This is because this region is not transcribed  (AFAIK) because it is under the kinetochore. The outer repeats produce the RNA that makes the siRNA, so this was not so bad although it was still  not really regulating transcription per se.

These are definitely 'silencing assays' though. A gene is inserted, and  expressed or not expressed dependent on the disruption of  CENP-A containing chromatin

**Comment by mah11** [comment]
That was all true at the time of ticket #2904. Please clarify: do you now think the name change done for that ticket was an error?

**Comment by ValWood** [comment]
I thought the solution was to use

>Upon closer inspection of the GO silencing terms, it looks like I can use GO "negative regulation of transcription" and SO "centromere central core".

which would seem correct to logically define
"chromatin silencing at the chromosome central core"

I don't see  where the FYPO terms went?

**Comment by mah11** [comment]
In #3635 we agreed that "silencing" phenotype terms will not have logical definitions using GO BP terms, because silencing is a phenotype that reflects effects on a process of heterochromatin assembly, and that sounds more specific than "negative regulation of transcription".

As I said in my previous comments, the central core terms were renamed to use the "transcriptional repression" wording. Do you now wish to revert that change?

**Comment by mah11** [comment]
p.s. I think the older suggestion is now out of date, now that "silencing" won't be a GO process any more.

**Comment by ValWood** [comment]
I don't think I fully understood what was done previously.


I think the terms can have 
transcriptional repression at centromere central core
and still be called 'silencing' in the term names?

**Comment by ValWood** [comment]
In fact,  the definition could be more precise


Definition | Parents
-- | --
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the occurrence of negative regulation of transcription at the central core of the centromeric regions is increased.

Should be
 A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the occurrence of *constitutive repression* of transcription at the central core of the centromeric regions *effected by CENP-A containing chromatin* is decreased

transcription isn't really 'negatively regulated' in a biological sense  because repression is the default state? Transcription if it ocvcur needs to be activated. This phenotype destroys the repression.


Odd that we have "increased transcriptional repression at centromere central core"
though. I don't know how silencing at the central core can be increased from a WT default repressed state. I will look at those....

**Comment by mah11** [comment]
also see #2576 and #3446

**Comment by mah11** [comment]
Can we back up a bit? I think I've lost grip on some key things, with the various changes ...

What (if anything) distinguishes a "chromatin silencing" phenotype from other transcription regulation phenotypes?

Before the move to take silencing BP terms out of GO, it was simple: refer to silencing BP terms or other transcription regulation BPs as needed, and let GO take care of defining them all. Now we have to make the distinction clear in FYPO definitions.

I'm also now confused about whether we should still avoid saying there are specifically "silencing" phenotypes at the centromere central core - at the time of #2904 we thought we shouldn't, and that's why term names were changed (FYPO:0000640, FYPO:0003217, FYPO:0005315). I think I might have a better idea whether they can change back once I understand what defines a "silencing" phenotype anywhere in the genome.

**Comment by ValWood** [comment]
"chromatin silencing"  will always include heterochromatin formation, where transcriptional regulation may or may not.
We can be more specific in the constitutive heterochromatin regions:

"In addition to the larger constitutive heterochromatin regions found at centromeres, the mating-type region, rDNA, and telomeres, there are also so-called facultative heterochromatin regions in S. pombe (Zofall et al. 2012). These heterochromatic “islands” are present in vegetative cells and contain clusters of genes that are expressed and, hence, euchromatic in meiotic cells. "

and say that this  abolished/decreased  silencing is  something along the lines of

"derepression of  the epigenetically regulated region of constitutive heterochromatin at the centromere/telomere/rDNA/mating type region  by heterochromatin misassembly or disassembly )

Then at the facultative regions we can say 
"derepression of a region of the facultative heterochromatin at the blah by heterochromatin misassembly or disassembly)

Does that work?

We can say there is "silencing at the central core" as a phenotype. It was only that  it seemed odd to have  this annotated to "silencing/ negative regulation of gene expression" by GO, or to have a GO term for it. There is no control of gene expression at the central core. Any transcription is  cryptic/non functional .

**Comment by ValWood** [comment]
More thoughts on this. Basically it has been a bit of a mess in GO for ages, because nobody really knew the scope of silencing when  thses were first added to GO.

Part of the problem is because "chromatin silencing"  as used by the community, should not strictly have been a GO process. "chromatin silencing" can refer to *anything* which affects heterochromatin assembly OR maintenance. This would include, for example the factors which tether the heterochromatin to the nuclear envelope. In GO these became annotated to "negative regulation of transcription" which is clearly incorrect. But a "chromatin silencing" phenotype term would be OK.

**Comment by mah11** [comment]
There's still the same problem for the centromere central core: because it doesn't have heterochromatin, these two statements contradict each other:

> "chromatin silencing" will always include heterochromatin formation

 and

> We can say there is "silencing at the central core" as a phenotype

Apart from that -- i.e. for everywhere except the central core -- it sounds like it would work define silencing phenotypes as affecting transcription in a region of the genome that is normally assembled into heterochromatin (whether constitutively or facultatively; most of the location-specific terms refer to constitutive ones).

So I think I've got it for the general case, and have come back round to the specific case of the central core, which still looks like an exception.

**Comment by ValWood** [comment]
Ah got you.

Then can we say  OR GO:0061638    CENP-A containing chromatin"

That should cover everything.

**Comment by mah11** [comment]
So - just to confirm - this part of the stuff above wasn't accurate?

> "chromatin silencing" will always include heterochromatin formation

And you *do* want to reverse the term name changes from #2904? (affected FYPO:0000640, FYPO:0003217, FYPO:0005315)

**Comment by ValWood** [comment]
So heterochromatin assembly OR maintenance OR CENP-A containing chromatin assembly or maintenance
will cover it.

And yes, we can call the phenotypes
chromatin silencing at centromere central core

Sorry about the to  and fro-ing.  It's taken me a while to get my head around this. In fact I've been avoiding it for years......

**Comment by mah11** [comment]
Well, my share of the to-and-fro is probably at least partly because I *still* don't really have my head round it! So I ask what looks like a simple question that turns out not to be ...

I'll run with this and hope we don't end up wanting to change it back yet again somewhere along the line.

**Comment by mah11** [comment]
OK, basically done

edit file: 1406da4f08419332f5edf314d3b32c69f3d7202f
release: e78a27623827f37533246f6b61131aff7b85e8ed
