### ISSUE TITLE
missing parent

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3692]
I dont see

FYPO:0005845 | decreased histone H3-K9 trimethylation at silent mating-type cassette during vegetative growth

(or di-)

under
FYPO:- | decreased histone H3-K9 methylation at silent mating-type cassette during vegetative growth

**Comment by mah11** [comment]
buggeration. I expected those to be inferred. I'll have a closer look tomorrow ... really hope I don't have to assert manually 'cos it'd be a right pain.

**Comment by mah11** [comment]
note to self: try adding generic "abnormal histone methylation at silent mating-type cassette" & see if that spawns nice inferences

**Comment by mah11** [comment]
added these yesterday:
  abnormal histone methylation at silent mating-type cassette during vegetative growth FYPO:0007373
  abnormal histone methylation at centromere during vegetative growth FYPO:0007374
  abnormal histone methylation at telomere during vegetative growth FYPO:0007375

it's getting closer - FYPO:0005845 gets inferred as is_a FYPO:0007373. If that's close enough, close this. Otherwise I think I may have to add more intermediate terms (e.g. decreased histone methylation at x) to get all the detailed inferences ... which would still be less work than asserting the whole entangled mess.

edit file: 03fe37fd3c65983cd38ae7fa17a7f2930fabcdb9
release: e1e110f55e2353a6a104997adde5d82959ee8c56
