### ISSUE TITLE
are these saying the same decreased bipolar/increased monopolar

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3694]
I made a note about this when I was checking a session recently.
 This seems to be saying the same thing in a different way?

decreased activation of bipolar cell growth (FYPO:0003150) [single allele genotypes] AND increased monopolar index (FYPO:0003532) [single allele genotypes])

**Comment by mah11** [comment]
FYPO:0003532 could well be a consequence of FYPO:0003150. 

FYPO:0003532 is for experiments that count how many cells in a population (i.e. proportion) are doing monopolar growth. 

If there's any way to observe NETO (or lack thereof) more directly, I would use FYPO:0003150 for that rather than merge the terms.

On the other hand, if determining monopolar index is the only way to assess NETO, then if we merge the terms it would make sense to retain the "monopolar index" name and def, and it would end up with the parentage that FYPO:0003532 has now, i.e. under population phenotype. It wouldn't keep the connection to cellular process phenotypes via FYPO:0003150's current parent (FYPO:0000147 ! abnormal activation of bipolar cell growth).

Does that make sense?

**Comment by ValWood** [comment]
Yes.

You can observe increased monopolar growth/abolishes bipolar growth by observing single cells
like in  figure 1 d here
https://www.cell.com/current-biology/fulltext/S0960-9822(02)00821-7?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0960982202008217%3Fshowall%3Dtrue

**Comment by mah11** [comment]
OK, that argues against merging.

Is it safe (and desirable) to add an output link?

**Comment by ValWood** [comment]
I think so. 

increased monopolar index (FYPO:0003532) [single allele genotypes])
always results in
decreased activation of bipolar cell growth (FYPO:0003150) [single allele genotypes] AND

**Comment by mah11** [comment]
link added yesterday; closing now

edit file: 03fe37fd3c65983cd38ae7fa17a7f2930fabcdb9
release: e1e110f55e2353a6a104997adde5d82959ee8c56
