### ISSUE TITLE
NTR: abolished activation of bipolar cell growth with growth from the new end PMID:12007420

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3699]
child of
abolished activation of bipolar cell growth

I'm sure we have seen this before?

<img width="394" alt="Screen Shot 2020-05-17 at 18 44 18" src="https://user-images.githubusercontent.com/7359272/82155660-71b91180-986e-11ea-97ab-149335bc1ffe.png">

@JackyVH  described as
Monopolar growth pattern in cells with NETO defect
Monopolar growth in daughter cell is initiated at growing end inherited from mother cell and monopolar growth in daughter cell is initiated at cell end created by septation.

**Comment by mah11** [comment]
Please see #3537 and #3614, and see if they cover this as well (#2839 may also be related).

**Comment by ValWood** [comment]
yes also
abolished activation of bipolar cell growth in both daughter cells  with growth initiated from the old end 
(normally is new end)

**Comment by mah11** [comment]
> abolished activation of bipolar cell growth in both daughter cells with growth initiated from the old end
> (normally is new end)

OK, now I'm really confused. Don't wild-type cells start growing at the old end, and then grow at both ends after NETO?

But looking at the figure, I think I'd suggest terms:

- left: looks like the same thing for which I added FYPO:0007242 (see PMID:31719163 fig 6C); the def doesn't specify that both daughters grow from the old end, but I can add that
- middle: FYPO:new growth only from old end in daughter that inherited mother's growing end, and growth only from new end in other daughter
- right: FYPO:new like FYPO:0007242 but with growth from the new instead of old ends in both daughters (and to me that implies premature NETO in both)

Does that sound like it would help?

**Comment by ValWood** [comment]
> OK, now I'm really confused. Don't wild-type cells start growing at the old end, and then grow at both ends after NETO? 

fixed above.

**Comment by ValWood** [comment]
Abolished activation or bipolar growth with (monopolar) growth from the new end
is all I need here.

**Comment by mah11** [comment]
OK.

Tangential question: In GO, the NETO synonyms were moved from GO:0051519 'activation of bipolar cell growth' to GO:0051523 'cell growth mode switching, monopolar to bipolar' a while ago, but the FYPO terms for NETO-related phenotypes date back to before that GO change. So now GO and FYPO aren't quite completely consistent.

Will it be OK if I change the FYPO NETO terms that have logical definitions to use GO:0051523?

I would also change the term names so they don't follow GO:0051519 any more, but the new term here makes me worry that using "NETO" in the names might not be ideal. Would "normal/abnormal/etc. switch from monopolar to bipolar cell growth" work (with the GO term name in exact synonyms)?

**Comment by mah11** [comment]
added:
abolished switch from monopolar to bipolar cell growth, with growth from new end FYPO:0007387

moved the tangent about NETO terms to #3279; it's too buried here
