### ISSUE TITLE
NTR: elongated T-shaped vegetative cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3704]
Definition | Parents
-- | --
A cell morphology phenotype observed in the vegetative growth phase of the life cycle in which a new growth zone forms along the lateral portion of the cell (often in the middle) before septation, such that a single cell grows in the form of the letter T.  Cells are also elongated.

PMID:9679144

I was going to suggest parent
T-shaped vegetative cell (FYPO:0000013)
but this specifies normal length?

Also, to T-shaped we can add  that "the new growth zone  forms before NETO"
as part of the differetia for the 'othere type of branched' althugh in most cases we will not be able to judgge this...

**Comment by ValWood** [comment]
You can see the difference from the other (cytokinesis defect)  branched even if it's difficult to describe...


<img width="284" alt="Screen Shot 2020-05-18 at 18 46 01" src="https://user-images.githubusercontent.com/7359272/82243611-d4c2ab00-9937-11ea-9935-9ad02fd2d158.png">

**Comment by mah11** [comment]
> I was going to suggest parent
> T-shaped vegetative cell (FYPO:0000013)
> but this specifies normal length?

The definitions for cell morphology phenotypes will pretty much just reflect whatever you and Jacky told me about them, especially terms dating back to the beginnings of FYPO (as this one does). I'm not opposed to changing old definitions, as long as you've thought it through -- e.g. can you remember why the bit about normal cell length was included in the first place? (I've looked but haven't found anything in things I can reach from here; it may have come up in a meeting and not been recorded in email or a ticket.) And are you confident that it won't need to change back in a week or a month?

> Also, to T-shaped we can add that "the new growth zone forms before NETO"
> as part of the differentiae for [from?] the 'other type of branched' although in most cases we will not be able to judge this.

I can put it in the text definition. I don't have a way to include it in a logical definition. (I'd be a little uneasy about building something into a logical def if "in most cases we will not be able to judge this" but the main reason is simply that I'm not aware of suitable ontology terms and relations, and it's not worth requesting any for one phenotype term.)

> You can see the difference 

Erm, actually, no, I can't see any difference because there's only one image. (And no, I have not memorized the appearance of every morphology phenotype ;) )

**Comment by ValWood** [comment]
It's subtle but the branching is much less uniform in the none-T type
<img width="356" alt="Screen Shot 2020-05-19 at 15 56 32" src="https://user-images.githubusercontent.com/7359272/82342324-64746200-99e9-11ea-9e8d-b7113ecabd99.png">

**Comment by ValWood** [comment]
OK, sorry it wasn't clear. This is a new term. Usually, the T-s are not elongated. These are, because they were harvested from a cell cycle block +TBZ
So this is the same as the existing T-shaped, but it's elongated.  But the ones we annotated so far are not elongated.

MAybe we need
T-shaped
-- T-shaped with WT length (the existing T-shaped)
-- T shaped elongated.

Could the  extra part
"the new growth zone forms before NETO"

just be in a comment
i.e although  it will not often be possible to tell, T-shaped cells from before NETO, while other types of branching occur during cytokinesis

@JackyVH is that  comment correct?

**Comment by mah11** [comment]
> OK, sorry it wasn't clear. This is a new term. 

That was clear. The rest of the paragraph doesn't add anything.

> Maybe we need
> T-shaped
> -- T-shaped with WT length (the existing T-shaped)
> -- T shaped elongated.

That would avoid the single-subclass issue that formal ontology geeks frown upon. My question was aimed at finding out whether you do indeed want this set of terms in FYPO.

**Comment by ValWood** [comment]
Yes please- with the comment.

**Comment by mah11** [comment]
new terms
  T-shaped vegetative cell FYPO:0007379
  elongated T-shaped vegetative cell FYPO:0007380

renamed FYPO:0000013 to add 'normal cell length'
added/edited comments
