### ISSUE TITLE
NTR: increased length at division during nitrogen stress

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3760]
~Do you think we could rename
FYPO:0000998 | elongated cell during nitrogen starvation
and
FYPO:0005664 viable elongated cell during nitrogen starvation
to 
 increased length at mitosis during nitrogen stress
A  *** phenotype in which a cell divides at a longer length than normal during nitrogen stress
because it make the phenotype  clearer (and reflects the experiments better)
This part of the comment can stay the same 
Comment: 
Note that wild-type cells become shorter under nitrogen starvation conditions than under nitrogen-replete conditions, and that mutant cells subjected to nitrogen starvation may have lengths similar to wild type cells under non-starved conditions. 
I don't know if this is true for this phenotype. The proportions are the same as WT, unlike vegetative cells under non-nitrogen starved conditions:
Also note that this term is classified as a type of abnormal cell shape, because under a given set of conditions wild-type cells are never seen with the proportions (length:diameter ratio) observed in elongated cells. Small cells, in contrast, have the same proportions as a subset of wild-type cells, and simply do not grow to the full length seen in wild type. This term can be used for any circumstances in which cells are starved for nitrogen.~

replaced https://github.com/pombase/fypo/issues/3763

@Antonialock 
@JackyVH 

Do you agree with this change?  You have both annotated such papers. The one I am looking at 
PMID:25639242 this annotation would be better than "increased length during nitrogen starvation"

**Comment by Antonialock** [comment]
No - it wouldn't fit most annotations. 

Most experiments will starve cells of nitrogen - the paper you reference state that they "nitrogen stress" the cells (from the conditions column I can see that they shifted the nitrogen source to proline which is generally regarded a poor nitrogen source (in pombe)).

If I annotated the paper I probably didn't request a new term distinguishing stress / starvation because the distinction is too wishy washy without clearer knowledge of how to make the distinction (and maybe the distinction hadn't been made for other papers - there are def other papers using proline nitrogen mediums, are they always considered 'stress' and not the more severely limiting 'starvation'?).

Anyway it won't work because once stress becomes starvation they perform two cell divisions and then arrest in G0 - so increased length at mitosis during nitrogen stress won't be true for most genes annotated to these terms.  e.g. https://www.pombase.org/reference/PMID:19366728

**Comment by ValWood** [comment]
Hmm, I assumed that all of these experiments looking at vegetative  cell length during nitrogen depletion were done under stress rather than starvation (they don't want to induce  quiescence presumably, because they could not then do the experiments looking at vegetative cell length because they would have a mixture of vegetative and small cells?)

If this is NOT the case  could the term be named 
increased length at mitosis during nitrogen starvation?

It seems that  we can be specific enough to say that this phenotype is observed at division time (this is not  true for all elongated, for example cytokinesis defects which elongate without dividing).

Although I still think it would be *Much* clearer to say 
increased length at mitosis during nitrogen stress
for the experiments where people look at vegetative nitrogen stressed cells.

If we mix these two things together it's difficult to separate the important observations  about these effects on the vegetative cell cycle. We can't separate the nutrient sensing ability of TOR from  entry into quiescence type of experiments.

I thought maybe 'nitrogen stress' could be defined as  a poor nitrogen source (i.e not limiting enough to induce G0).

**Comment by ValWood** [comment]
We have  things like sal3 that when disrupted cannot respond to N starvation because they are stuck at G2/M. These really are elongated (but also inviable). You get a half size colony because you can only do one division.

The other set are things where we are trying to capture the response to a shift in Nitrogen source from good to poor. These are viable, but  WT divide at a smaller size.
Some mutants divide at a larger  size than WT  in these conditions (but still smaller then WT when not N-)
 (presumably this is for all the experiments  analysing TOR and nutrient sensing)

It's really important to separate these two phenotypes because they are due to different phenomena and they  look totally different (1 are dead and superlong, 2 are viable and shorter than normal WT) but currently we are using the same term for both.


FYPO:0000998 | elongated cell during nitrogen ~starvation~ depletion
-- FYPO:NEW | inviable elongated cell during nitrogen starvation
This would be the cells that die very elongated before G0 entry (with the G2 block)

-- FYPO:NEW| viable elongated vegetative cell during nitrogen stress (defined as poor nitrogen source)
For the ones  which have a problem with the nutrient sensing pathway

would that work?

Either way I will need
 FYPO:NEW| viable elongated vegetative cell during nitrogen stress (defined as poor nitrogen source)

**Comment by ValWood** [comment]
Maybe  a better way to describe the changes I am looking at is

decreased change in length after nitrogen starvation

this makes it clearer to the casual 'reader' what  is happening.

upon starvation WT get shorter
These cells do not get as short as normal WT

This is more similar to this term
abolished cell division timing change upon nitrogen source shift 
which I now understand!

There is a timing change, and a length change and the are not always coincident.

**Comment by ValWood** [comment]
SO, my problem is that term reads as though the cells are getting longer, but really they are just not getting as short.
DOes that make sense?

**Comment by mah11** [comment]
Wow, a lot to try to unpack here ...

First, the most important thing: I strongly oppose using "nitrogen stress" in term names. There isn't a corresponding GO process (as there is for N starvation), and it's vaguer than specifying starvation or N source change (it doesn't even rule out excess N!).

(I'm not sure switching N sources is necessarily stressful -- it's something pombe's wild counterparts would have to do all the time. But I won't fuss further on that aspect of this because it's not an area I know well at all.)

**Comment by mah11** [comment]
Second, is the argument for 

> increased length at mitosis during nitrogen [yada]

that  the altered length:width ratio that characterizes "elongated" cells doesn't always apply? If so, I can switch to "increased cell length".

And you've confirmed that the "at mitosis" part would apply to everything currently annotated to either FYPO:0000998 or FYPO:0005664, right?

**Comment by mah11** [comment]
> reduced cell length decrease after nitrogen starvation

If I saw it in the wild I would have *no* idea what it means! I would infer some unpleasant copy/paste incident.

I'll try to think of some way to convey the "doesn't shrink like wild type" notion better, but "reduced decrease" is not a good way to do it, and I won't change the name until & unless we think of something that will do the job without torturing English.

**Comment by ValWood** [comment]
I'll close this ticket and open separate ones for each issue.
