### ISSUE TITLE
new term nuclear envelope protrusion/excess inm / present during mitotic interphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3786]
FYPO:0004725 | nuclear envelope protrusion present during mitotic interphase

should this be a descendant of

FYPO:0001556 | excess nuclear envelope present
(I'm worried that we might have used this term for the internal protrusions caused mby excess nuclear envelope, and the external protrusions cause by the spindle...I would need to check that)

**Comment by mah11** [comment]
No, I don't think so -- a protrusion could result from rearranging the normal amount of NE into an abnormal distribution/structure.

**Comment by ValWood** [comment]
ok
Gautam used 2 terms, both correct, for the same phenotype:

FYPO:0001556 | excess nuclear envelope present
FYPO:0004725 | nuclear envelope protrusion present during mitotic interphase

so could I have a new term, child of both


FYPO:0004725 | nuclear envelope protrusion due to  excess inner membrane  present present during mitotic interphase

**Comment by mah11** [comment]
That sounds absolutely ghastly. And looking at the figs (especially the little diagram), it wouldn't occur to me to call that a "protrusion". More importantly, we've also defined a nuclear envelope protrusion as sticking out into the cytoplasm, whereas the nem1delta phenotype looks like only the inner membrane is present in excess, and it invaginates into the nucleus (not the cytoplasm) more than in wt. So the FYPO:0004725 annotation may just be a mistake due to overlooking the "into the cytoplasm" part of the def.

But if there's actually something to gain (what?) by adding such a specific term, I can add it as "excess inner nuclear membrane protruding into nucleus during mitotic interphase".

We also have to decide whether FYPO:0001556 ! excess nuclear envelope present means extra of both membranes or just either one, and then I should also refine the text def accordingly. If it can be either membrane, then a new term could be is_a FYPO:0001556,

**Comment by ValWood** [comment]
I can delete the nuclear protrusion annotation

FYPO:0001556 ! excess nuclear envelope  
is both inner and outer membrane
for exisitng (and the phenotype looks similar to this)
 
and although the cartoon is drawn as "inner" here I'm not sure that it is really possible to tell.

So I would just go with 
FYPO: ! excess nuclear envelope   during mitotic interphase

**Comment by mah11** [comment]
OK,
  excess nuclear envelope present during mitotic interphase FYPO:0007457
