### ISSUE TITLE
question about population growth rate

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3821]
We are trying to disambiguate some head-melty stuff in PHIPO related to growth of populations both yeast form and hyphal growth and what can be inferred from this.

We have 
cell population growth phenotype 
defined like FYPO
A cell phenotype that affects the rate or extent of cell population growth.

I was expecting to see this defined as an increase/decrease  in the number of individuals so that it would not be confused with an increase/decrease in size of the individuals. Would that make sense? It seems that we need to be more specific about the 'type' of growth.

Or maybe 'cell population growth' is really only  ever applying to an increase in the number of individuals that this is unnecessary? (it gets a bit murky when looking at hyphal commonly size because colony size can be more directly related to  the growth of individual hyphae).

@CuzickA

**Comment by mah11** [comment]
We have never had to make a distinction in FYPO because (clue's in the name) for fission yeast it's felt safe to leave it implicit that population growth in an increase in the number of cells. Even for size mutants what's assayed for populations stays coupled to the number of cells in the population rather than to individual cells enlarging.

I can easily edit definitions for the FYPO population growth terms, to make it explicit that they refer to cell numbers, but I don't think the FYPO terms necessarily provide much guidance for species and contexts where it's less straightforward to tell whether numbers, individual size, or both is/are relevant.

Note, also, that when people talk about population size for "big" organisms (humans, mice, trees, etc.) they pretty much only mean how many individuals, not how tall or fat they are. Still not sure how much that helps with things like hyphae, though.

**Comment by ValWood** [comment]
Thanks. The response helped us. I mainly just wanted to check that these terms could only  refer to an increase in the number of cells. We have an alternative solution for the hyphal colony size problem.

We can make the def more explicit in PHIPO. No need to do anything here unless you think it might be useful to make the defs less self-referring for people like me. I thought I knew what it meant but I needed to check.

**Comment by mah11** [comment]
OK, glad it helped. What I'll probably do in FYPO is add some details to one or a few high-level population growth term defs, but not bother doing it for all the descendants.

**Comment by ValWood** [comment]
That makes sense...

**Comment by mah11** [comment]
OK, def edits done
