### ISSUE TITLE
rename  FYPO:0005321 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3908]
If we have terms which mention a mitotic or meiotic phase, e.g.

FYPO:0005321 | inviable elongated  mononucleate aseptate vegetative cell with cell cycle arrest             in mitotic metaphase

could we label as

FYPO:0005321 | inviable elongated  mononucleate aseptate  cell with  mitotic metaphase arrest (or similar)

in these cases,  'vegetative' is redundant in the term name.

**Comment by mah11** [comment]
I've removed "vegetative" from the names of several terms (list below) and added synonyms following a '* phase arrest' pattern.

I am reluctant to switch names from "cell cycle arrest in *phase" to "*phase arrest" because either they'd become inconsistent with all other cell cycle arrest terms ... or I'd have to rename over 80 terms, and that would be a phenomenal PITA. But reopen this if the gain for users really would outweigh the pain of doing so many switches.

renamed:
FYPO:0001497, FYPO:0003128, FYPO:0003826, FYPO:0004197, FYPO:0004922, FYPO:0005321, FYPO:0005422, FYPO:0005367

**Comment by ValWood** [comment]
Yeah it's not a big issue....

**Comment by mah11** [comment]
that's a relief!
