### ISSUE TITLE
decreased mating frequency vs. efficiency

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3919]
I don't totally understand the difference between

585 | decreased mating efficiency (FYPO:0000708) [single allele genotypes] | ...
A biological process phenotype in which the observed mating efficiency is lower than normal.

and
  | 57 | decreased mating frequency (FYPO:0000303) [single allele genotypes]
A cell population phenotype in which a smaller than normal proportion of cells in the population undergoes conjugation.

(they both appear to be population phenotypes and seem to be used interchangeably )

@JackyVH 
@Antonialock

**Comment by ValWood** [comment]
I was looking at zfs1:

<img width="678" alt="Screenshot 2021-02-23 at 19 03 35" src="https://user-images.githubusercontent.com/7359272/108894164-dda08580-7609-11eb-9edc-b693f6ac51ef.png">

**Comment by mah11** [comment]
We have "mating efficiency" terms because that phrase gets used in the literature. It's kind of unfortunate, because it doesn't actually refer only to mating, and because of the potential for confusion.

The first request for a mating efficiency term is [here](#63), and the "what's the difference" question arose [here](#628) (note that the "mating frequency" terms used to have different names; changed in #2271). Should we revert to using "conjugation" in the names for the "frequency" terms? Or would any additions/changes to the existing comments help?

id: FYPO:0000303
name: decreased mating frequency
def: "A cell population phenotype in which a smaller than normal proportion of cells in the population undergoes conjugation." [PomBase:mah]
comment: Note that this term refers specifically to conjugation, whereas experiments that measure mating efficiency often do so by counting zygotes plus asci, sometimes also including spores. For such experiments, we recommend using 'decreased mating efficiency' (FYPO:0000708).

id: FYPO:0000708
name: decreased mating efficiency
def: "A biological process phenotype in which the observed mating efficiency is lower than normal." [PMID:15300681, PMID:16598689, PomBase:al, PomBase:mah]
comment: Note that mating efficiency is often measured by counting zygotes plus asci, sometimes also including spores, so a change in measured mating efficiency may reflect a change in conjugation frequency (see FYPO:0000031 and its descendants), a change in sporulation (see FYPO:0000121 and its descendants), or both. For this reason, this term is not a child of 'mating phenotype' (FYPO:0000031).

**Comment by Antonialock** [comment]
mating efficiency is conjugation + sporulation.

You can have normal conjugation, but problems making spores.

**Comment by ValWood** [comment]
Without knowing why the change would made I think "decreased conjugation efficiency " might be clearer.
Although if I had read the comments, I would have understood the difference.

**Comment by mah11** [comment]
So is any action required?

**Comment by ValWood** [comment]
I think these seem so similar it would be really helpful if the label was "conjugation efficiency" for the ones which are stuck at conjugation. I just curated another paper and if not for this ticket I would have used "mating frequency" here too.

**Comment by mah11** [comment]
Well, these aren't necessarily "stuck" anywhere -- there's a `normal` and an `increased` term for each (and even decreased frequency could be, say, slower overall as opposed to stopped at some point). I'll change "mating frequency" to "conjugation frequency" for the ones that are specific for mating-aka-conjugation, and leave "efficiency" for the ones representing the "mating efficiency" that's really "mating and/or sporulation".

**Comment by mah11** [comment]
renaming done; I also copied a bit of the "measuring yada" text from comments to the "efficiency" defs
