### ISSUE TITLE
relationship between "mating efficiency" and "sterility"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3928]
Is there a releationship between these terms? sterility  is really an extreme form of 
decreased mating efficiency?

 | 50 | sterile (FYPO:0000280) [single allele genotypes] AND decreased mating efficiency (FYPO:0000708) [single allele genotypes] [details] | ...
  | 75 | sterile (FYPO:0000280) [single allele genotypes] | ...
  | 585 | decreased mating efficiency (FYPO:0000708) [single allele genotypes]

**Comment by mah11** [comment]
No, mainly because "mating efficiency" is a wooly phrase that we're using in phenotype terms solely because it turns up in the literature. Because what they call mating efficiency actually reflects the sum of conjugation and sporulation, it doesn't connect neatly to terms that are specific to one or the other. E.g. decreased mating efficiency could mean decreased conjugation, decreased sporulation, or both.

While it's true that sterile cells won't form diploids that could go on to sporulate, the absence of sporulation is a downstream consequence. It doesn't mean things needed for conjugation also participate in sporulation.

**Comment by mah11** [comment]
closing because it doesn't seem like any action is required
