### ISSUE TITLE
"normal microtubules during mating projection formation" PMID:11950884

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4030]
Jacky @JackyVH  requested
FYPO:0000760 | normal mating | Microscopy | + P-factor, glucose MM | normal microtubules during response to pheromone

I think I would do
"normal microtubules during mating projection formation"
as P factor is already in the conditions. This would allow positioning under 'normal mating' (I don't think response to pheromone terms can be because mating can occur also during starvation).

@mah11 
@JackyVH  does that sound right?

PMID:11950884

**Comment by mah11** [comment]
I think the opposite -- if mating can result from starvation OR pheromone response, and these experiments tested pheromone response, then the requested term name describes the observation more directly. It's also not entirely clear to me that MTs are normal *only* after shmoo formation starts -- I got the impression that MTs are normal once the cells arrest in G1.

The "P-factor" condition is still not redundant, because it specifies *which* pheromone; the suggested term name allows for either P- or M-factor.

I doubt I'd put the term under "normal mating" either way - it shouldn't be is_a or part_of because that would imply that everything else about mating is also normal, which may not be the case in every mutant with normal MTs, and we abandoned has_part (which would be logically and biologically accurate) in the "normal phenotype" branch because something was counter-intuitive about searching and/or inferences.

Related question: should the new term specify cytoplasmic MTs?

Tangential observation: a lot of the "phenotype" annotations in the session look like they're really localizations in wild type (unless tagging any of the proteins changes their localization) or effects of LatA.

**Comment by ValWood** [comment]
I don't think the experiment is testing pheromone response though. It is  testing the conserved part of conjugation which is independent of signal type (pheromone or N2 starvation). The pheromone is just happens to be the condition being used to induce mating.

Agreed it should not go under normal mating.

Related question: should the new term specify cytoplasmic MTs?
- yes please


I thought figure 5 was showing cells that were beginning to shmoo? @JackyVH  is that correct?

**Comment by ValWood** [comment]
maybe that wasn't true. 

All our experiments were carried out in a
cyr1Æsxa2Æ strain (Imai and Yamamoto, 1994), which
responds to exogenous pheromone in rich media. This allows
us to separate the pheromone response from the effects of
nitrogen starvation, which is required to induce shmooing in
wild-type cells, and therefore permits us to analyse the effects
of a single external signal (pheromone) on cell shape.

We can go with Jacky's original suggestion.

**Comment by mah11** [comment]
normal cytoplasmic microtubules FYPO:0007809 (new grouping term)
  normal cytoplasmic microtubules during cellular response to pheromone FYPO:0007810
