### ISSUE TITLE
Add synonym FYPO:0003946

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4041]
community suggested:
delayed onset of protein recruitment to site of cell division
Delayed appearance of cytokinesis proteins to the presumptive division plane.

add as synonym to 
FYPO:0003946
for searching

**Comment by mah11** [comment]
1. Is the synonym exact?
2. Should the other "protein localization to cell division site" terms also have "recruitment" synonyms?

**Comment by ValWood** [comment]
I guess all most localization terms  could have recruitment as a synonym.
I think recruitment is related_to or narrower than 'localization' 

Officially, localization includes transport.  Maybe when we use 'localization of protein' in FYPO we always mean recruitment- but we don't have recruitment as a process in 'GO' (and recruitment is usually used where one molecule directly recruits another, so this would likely be considered a MF rather than a BP). 

So, I'm not totally sure about the scope.  I would probably go with related and adjust if it is formally defined elsewhere?

**Comment by mah11** [comment]
Lately I've been thinking that most -- tho not all -- of our "protein localization to x" phenotypes are really "amount of protein detected at/in x", since they're so often based on "snapshot" observations in micrographs or westerns. But I also think life's probably too short to go back and retrofit them, especially since there are a few that really do come from experiments that can watch a localization process happen (or fail), so we can't just rename existing terms or do a brainless find/replace.

For the specific terms & synonyms here, related scope is fine with me.

**Comment by ValWood** [comment]
Yeah the localization is more of an inference. I think we can live with it unless we can think of a way to fix globally.

**Comment by mah11** [comment]
For now I've added "recruitment" related synonyms for localization to the cell division site, contractile ring, and medial cortical node. If you think of other locations where the localization terms should get synonyms, open a new ticket.
