### ISSUE TITLE
PMID:34731638 (FACT histone chaperone complex related)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4080]
- [ ] FYPO:NEW | decreased spatial extent of mating-type region heterochromatin assembly
related to
FYPO:0007480 | decreased spatial extent of subtelomeric heterochromatin assembly

- [ ] Increased histone turnover at subtelomeric heterochromatin
related to
FYPO:0007472 | abnormal histone exchange

- [ ] FYPO:NEW increased histone H2B-K119 ubiquitination  at subtelomeric heterochromatin
related to 
FYPO:0005607 abnormal histone H2B-K119 ubiquitination during vegetative growth

**Comment by ValWood** [comment]
FYPO:0007894: increased histone H2B-K119 ubiquitination at subtelomeric heterochromatin
Needs logical def
still needs logical def:

increased occurrence' goes
in place of 'quality'; it's not a "modifier" as in "'has modifier' some
abnormal", e.g.

'has part' some
    ('decreased occurrence'
     and ('characteristic of' some
        ('histone H2A phosphorylation'
         and ('happens during' some 'single-celled organism vegetative
growth phase'))))

**Comment by ValWood** [comment]
In this ticket I also swapped "exchange' for 'turnover' in primary names and added exact synonyms.

**Comment by ValWood** [comment]
missed
 | increased histone H2B-K119 ubiquitination at pericentromeric  heterochromatin
-- | --

**Comment by ValWood** [comment]
@mah11  do you think the label should be
"Increased histone turnover at subtelomeric heterochromatin"
Or
"Increased histone turnover in subtelomeric heterochromatin"
(in seems more accurate)

**Comment by ValWood** [comment]
@mah11 
Should I be modelling
decreased protein level at chromatin during vegetative growth
as
decreased protein localization to  chromatin during vegetative growth
?
I'm wondering why these terms don't already exist...

**Comment by mah11** [comment]
> do you think the label should be
> "Increased histone turnover at subtelomeric heterochromatin"
> Or
> "Increased histone turnover in subtelomeric heterochromatin"

No strong preference, so if you prefer "in", go with it.


> Should I be modelling
> decreased protein level at chromatin during vegetative growth
> as
> decreased protein localization to chromatin during vegetative growth?

That's what I would do, given that we've been muddying the distinction for ~10 years now :P With hindsight, we probably should have done a lot of the protein localization terms as protein level, but we might get away with it because the uPheno patterns will use an "efficacy" quality -- more in this vein in comments on a uPheno pull request, starting roughly [here](https://github.com/obophenotype/upheno/pull/762#discussion_r718456226), esp. [this](https://github.com/obophenotype/upheno/pull/762#discussion_r718465748).

**Comment by ValWood** [comment]
we have
decreased protein level at centromere outer repeat heterochromatin
though
