### ISSUE TITLE
FYPO:0000512

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4151]
Once annotations in https://github.com/pombase/curation/issues/3251 are re-assigned.

**Comment by ValWood** [comment]
I followed the steps for deprecate  but it does not look like the ones Midori has obsoleted previously (it appears as deprecated, not 'obsolete')


At one point  there were 3 options
Basic
GO
or OBI
(I chose "Basic" but I do not know if this was the correct option)

@matentzn 
@nicolevasilevsky 

I guess I will see if something goes terrible wrong...

**Comment by matentzn** [comment]
I am not sure why I was tagged here, but I think we should try to consolidate deprecation here: https://oboacademy.github.io/obook/howto/obsolete-term/

Indeed, we should not use the word "deprecate" at all - just obsolete!

**Comment by nicolevasilevsky** [comment]
@ValWood I can't see what was done, is there a PR that you'd like me to look at?

You can also use the Protege 'Make entity obsolete' function, which is described [here](https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#obsolete-a-class-without-merging) (and this is missing in the OBO Academy documentation, I will add it.

**Comment by ValWood** [comment]
Hi Nicole. 
I don't know how to point to a pull request.
It was part of the edits I did in the branch with the linked issues above, and is now in the current release.
We recently switched from the editing in  a branch, rather than master, as advised, but we only do one pull request for the release (following the protocol of our legacy pipeline). The branch containing this edit was successful and is now deleted.

Essentially, I looked for an "obsolete option" in Protege, but could not see it. But I found depracate, so I assumed it must be the same thing. I can follow the obsolete instructions that you provided here in future. 

Presumably I can 'undeprecate' this term somehow, and obsolete it instead. I will look at this when I am next editing FYPO (Likely the week beginning 6th June).  If I get stuck I'll let you know.
Thanks!

**Comment by nicolevasilevsky** [comment]
@ValWood in my protege, I have an open to Make entity obsolete (see screenshot below). 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/6722114/171315448-c26d217a-8d42-431d-8e90-45638a3d66f0.png">

I think you chose the Deprecate entity option - do you not have the option Make entity obsolete? I don't know why that is, but I have seen that before with another colleague (and their version of Protege was the most recent version).

In the future, it is fine to use the Deprecate entity option, but you should choose GO, as it will prepend the label with 'obsolete [label]' instead of 'deprecate [label]'.

Alternatively, you can follow the directions here, as @matentzn pointed out:
https://oboacademy.github.io/obook/howto/obsolete-term/#obsoletion-process-manual

That being said - I just looked at your fypo.owl file and the term does not appear to be obsoleted (unless I am looking in the wrong place). Do you see that it has been obsoleted?

**Comment by ValWood** [comment]
I think Nicole is away, I have obsoletion instructions. Will send straight after  my talk

**Comment by ValWood** [comment]
OK, they are in this ticket! I  did not see obsoletion in the menu either.

**Comment by matentzn** [comment]
@nicolevasilevsky is it possible this is because you have the protege OBO plugin installed?

https://github.com/monarch-initiative/protege-obo-plugin

**Comment by ValWood** [comment]
Right, so we likely need OBO plugin and  Elk plug-in. Anything else? Is there a list of things we should have in our set-up?

Thanks,
v

**Comment by matentzn** [comment]
Can you as this question on the obook issue tracker? We should have / make a page for it.

**Comment by ValWood** [comment]
https://github.com/OBOAcademy/obook/issues/197

**Comment by manulera** [comment]
But the obo plugin description on github does say:

> A plug-in for Protege that provides entry fields for standard OBO annotation properties, as well as menu actions such as term obsoletion.
