### ISSUE TITLE
NTR for community curation PMID:35970865

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4211]
FYPO:NTR | decreased protein localization to CENP-A containing chromatin during M-phase
child of 
FYPO:0004313 | decreased protein localization to CENP-A containing chromatin

Masamitsu suggested
decreased CENP-A maintenance during M-phase
but I used the existing "protein localization to CENP-A region" with "cnp1" as assayed protein throughout

However, the crux of the paper is that the Mis6 and Mis15 are required for correct localization (maintenance) of cnp1 during M- phase, so we need the new pre-composed term for that.

**Comment by manulera** [comment]
Done in protege

**Comment by ValWood** [comment]
damn, I was also supposed to request 

normal protein localization to CENP-A containing chromatin during M-phase,
and increased.

**Comment by ValWood** [comment]
no hurry, you can do it with  the next batch.

**Comment by manulera** [comment]
Hi @ValWood,

I was going to substitute the new terms in the session, but I am not sure where since some are initially annotated to `normal protein localization to centromere central core` and not `normal protein localization to CENP-A containing chromatin`.

From the comments in the session, it seems you also need `normal chromatin silencing at centromere during mitosis`?

Let me know if more terms are needed.

Best,
Manu

**Comment by ValWood** [comment]
All sorted.
