### ISSUE TITLE
FYPO merge error

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4362]
I always get this error

<img width="509" alt="Screenshot 2023-06-20 at 16 07 55" src="https://github.com/pombase/fypo/assets/7359272/6242eb16-3cf3-4fa4-8e8d-ed1203706906">

does anyone know why?

**Comment by manulera** [comment]
Hi @ValWood. I think this is unrelated to #4360. I am pasting here the answer from a previous email exchange so that it's easier to find. I will reply to the email so that you see it.

Short answer:

Do git branch -D (capital letter), then go to master and pull

Long answer:

The problem may arise because of the "Squash and merge" that occurs in the pull request. Basically, when you create your branch you made a series of commits, and then made a pull request. When the pull request is merged into master, all changes made to your branch in several commits get squashed into a single commit, so even though your branch and master are identical in the code, their histories are not. Maybe this also happens if there is a single commit when you run squash and merge.

![download](https://github.com/pombase/fypo/assets/22526102/c066b39f-db03-4185-9526-38a883da2e94)

**Comment by ValWood** [comment]
I remember you told me this before.
